const en = {
    rolesTitle: 'Roles for this run', rolesYour: 'Your roles',
    rolesChanged: ({ count }: { count: number }) => `${count} changed for this run`,
    rolesUnchanged: 'Everything else stays the same.', useYourRole: 'Use your role',
    targetsTitle: 'Each step runs in', rolesPrefillFailed: 'Could not read the roles from your last run. Try again.',
    frozenRepeatUnavailable: 'Frozen roles or child workflows cannot be repeated yet. Open as a new draft and review its roles and steps before starting.',
};
export const workflowRunRoleTranslations: Record<'en'|'de'|'es'|'fr'|'it'|'pt'|'ca'|'pl'|'ru'|'ja'|'zhHans'|'zhHant', typeof en> = {
    en,
    de: { rolesTitle: 'Rollen für diesen Lauf', rolesYour: 'Deine Rollen', rolesChanged: ({ count }) => `${count} für diesen Lauf geändert`, rolesUnchanged: 'Alles andere bleibt gleich.', useYourRole: 'Deine Rolle verwenden', targetsTitle: 'Jeder Schritt läuft in', rolesPrefillFailed: 'Die Rollen deines letzten Laufs konnten nicht gelesen werden. Versuche es erneut.', frozenRepeatUnavailable: 'Eingefrorene Rollen oder untergeordnete Workflows können noch nicht wiederholt werden. Öffne einen neuen Entwurf und prüfe vor dem Start Rollen und Schritte.' },
    es: { rolesTitle: 'Roles para esta ejecución', rolesYour: 'Tus roles', rolesChanged: ({ count }) => `${count} cambiados para esta ejecución`, rolesUnchanged: 'Todo lo demás sigue igual.', useYourRole: 'Usar tu rol', targetsTitle: 'Cada paso se ejecuta en', rolesPrefillFailed: 'No se pudieron leer los roles de tu última ejecución. Inténtalo de nuevo.', frozenRepeatUnavailable: 'Todavía no se pueden repetir roles o flujos secundarios congelados. Abre un nuevo borrador y revisa sus roles y pasos antes de iniciar.' },
    fr: { rolesTitle: 'Rôles pour cette exécution', rolesYour: 'Vos rôles', rolesChanged: ({ count }) => `${count} modifiés pour cette exécution`, rolesUnchanged: 'Tout le reste reste identique.', useYourRole: 'Utiliser votre rôle', targetsTitle: 'Chaque étape s’exécute dans', rolesPrefillFailed: 'Impossible de lire les rôles de votre dernière exécution. Réessayez.', frozenRepeatUnavailable: 'Les rôles ou workflows enfants figés ne peuvent pas encore être répétés. Ouvrez un nouveau brouillon et vérifiez ses rôles et étapes avant de démarrer.' },
    it: { rolesTitle: 'Ruoli per questa esecuzione', rolesYour: 'I tuoi ruoli', rolesChanged: ({ count }) => `${count} modificati per questa esecuzione`, rolesUnchanged: 'Tutto il resto rimane invariato.', useYourRole: 'Usa il tuo ruolo', targetsTitle: 'Ogni passaggio viene eseguito in', rolesPrefillFailed: 'Impossibile leggere i ruoli della tua ultima esecuzione. Riprova.', frozenRepeatUnavailable: 'Ruoli o flussi secondari congelati non possono ancora essere ripetuti. Apri una nuova bozza e verifica ruoli e passaggi prima di avviare.' },
    pt: { rolesTitle: 'Funções para esta execução', rolesYour: 'Suas funções', rolesChanged: ({ count }) => `${count} alteradas para esta execução`, rolesUnchanged: 'Todo o resto permanece igual.', useYourRole: 'Usar sua função', targetsTitle: 'Cada passo é executado em', rolesPrefillFailed: 'Não foi possível ler as funções da sua última execução. Tente novamente.', frozenRepeatUnavailable: 'Funções ou fluxos secundários congelados ainda não podem ser repetidos. Abra um novo rascunho e revise suas funções e passos antes de iniciar.' },
    ca: { rolesTitle: 'Rols per a aquesta execució', rolesYour: 'Els teus rols', rolesChanged: ({ count }) => `${count} canviats per a aquesta execució`, rolesUnchanged: 'Tota la resta continua igual.', useYourRole: 'Fes servir el teu rol', targetsTitle: 'Cada pas s’executa en', rolesPrefillFailed: 'No s’han pogut llegir els rols de la teva última execució. Torna-ho a provar.', frozenRepeatUnavailable: 'Encara no es poden repetir rols o fluxos secundaris congelats. Obre un esborrany nou i revisa els rols i passos abans d’iniciar.' },
    pl: { rolesTitle: 'Role dla tego uruchomienia', rolesYour: 'Twoje role', rolesChanged: ({ count }) => `${count} zmienionych dla tego uruchomienia`, rolesUnchanged: 'Wszystko inne pozostaje bez zmian.', useYourRole: 'Użyj swojej roli', targetsTitle: 'Każdy krok działa w', rolesPrefillFailed: 'Nie udało się odczytać ról z ostatniego uruchomienia. Spróbuj ponownie.', frozenRepeatUnavailable: 'Utrwalonych ról lub podrzędnych workflow nie można jeszcze powtórzyć. Otwórz nowy szkic i sprawdź jego role i kroki przed uruchomieniem.' },
    ru: { rolesTitle: 'Роли для этого запуска', rolesYour: 'Ваши роли', rolesChanged: ({ count }) => `${count} изменено для этого запуска`, rolesUnchanged: 'Всё остальное остаётся прежним.', useYourRole: 'Использовать вашу роль', targetsTitle: 'Каждый шаг выполняется в', rolesPrefillFailed: 'Не удалось прочитать роли вашего последнего запуска. Попробуйте ещё раз.', frozenRepeatUnavailable: 'Зафиксированные роли или дочерние процессы пока нельзя повторить. Откройте новый черновик и проверьте его роли и шаги перед запуском.' },
    ja: { rolesTitle: 'この実行のロール', rolesYour: 'あなたのロール', rolesChanged: ({ count }) => `この実行で${count}件変更`, rolesUnchanged: 'その他は変わりません。', useYourRole: '自分のロールを使用', targetsTitle: '各ステップの実行先', rolesPrefillFailed: '前回の実行のロールを読み込めませんでした。再試行してください。', frozenRepeatUnavailable: '固定されたロールや子ワークフローはまだ再実行できません。新しい下書きを開き、開始前にロールとステップを確認してください。' },
    zhHans: { rolesTitle: '本次运行的角色', rolesYour: '你的角色', rolesChanged: ({ count }) => `本次运行更改了 ${count} 个`, rolesUnchanged: '其他内容保持不变。', useYourRole: '使用你的角色', targetsTitle: '每个步骤运行于', rolesPrefillFailed: '无法读取你上次运行的角色。请重试。', frozenRepeatUnavailable: '暂时无法重复已冻结的角色或子工作流。请打开新草稿，并在开始前检查其角色和步骤。' },
    zhHant: { rolesTitle: '本次執行的角色', rolesYour: '你的角色', rolesChanged: ({ count }) => `本次執行更改了 ${count} 個`, rolesUnchanged: '其他內容保持不變。', useYourRole: '使用你的角色', targetsTitle: '每個步驟執行於', rolesPrefillFailed: '無法讀取你上次執行的角色。請重試。', frozenRepeatUnavailable: '暫時無法重複已凍結的角色或子工作流程。請開啟新草稿，並在開始前檢查其角色和步驟。' },
};
