import { CLAUDE_OAUTH_CLIENT_ID, CLAUDE_OAUTH_TOKEN_URL } from '../../providers/claude/oauthProfile.js';
import { OPENAI_CODEX_CLIENT_ID, OPENAI_CODEX_TOKEN_URL } from '../../providers/codex/oauth.js';
import { defineServerConfigRegistry } from '../serverConfigEntry.js';

/**
 * Push, Live Activities, voice, billing, connected services, plugins and other integrations:
 * credentials of external services, their limits, and server-resource tuning.
 */

export const INTEGRATIONS_SERVER_CONFIG = defineServerConfigRegistry({
    // Live Activity remote updates.
    HAPPIER_LIVE_ACTIVITY_REMOTE_UPDATES_ENABLED: {
        type: 'boolean',
        default: false,
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'liveActivity',
        description: 'Pushes Live Activity updates to iOS devices while the app is in the background.',
        docs: 'self-hosting/env#live-activity-remote-updates-optional',
    },
    HAPPIER_LIVE_ACTIVITY_REMOTE_UPDATE_MODE: {
        type: 'enum',
        default: 'local_only',
        bounds: { values: ['hosted_happier_relay', 'direct_apns', 'background_wake_best_effort', 'local_only', 'disabled'] },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'liveActivity',
        description: 'Preferred way to deliver Live Activity updates.',
        docs: 'self-hosting/env#live-activity-remote-updates-optional',
    },
    HAPPIER_LIVE_ACTIVITY_REMOTE_UPDATE_ALLOW_FALLBACK: {
        type: 'boolean',
        default: false,
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'liveActivity',
        description: 'Falls back to another delivery mode when the preferred one is unavailable.',
        docs: 'self-hosting/env#live-activity-remote-updates-optional',
    },
    HAPPIER_LIVE_ACTIVITY_REMOTE_UPDATE_DEDUPE_WINDOW_MS: {
        type: 'int',
        default: 30_000,
        bounds: { min: 0, max: 86_400_000 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'liveActivity',
        description: 'Milliseconds within which a repeated identical Live Activity update is dropped.',
        docs: 'self-hosting/env#live-activity-remote-updates-optional',
    },
    HAPPIER_LIVE_ACTIVITY_BACKGROUND_WAKE_ENABLED: {
        type: 'boolean',
        default: false,
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'liveActivity',
        description: 'Allows best-effort background-wake pushes as a Live Activity delivery mode.',
        docs: 'self-hosting/env#live-activity-remote-updates-optional',
    },
    HAPPIER_LIVE_ACTIVITY_BACKGROUND_WAKE_MIN_INTERVAL_MS: {
        type: 'int',
        default: 60_000,
        bounds: { min: 0, max: 86_400_000 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'liveActivity',
        description: 'Shortest time between two background-wake pushes to one device, in milliseconds.',
        docs: 'self-hosting/env#live-activity-remote-updates-optional',
    },
    HAPPIER_LIVE_ACTIVITY_EXPO_WIDGETS_PUSH_NOTIFICATIONS_ENABLED: {
        type: 'boolean',
        default: true,
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'liveActivity',
        description: 'Reports that the iOS widgets build can receive push notifications.',
    },
    HAPPIER_LIVE_ACTIVITY_TARGET_TRANSIENT_FAILURE_BUDGET: {
        type: 'int',
        default: 50,
        bounds: { min: 1, max: 10_000 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'liveActivity',
        description: 'Transient delivery failures a Live Activity target may accumulate before it is dropped.',
    },
    HAPPIER_LIVE_ACTIVITY_APNS_ENVIRONMENT: {
        type: 'enum',
        default: 'sandbox',
        bounds: { values: ['sandbox', 'production'] },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'liveActivity',
        description: 'Apple push environment for direct delivery.',
        docs: 'self-hosting/env#live-activity-remote-updates-optional',
    },
    HAPPIER_LIVE_ACTIVITY_APNS_TEAM_ID: {
        type: 'string',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'liveActivity',
        description: 'Apple developer team id for direct push delivery.',
        docs: 'self-hosting/env#live-activity-remote-updates-optional',
    },
    HAPPIER_LIVE_ACTIVITY_APNS_KEY_ID: {
        type: 'string',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'liveActivity',
        description: 'Id of the Apple push signing key.',
        docs: 'self-hosting/env#live-activity-remote-updates-optional',
    },
    HAPPIER_LIVE_ACTIVITY_APNS_PRIVATE_KEY: {
        type: 'string',
        sensitivity: 'secret',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'liveActivity',
        description: 'Apple push signing key (PEM). Takes precedence over the key file.',
        docs: 'self-hosting/env#live-activity-remote-updates-optional',
    },
    HAPPIER_LIVE_ACTIVITY_APNS_PRIVATE_KEY_FILE: {
        type: 'string',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'liveActivity',
        description: 'Path of a file holding the Apple push signing key (PEM).',
        docs: 'self-hosting/env#live-activity-remote-updates-optional',
    },
    HAPPIER_LIVE_ACTIVITY_APNS_BUNDLE_IDS: {
        type: 'list',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'liveActivity',
        description: 'iOS bundle ids allowed as direct push topics (comma-separated).',
        docs: 'self-hosting/env#live-activity-remote-updates-optional',
    },
    HAPPIER_LIVE_ACTIVITY_APNS_ACTIVITY_NAMES: {
        type: 'list',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'liveActivity',
        description: 'Live Activity names allowed for direct push delivery (comma-separated).',
        docs: 'self-hosting/env#live-activity-remote-updates-optional',
    },
    HAPPIER_LIVE_ACTIVITY_APNS_REQUEST_TIMEOUT_MS: {
        type: 'int',
        default: 15_000,
        bounds: { min: 1 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'liveActivity',
        description: 'Timeout of one Apple push request, in milliseconds.',
    },
    HAPPIER_LIVE_ACTIVITY_APNS_RECONNECT_BACKOFF_MS: {
        type: 'int',
        default: 1_000,
        bounds: { min: 1 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'liveActivity',
        description: 'Delay before reconnecting to Apple push after a connection failure, in milliseconds.',
    },
    HAPPIER_LIVE_ACTIVITY_HOSTED_RELAY_ALLOWED: {
        type: 'boolean',
        default: false,
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'liveActivity',
        description: 'Allows delivering Live Activity updates through a hosted Happier relay.',
        docs: 'self-hosting/env#live-activity-remote-updates-optional',
    },
    HAPPIER_LIVE_ACTIVITY_HOSTED_RELAY_BASE_URL: {
        type: 'url',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'liveActivity',
        description: 'Address of the hosted Live Activity relay.',
        docs: 'self-hosting/env#live-activity-remote-updates-optional',
    },
    HAPPIER_LIVE_ACTIVITY_HOSTED_RELAY_ACCESS_KEY: {
        type: 'string',
        sensitivity: 'secret',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'liveActivity',
        description: 'Access key this server presents to the hosted Live Activity relay.',
        docs: 'self-hosting/env#live-activity-remote-updates-optional',
    },
    HAPPIER_LIVE_ACTIVITY_HOSTED_RELAY_SERVICE_ENABLED: {
        type: 'boolean',
        default: false,
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'liveActivity',
        description: 'Runs this server as a hosted Live Activity relay for other servers.',
    },
    HAPPIER_LIVE_ACTIVITY_HOSTED_RELAY_ACCESS_KEYS: {
        type: 'list',
        sensitivity: 'secret',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'liveActivity',
        description: 'Access keys other servers may present to this hosted Live Activity relay (comma-separated).',
    },
    HAPPIER_LIVE_ACTIVITY_HOSTED_RELAY_MAX_SKEW_MS: {
        type: 'int',
        default: 300_000,
        bounds: { min: 1 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'liveActivity',
        description: 'Largest clock difference the hosted relay accepts on a signed request, in milliseconds.',
    },
    HAPPIER_LIVE_ACTIVITY_HOSTED_RELAY_DUPLICATE_TTL_MS: {
        type: 'int',
        default: 600_000,
        bounds: { min: 1 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'liveActivity',
        description: 'Milliseconds the hosted relay remembers a request to refuse duplicates.',
    },
    HAPPIER_LIVE_ACTIVITY_HOSTED_RELAY_DUPLICATE_CACHE_MAX_ENTRIES: {
        type: 'int',
        default: 10_000,
        bounds: { min: 1 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'liveActivity',
        description: 'Most requests the hosted relay remembers for duplicate detection.',
    },

    // Voice (ElevenLabs) and billing.
    ELEVENLABS_API_KEY: {
        type: 'string',
        sensitivity: 'secret',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'voice',
        description: 'ElevenLabs API key for hosted voice. Voice is unavailable without it.',
        docs: 'self-hosting/env#voice',
    },
    ELEVENLABS_AGENT_ID: {
        type: 'string',
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'server',
        group: 'voice',
        description: 'ElevenLabs agent id used for voice (outside production, preferred over the production agent).',
        docs: 'self-hosting/env#voice',
    },
    ELEVENLABS_AGENT_ID_PROD: {
        type: 'string',
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'server',
        group: 'voice',
        description: 'ElevenLabs agent id preferred when NODE_ENV is production.',
        docs: 'self-hosting/env#voice',
    },
    ELEVENLABS_API_BASE_URL: {
        type: 'url',
        default: 'https://api.elevenlabs.io',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'voice',
        description: 'Base address of the ElevenLabs API.',
    },
    REVENUECAT_SECRET_KEY: {
        type: 'string',
        sensitivity: 'secret',
        apply: 'live',
        editable: 'home',
        section: 'server',
        group: 'voice',
        description: 'RevenueCat secret key used to check voice subscriptions when a subscription is required.',
    },
    VOICE_FREE_SESSIONS_PER_MONTH: {
        type: 'int',
        default: 0,
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'server',
        group: 'voice',
        description: 'Voice sessions per month allowed without a subscription (negative values count as 0).',
        docs: 'self-hosting/env#voice',
    },
    VOICE_FREE_MINUTES_PER_MONTH: {
        type: 'int',
        default: 0,
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'server',
        group: 'voice',
        description: 'Voice minutes per month allowed without a subscription (negative values count as 0).',
        docs: 'self-hosting/env#voice',
    },
    VOICE_MAX_CONCURRENT_SESSIONS: {
        type: 'int',
        default: 1,
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'server',
        group: 'voice',
        description: 'Voice sessions one account may run at once (at least 1).',
        docs: 'self-hosting/env#voice',
    },
    VOICE_MAX_SESSION_SECONDS: {
        type: 'int',
        default: 1_200,
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'server',
        group: 'voice',
        description: 'Longest voice session, in seconds (at least 30).',
        docs: 'self-hosting/env#voice',
    },
    VOICE_MAX_MINUTES_PER_DAY: {
        type: 'int',
        default: 0,
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'server',
        group: 'voice',
        description: 'Voice minutes one account may use per day; 0 means no daily cap.',
        docs: 'self-hosting/env#voice',
    },
    HAPPIER_VOICE_PROVIDER_IDENTITY_BACKFILL_ENABLED: {
        type: 'boolean',
        default: false,
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'voice',
        description: 'Runs the background backfill of voice provider conversation identities (accepts only true, false, 1 or 0).',
    },
    HAPPIER_VOICE_PROVIDER_IDENTITY_BACKFILL_BATCH_SIZE: {
        type: 'int',
        default: 100,
        bounds: { min: 1, max: 1_000 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'voice',
        description: 'Rows per voice identity backfill batch; other values stop the server.',
    },
    HAPPIER_VOICE_PROVIDER_IDENTITY_BACKFILL_TIME_BUDGET_MS: {
        type: 'int',
        default: 5_000,
        bounds: { min: 1, max: 900_000 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'voice',
        description: 'Time one voice identity backfill run may spend, in milliseconds.',
    },
    HAPPIER_VOICE_PROVIDER_IDENTITY_BACKFILL_BATCH_DELAY_MS: {
        type: 'int',
        default: 100,
        bounds: { min: 0, max: 60_000 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'voice',
        description: 'Pause between voice identity backfill batches, in milliseconds.',
    },
    HAPPIER_VOICE_PROVIDER_IDENTITY_BACKFILL_INTERVAL_MS: {
        type: 'int',
        default: 60_000,
        bounds: { min: 1_000, max: 86_400_000 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'voice',
        description: 'Time between voice identity backfill runs, in milliseconds.',
    },

    // Connected services and vendor tokens.
    HAPPIER_CONNECTED_SERVICES_OPENAI_CODEX_OAUTH_CLIENT_ID: {
        type: 'string',
        default: OPENAI_CODEX_CLIENT_ID,
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'connectedServices',
        description: 'OAuth client id used to refresh OpenAI Codex subscription credentials.',
    },
    HAPPIER_CONNECTED_SERVICES_OPENAI_CODEX_OAUTH_TOKEN_URL: {
        type: 'url',
        default: OPENAI_CODEX_TOKEN_URL,
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'connectedServices',
        description: 'OAuth token endpoint used to refresh OpenAI Codex subscription credentials.',
    },
    HAPPIER_CONNECTED_SERVICES_CLAUDE_SUBSCRIPTION_OAUTH_CLIENT_ID: {
        type: 'string',
        default: CLAUDE_OAUTH_CLIENT_ID,
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'connectedServices',
        description: 'OAuth client id used to refresh Claude subscription credentials.',
    },
    HAPPIER_CONNECTED_SERVICES_CLAUDE_SUBSCRIPTION_OAUTH_TOKEN_URL: {
        type: 'url',
        default: CLAUDE_OAUTH_TOKEN_URL,
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'connectedServices',
        description: 'OAuth token endpoint used to refresh Claude subscription credentials.',
    },
    HAPPIER_CONNECTED_SERVICES_OAUTH_EXCHANGE_TIMEOUT_MS: {
        type: 'int',
        default: 10_000,
        bounds: { min: 1_000, max: 60_000 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'connectedServices',
        description: 'Timeout of a connected-service OAuth token exchange, in milliseconds.',
    },
    CONNECTED_SERVICE_CREDENTIAL_MAX_LEN: {
        type: 'int',
        default: 64_000,
        bounds: { min: 1, max: 2_000_000 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'connectedServices',
        description: 'Largest connected-service credential the server stores, in characters.',
    },
    CONNECTED_SERVICE_REFRESH_LEASE_MAX_MS: {
        type: 'int',
        default: 300_000,
        bounds: { min: 5_000, max: 3_600_000 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'connectedServices',
        description: 'Longest lease a machine may hold while refreshing a connected-service credential, in milliseconds.',
    },
    VENDOR_TOKEN_MAX_LEN: {
        type: 'int',
        default: 4_096,
        bounds: { min: 256, max: 65_536 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'connectedServices',
        description: 'Largest vendor token the server stores, in characters.',
        docs: 'self-hosting/env#account--terminal-auth-ttl-controls',
    },

    // Local service previews.
    HAPPIER_LOCAL_SERVICES_TOKEN_SECRET: {
        type: 'string',
        sensitivity: 'secret',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'localServices',
        description: 'Secret that signs local-service preview tokens. When unset: derived from the master secret.',
    },
    HAPPIER_LOCAL_SERVICES_PREVIEW_TOKEN_SECRET: {
        type: 'string',
        sensitivity: 'secret',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'localServices',
        description: 'Secret that signs private local-service preview tokens, overriding the shared local-services secret.',
    },
    HAPPIER_LOCAL_SERVICES_PUBLIC_PREVIEW_TOKEN_SECRET: {
        type: 'string',
        sensitivity: 'secret',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'localServices',
        description: 'Secret that signs public local-service preview tokens, overriding the shared local-services secret.',
    },

    // Plugins and reviews.
    HAPPIER_PLUGIN_UI_ARTIFACT_BROWSER_ORIGIN: {
        type: 'url',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'plugins',
        description: 'Separate https origin that serves plugin UI artifacts to browsers. Browser plugin UI is off without it.',
    },
    HAPPIER_PLUGIN_INSTALLATION_MANIFEST_PUBLISHER_PROOF_MAX_AGE_MS: {
        type: 'int',
        default: 300_000,
        bounds: { min: 1 },
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'server',
        group: 'plugins',
        description: 'Age after which a plugin publisher proof is refused, in milliseconds.',
    },
    HAPPIER_PLUGIN_INSTALLATION_MANIFEST_PUBLISHER_PROOF_CLOCK_SKEW_MS: {
        type: 'int',
        default: 60_000,
        bounds: { min: 1 },
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'server',
        group: 'plugins',
        description: 'Clock difference tolerated on a plugin publisher proof, in milliseconds.',
    },
    HAPPIER_REVIEW_COMMENT_PRINCIPAL_PROOF_MAX_AGE_MS: {
        type: 'int',
        default: 300_000,
        bounds: { min: 1 },
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'server',
        group: 'reviews',
        description: 'Age after which a review-comment principal proof is refused, in milliseconds.',
    },
    HAPPIER_REVIEW_COMMENT_PRINCIPAL_PROOF_CLOCK_SKEW_MS: {
        type: 'int',
        default: 60_000,
        bounds: { min: 1 },
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'server',
        group: 'reviews',
        description: 'Clock difference tolerated on a review-comment principal proof, in milliseconds.',
    },

    // Bug-report server diagnostics.
    HAPPIER_BUG_REPORTS_SERVER_DIAGNOSTICS_ENABLED: {
        type: 'boolean',
        default: false,
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'server',
        group: 'bugReports',
        description: 'Lets bug reports include a snapshot of recent server logs.',
        docs: 'self-hosting/env#server-diagnostics-snapshot-controls',
    },
    HAPPIER_BUG_REPORTS_SERVER_DIAGNOSTICS_ACCESS_MODE: {
        type: 'enum',
        default: 'owner',
        bounds: { values: ['owner', 'authenticated'] },
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'server',
        group: 'bugReports',
        description: 'Who may read the server diagnostics snapshot: server owners or any signed-in account.',
        docs: 'self-hosting/env#server-diagnostics-snapshot-controls',
    },
    HAPPIER_BUG_REPORTS_SERVER_LOG_PATH: {
        type: 'string',
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'server',
        group: 'bugReports',
        description: 'Server log file the diagnostics snapshot reads. When unset: server.log in the self-host log directory.',
        docs: 'self-hosting/env#server-diagnostics-snapshot-controls',
    },
    HAPPIER_BUG_REPORTS_SERVER_LOG_MAX_BYTES: {
        type: 'int',
        default: 262_144,
        bounds: { min: 4_096, max: 5_242_880 },
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'server',
        group: 'bugReports',
        description: 'Bytes of server log the diagnostics snapshot includes (values outside the range are clamped).',
        docs: 'self-hosting/env#server-diagnostics-snapshot-controls',
    },

    // Release sources.
    HAPPIER_PUBLIC_RELEASE_CHANNEL: {
        type: 'string',
        default: 'stable',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'releases',
        description: 'Release channel this Home follows for published runner artifacts.',
    },
    HAPPIER_GITHUB_REPO: {
        type: 'string',
        default: 'happier-dev/happier',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'releases',
        description: 'GitHub repository (owner/name) runner artifacts are published from.',
    },
});
