import { defineServerConfigRegistry } from '../serverConfigEntry.js';

/**
 * Sign-in, identity-provider and account policy keys.
 *
 * The auth policy keys are the ceiling the Home's governance policy narrows within (plan §3.4);
 * an explicitly set env value is a lock the console shows as fixed.
 */

export const POLICIES_SERVER_CONFIG = defineServerConfigRegistry({
    // Global auth policy (read per request by `resolveAuthPolicyFromEnv`).
    AUTH_ANONYMOUS_SIGNUP_ENABLED: {
        type: 'boolean',
        default: true,
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'policies',
        group: 'signup',
        description: 'Allows creating an account without a sign-in provider (key-based signup).',
        docs: 'self-hosting/env#global-auth-policy',
    },
    AUTH_SIGNUP_PROVIDERS: {
        type: 'list',
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'policies',
        group: 'signup',
        description: 'Sign-in providers that may create new accounts (comma- or space-separated provider ids).',
        docs: 'self-hosting/env#global-auth-policy',
    },
    AUTH_REQUIRED_LOGIN_PROVIDERS: {
        type: 'list',
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'policies',
        group: 'signup',
        description: 'Sign-in providers every account must have linked to sign in (comma- or space-separated provider ids).',
        docs: 'self-hosting/env#global-auth-policy',
    },
    AUTH_OFFBOARDING_ENABLED: {
        type: 'boolean',
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'policies',
        group: 'offboarding',
        description: 'Re-checks provider allowlist eligibility of signed-in accounts. When unset: on whenever a GitHub organization or OIDC allowlist is configured.',
        docs: 'self-hosting/env#global-auth-policy',
    },
    AUTH_OFFBOARDING_STRICT: {
        type: 'boolean',
        default: false,
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'policies',
        group: 'offboarding',
        description: 'Refuses requests when an eligibility re-check cannot reach the provider, instead of allowing them.',
        docs: 'self-hosting/env#global-auth-policy',
    },
    AUTH_OFFBOARDING_INTERVAL_SECONDS: {
        type: 'int',
        default: 86_400,
        bounds: { min: 60, max: 86_400 },
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'policies',
        group: 'offboarding',
        description: 'Seconds between eligibility re-checks of a signed-in account.',
        docs: 'self-hosting/env#global-auth-policy',
    },
    AUTH_PROVIDERS_CONFIG_PATH: {
        type: 'string',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'policies',
        group: 'oidc',
        description: 'Path of a JSON file declaring OIDC sign-in providers; takes precedence over AUTH_PROVIDERS_CONFIG_JSON.',
        docs: 'self-hosting/env#global-auth-policy',
    },
    AUTH_PROVIDERS_CONFIG_JSON: {
        type: 'json',
        sensitivity: 'secret',
        apply: 'restart',
        editable: 'home',
        section: 'policies',
        group: 'oidc',
        description: 'Inline JSON array declaring OIDC sign-in providers, including their client secrets.',
        docs: 'self-hosting/env#global-auth-policy',
    },
    HAPPIER_AUTH_REQUIRE_KEY_CHALLENGE_V2: {
        type: 'boolean',
        default: false,
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'policies',
        group: 'signup',
        description: 'Requires the version 2 key-challenge sign-in for ordinary Homes.',
        docs: 'self-hosting/env#built-in-key-challenge-login-route',
    },
    HAPPIER_AUTH_SIGN_IN_SERVICE_MODE: {
        type: 'enum',
        default: 'disabled',
        bounds: { values: ['disabled', 'self', 'external'] },
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'policies',
        group: 'accountService',
        description: 'Account sign-in service: none, this server, or an external Account Service.',
        docs: 'self-hosting/env#global-auth-policy',
    },
    HAPPIER_AUTH_SIGN_IN_SERVICE_URL: {
        type: 'url',
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'policies',
        group: 'accountService',
        description: 'Address of the external Account Service; required when the sign-in service mode is external.',
        docs: 'self-hosting/env#global-auth-policy',
    },
    HAPPIER_AUTH_SIGN_IN_SERVICE_SERVER_IDENTITY_ID: {
        type: 'string',
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'policies',
        group: 'accountService',
        description: 'Server identity the external Account Service must present (optional pin).',
        docs: 'self-hosting/env#global-auth-policy',
    },
    HAPPIER_ACCOUNT_SERVICE_DISPLAY_NAME: {
        type: 'string',
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'policies',
        group: 'accountService',
        description: 'Display name of the Account Service shown on sign-in screens.',
        docs: 'self-hosting/env#global-auth-policy',
    },
    HAPPIER_AUTH_PUBLIC_PROVISION_DENY_METHODS: {
        type: 'list',
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'policies',
        group: 'signup',
        description: 'Sign-in methods that may not create accounts from the public internet (comma- or space-separated). Empty turns the rule off.',
    },
    HAPPIER_AUTH_PUBLIC_PROVISION_DENY_MODES: {
        type: 'list',
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'policies',
        group: 'signup',
        description: 'Account modes the public-provisioning rule applies to: keyed, keyless or *. When unset: both.',
    },
    HAPPIER_AUTH_PUBLIC_PROVISION_DENY_IP_CLASSES: {
        type: 'list',
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'policies',
        group: 'signup',
        description: 'Client address classes the public-provisioning rule applies to: public, private, unknown or *. When unset: public and unknown.',
    },
    HAPPIER_SERVER_OWNER_USER_IDS: {
        type: 'list',
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'policies',
        group: 'diagnostics',
        description: 'Account ids treated as server owners for owner-only server diagnostics (comma-separated).',
        docs: 'self-hosting/env#server-diagnostics-snapshot-controls',
    },
    HAPPIER_HOME_DEVICE_APPROVAL_REQUIRED: {
        type: 'enum',
        default: '0',
        bounds: { values: ['0', '1'] },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'policies',
        group: 'devices',
        description: 'Set to 1 to require an existing device to approve each new device sign-in (Personal Home). Read through the shared Personal Home configuration.',
    },

    // Built-in GitHub sign-in (OAuth app) and its restrictions.
    GITHUB_CLIENT_ID: {
        type: 'string',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'policies',
        group: 'github',
        description: 'Client id of the GitHub OAuth app used for GitHub sign-in. GitHub sign-in is unavailable until it and the secret are set.',
        docs: 'self-hosting/env#github-oauth',
    },
    GITHUB_CLIENT_SECRET: {
        type: 'string',
        sensitivity: 'secret',
        apply: 'restart',
        editable: 'home',
        section: 'policies',
        group: 'github',
        description: 'Client secret of the GitHub OAuth app.',
        docs: 'self-hosting/env#github-oauth',
    },
    GITHUB_REDIRECT_URL: {
        type: 'url',
        aliases: ['GITHUB_REDIRECT_URI'],
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'policies',
        group: 'github',
        description: 'OAuth callback address registered on the GitHub OAuth app.',
        docs: 'self-hosting/env#github-oauth',
    },
    GITHUB_HTTP_TIMEOUT_SECONDS: {
        type: 'int',
        default: 10,
        bounds: { min: 1, max: 120 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'policies',
        group: 'github',
        description: 'Timeout of requests to the GitHub API, in seconds.',
        docs: 'self-hosting/env#github-oauth',
    },
    GITHUB_STORE_ACCESS_TOKEN: {
        type: 'boolean',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'policies',
        group: 'github',
        description: 'Keeps the GitHub access token after sign-in. When unset: kept only when organization membership is checked with the user token.',
        docs: 'self-hosting/env#github-oauth',
    },
    OAUTH_PENDING_TTL_SECONDS: {
        type: 'int',
        default: 600,
        bounds: { min: 60, max: 3_600 },
        aliases: ['GITHUB_OAUTH_PENDING_TTL_SECONDS'],
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'policies',
        group: 'oauth',
        description: 'Seconds a pending OAuth sign-in stays valid (values outside the range are clamped).',
        docs: 'self-hosting/env#github-oauth',
    },
    OAUTH_STATE_TTL_SECONDS: {
        type: 'int',
        default: 600,
        bounds: { min: 60, max: 3_600 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'policies',
        group: 'oauth',
        description: 'Seconds an OAuth state token stays valid (values outside the range are clamped).',
        docs: 'self-hosting/env#github-oauth',
    },
    HAPPIER_OAUTH_RETURN_ALLOWED_SCHEMES: {
        type: 'list',
        aliases: ['HAPPY_OAUTH_RETURN_ALLOWED_SCHEMES'],
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'policies',
        group: 'oauth',
        description: 'Extra app URL schemes an OAuth flow may return to (comma- or space-separated).',
        docs: 'self-hosting/env#github-oauth',
    },
    AUTH_GITHUB_ALLOWED_USERS: {
        type: 'list',
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'policies',
        group: 'github',
        description: 'GitHub users allowed to sign in with GitHub (comma- or space-separated). Empty allows everyone the other rules allow.',
        docs: 'self-hosting/env#github-eligibility-restrictions',
    },
    AUTH_GITHUB_ALLOWED_ORGS: {
        type: 'list',
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'policies',
        group: 'github',
        description: 'GitHub organizations whose members may sign in with GitHub (comma- or space-separated).',
        docs: 'self-hosting/env#github-eligibility-restrictions',
    },
    AUTH_GITHUB_ORG_MATCH: {
        type: 'enum',
        default: 'any',
        bounds: { values: ['any', 'all'] },
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'policies',
        group: 'github',
        description: 'Whether membership in any or all of the allowed organizations is required.',
        docs: 'self-hosting/env#github-eligibility-restrictions',
    },
    AUTH_GITHUB_ORG_MEMBERSHIP_SOURCE: {
        type: 'enum',
        bounds: { values: ['github_app', 'oauth_user_token'] },
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'policies',
        group: 'github',
        description: 'How organization membership is checked. When unset: the GitHub App when organizations are allowlisted, otherwise the user token.',
        docs: 'self-hosting/env#github-eligibility-restrictions',
    },
    AUTH_GITHUB_APP_ID: {
        type: 'string',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'policies',
        group: 'github',
        description: 'Id of the deployment GitHub App used to check organization membership.',
        docs: 'self-hosting/env#github-eligibility-restrictions',
    },
    AUTH_GITHUB_APP_PRIVATE_KEY: {
        type: 'string',
        sensitivity: 'secret',
        apply: 'restart',
        editable: 'home',
        section: 'policies',
        group: 'github',
        description: 'Private key (PEM) of the deployment GitHub App.',
        docs: 'self-hosting/env#github-eligibility-restrictions',
    },
    AUTH_GITHUB_APP_INSTALLATION_ID_BY_ORG: {
        type: 'string',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'policies',
        group: 'github',
        description: 'Installation id of the deployment GitHub App per organization, as org=id pairs separated by commas or spaces.',
        docs: 'self-hosting/env#github-eligibility-restrictions',
    },

    // WorkOS (Team-level SSO and directory sync).
    WORKOS_API_KEY: {
        type: 'string',
        sensitivity: 'secret',
        apply: 'restart',
        editable: 'home',
        section: 'policies',
        group: 'workos',
        description: 'WorkOS API key that enables Team single sign-on and directory sync.',
    },
    WORKOS_CLIENT_ID: {
        type: 'string',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'policies',
        group: 'workos',
        description: 'WorkOS client id paired with the API key.',
    },

    // Sign-in request lifetimes and caches.
    ACCOUNT_AUTH_REQUEST_TTL_SECONDS: {
        type: 'int',
        default: 900,
        bounds: { min: 60, max: 3_600 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'policies',
        group: 'signInRequests',
        description: 'Seconds an account sign-in request waits for approval (values outside the range are clamped).',
        docs: 'self-hosting/env#account--terminal-auth-ttl-controls',
    },
    TERMINAL_AUTH_REQUEST_TTL_SECONDS: {
        type: 'int',
        default: 900,
        bounds: { min: 60, max: 3_600 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'policies',
        group: 'signInRequests',
        description: 'Seconds a terminal sign-in request waits for approval (values outside the range are clamped).',
        docs: 'self-hosting/env#account--terminal-auth-ttl-controls',
    },
    AUTH_PAIRING_TTL_SECONDS: {
        type: 'int',
        default: 120,
        bounds: { min: 30, max: 600 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'policies',
        group: 'signInRequests',
        description: 'Seconds a device pairing code stays valid (values outside the range are clamped).',
    },
    AUTH_TOKEN_CACHE_TTL_SECONDS: {
        type: 'int',
        default: 600,
        bounds: { min: 1, max: 86_400 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'authCaches',
        description: 'Seconds a verified session token stays in the in-memory cache (values outside the range are clamped).',
    },
    AUTH_TOKEN_CACHE_MAX_ENTRIES: {
        type: 'int',
        default: 4_096,
        bounds: { min: 0, max: 200_000 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'authCaches',
        description: 'Most verified session tokens kept in the in-memory cache; 0 turns the cache off.',
    },
    AUTH_LOGIN_ELIGIBILITY_CACHE_TTL_MS: {
        type: 'int',
        default: 1_000,
        bounds: { min: 0, max: 60_000 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'authCaches',
        description: 'Milliseconds a positive sign-in eligibility result stays cached (values above the range are clamped).',
    },
    AUTH_LOGIN_ELIGIBILITY_CACHE_MAX_ENTRIES: {
        type: 'int',
        default: 20_000,
        bounds: { min: 0, max: 200_000 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'authCaches',
        description: 'Most sign-in eligibility results kept in the cache; 0 turns the cache off.',
    },

    // Friends usernames.
    FRIENDS_USERNAME_MIN_LEN: {
        type: 'int',
        default: 3,
        bounds: { min: 1, max: 128 },
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'policies',
        group: 'friends',
        description: 'Shortest username allowed for friend search.',
        docs: 'self-hosting/env#friends--social',
    },
    FRIENDS_USERNAME_MAX_LEN: {
        type: 'int',
        default: 32,
        bounds: { min: 1, max: 128 },
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'policies',
        group: 'friends',
        description: 'Longest username allowed for friend search.',
        docs: 'self-hosting/env#friends--social',
    },
    FRIENDS_USERNAME_REGEX: {
        type: 'string',
        default: '^[a-z0-9_-]+$',
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'policies',
        group: 'friends',
        description: 'Regular expression a username must match; an invalid expression falls back to the default.',
        docs: 'self-hosting/env#friends--social',
    },
});
