import { defineServerConfigRegistry } from '../serverConfigEntry.js';
import { ACCOUNT_DIRECTORY_MAX_LABEL_UTF8_BYTES } from '../../auth/accountDirectory.js';

/**
 * Public, canonical and web-app addresses and how they are inferred (plan §3.2).
 *
 * The canonical server URL is the authentication audience; changing the public or web-app address
 * never changes it (invariant I1). The Iroh relay keys are read by the Iroh endpoint through the shared relay
 * configuration (`packages/iroh-native`), at endpoint start.
 */

export const REACH_SERVER_CONFIG = defineServerConfigRegistry({
    HAPPIER_HOME_DISPLAY_NAME: {
        type: 'string',
        bounds: { maxUtf8Bytes: ACCOUNT_DIRECTORY_MAX_LABEL_UTF8_BYTES, noControlChars: true },
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'reach',
        group: 'identity',
        description: 'Name of this Home shown to its connected devices. When unset, devices keep their existing local label.',
    },
    HAPPIER_PUBLIC_SERVER_URL: {
        type: 'url',
        bounds: { scheme: 'https' },
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'reach',
        group: 'addresses',
        description: 'Address other devices and links use to reach this Home. When unset: inferred from relay access or Tailscale.',
        docs: 'self-hosting/env#getting-started-required-vs-recommended',
    },
    HAPPIER_WEBAPP_URL: {
        type: 'url',
        aliases: ['HAPPY_WEBAPP_URL'],
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'reach',
        group: 'addresses',
        description: 'Address of the web app that links open. When unset: the bundled UI at the public address, else the Happier web app.',
        docs: 'self-hosting/env#getting-started-required-vs-recommended',
    },
    HAPPIER_CANONICAL_SERVER_URL: {
        type: 'url',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'bootstrap',
        section: 'reach',
        group: 'addresses',
        description: 'Stable identity address of this server used as the sign-in audience; changing it signs every device out. When unset: an explicitly set public address.',
        docs: 'self-hosting/env#getting-started-required-vs-recommended',
        readOnlyReason: 'invariant',
        reason: 'The sign-in audience of every credential; the console never changes it.',
    },
    HAPPIER_WEBAPP_OAUTH_RETURN_URL_BASE: {
        type: 'url',
        aliases: ['HAPPY_WEBAPP_OAUTH_RETURN_URL_BASE'],
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'reach',
        group: 'addresses',
        description: 'Base address OAuth flows return to in the web app; the provider id is appended.',
        docs: 'self-hosting/env#github-oauth',
    },
    PUBLIC_URL: {
        type: 'url',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'bootstrap',
        section: 'server',
        group: 'addresses',
        description: 'Light flavour only: the address the server announces for itself. When unset: derived from the host and port.',
        docs: 'self-hosting/env#light-flavor-paths',
        readOnlyReason: 'before_database',
        reason: 'Read before the database opens. The public address you can change is under Reach.',
    },
    HAPPIER_PUBLIC_SERVER_URL_INFER_TTL_MS: {
        type: 'int',
        default: 60_000,
        bounds: { min: 1_000, max: 3_600_000 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'reach',
        group: 'inference',
        description: 'Milliseconds an inferred public address is cached before it is probed again.',
    },
    HAPPIER_RELAY_ACCESS_INFER_PUBLIC_URL: {
        type: 'boolean',
        default: true,
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'reach',
        group: 'inference',
        description: 'Infers the public address from the relay-access method configured on the hosting computer.',
    },
    HAPPIER_TAILSCALE_INFER_PUBLIC_URL: {
        type: 'boolean',
        default: true,
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'reach',
        group: 'inference',
        description: 'Infers the public address from Tailscale Serve or Funnel on the hosting computer.',
        docs: 'self-hosting/env#tailscale-serve-inference-optional',
    },
    HAPPIER_TAILSCALE_SERVE_STATUS_TIMEOUT_MS: {
        type: 'int',
        default: 750,
        bounds: { min: 1, max: 10_000 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'reach',
        group: 'inference',
        description: 'Milliseconds to wait for `tailscale serve status` while inferring the public address.',
        docs: 'self-hosting/env#tailscale-serve-inference-optional',
    },
    HAPPIER_TAILSCALE_FUNNEL_STATUS_TIMEOUT_MS: {
        type: 'int',
        default: 750,
        bounds: { min: 1, max: 10_000 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'reach',
        group: 'inference',
        description: 'Milliseconds to wait for `tailscale funnel status` while inferring the public address.',
        docs: 'self-hosting/env#tailscale-serve-inference-optional',
    },
    HAPPIER_HOME_IROH_MODE: {
        type: 'enum',
        default: 'enabled',
        bounds: { values: ['enabled', 'disabled'] },
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'reach',
        group: 'iroh',
        description: 'Whether devices may connect to this Personal Home directly (Iroh). Turning it off retires the current direct-connection identity; turning it on creates a new one. Changed from Reach, which applies it at once.',
        docs: 'self-hosting/env#iroh-connectivity-optional',
    },
    HAPPIER_IROH_RELAY_POLICY: {
        type: 'enum',
        default: 'automatic',
        bounds: { values: ['automatic', 'disabled'] },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'reach',
        group: 'iroh',
        description: 'Whether direct (Iroh) connections may use relay servers when a direct path fails.',
        docs: 'self-hosting/env#iroh-connectivity-optional',
    },
    HAPPIER_IROH_RELAY_URLS: {
        type: 'list',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'reach',
        group: 'iroh',
        description: 'Comma-separated Iroh relay server addresses to use instead of the built-in relays.',
        docs: 'self-hosting/env#iroh-connectivity-optional',
    },
});
