// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
export type PluginPermissionGrantsActionInputById = {
    readonly "plugins.permissions.grants.list": {
        pluginId?: string | undefined;
        grantId?: string | undefined;
        capability?: 'reviews.comments.write.direct' | 'credentials.materialize.raw' | undefined;
        targetScope?: {
            kind: 'account';
        } | {
            kind: 'project';
            projectId: string;
        } | {
            kind: 'workspace';
            workspaceId: string;
        } | undefined;
        subject?: {
            kind: 'general';
        } | {
            kind: 'credential_access_disclosure';
            contribution: {
                pluginId: string;
                localId: string;
            };
            credentialSlotId: string;
            purpose: string;
            accessDeclarationDigest: string;
            selectedAuthorityDigest: string;
            selectedRawAccessDigest: string;
        } | undefined;
        caller?: {
            machineId: string;
            materializationId: string;
            pluginId: string;
        } | undefined;
        includeRevoked?: boolean | undefined;
        includeResolvedRequests?: boolean | undefined;
        limit?: number | undefined;
    };
    readonly "plugins.permissions.grants.request": {
        pluginId: string;
        capability: 'reviews.comments.write.direct' | 'credentials.materialize.raw';
        targetScope: {
            kind: 'account';
        } | {
            kind: 'project';
            projectId: string;
        } | {
            kind: 'workspace';
            workspaceId: string;
        };
        subject: {
            kind: 'general';
        } | {
            kind: 'credential_access_disclosure';
            contribution: {
                pluginId: string;
                localId: string;
            };
            credentialSlotId: string;
            purpose: string;
            accessDeclarationDigest: string;
            selectedAuthorityDigest: string;
            selectedRawAccessDigest: string;
        };
        requester: {
            kind: 'user';
            userId: string;
        } | {
            kind: 'plugin';
            pluginId: string;
            sessionId?: string | undefined;
            requestId?: string | undefined;
        } | {
            kind: 'host';
            label?: string | undefined;
        };
        reason: string;
        caller?: {
            machineId: string;
            materializationId: string;
            pluginId: string;
        } | undefined;
    };
    readonly "plugins.permissions.grants.grant": {
        requestId: string;
        reason?: string | undefined;
    };
    readonly "plugins.permissions.grants.revoke": {
        grantId: string;
        reason?: string | undefined;
        caller?: {
            machineId: string;
            materializationId: string;
            pluginId: string;
        } | undefined;
    };
    readonly "plugins.permissions.grants.dismissRequest": {
        requestId: string;
        reason?: string | undefined;
    };
};

export type PluginPermissionGrantsActionResultById = {
    readonly "plugins.permissions.grants.list": {
        grants: {
            v: 1;
            id: string;
            accountId: string;
            pluginId: string;
            capability: 'reviews.comments.write.direct' | 'credentials.materialize.raw';
            targetScope: {
                kind: 'account';
            } | {
                kind: 'project';
                projectId: string;
            } | {
                kind: 'workspace';
                workspaceId: string;
            };
            subject: {
                kind: 'general';
            } | {
                kind: 'credential_access_disclosure';
                contribution: {
                    pluginId: string;
                    localId: string;
                };
                credentialSlotId: string;
                purpose: string;
                accessDeclarationDigest: string;
                selectedAuthorityDigest: string;
                selectedRawAccessDigest: string;
            };
            authoritySource: {
                kind: 'bundled';
            } | {
                kind: 'machine_installation';
                machineId: string;
                installationId: string;
            };
            status: 'active' | 'revoked';
            grantedByUserId: string;
            grantedAt: number;
            createdAt: number;
            updatedAt: number;
            requestId?: string | undefined;
            revokedByUserId?: string | undefined;
            revokedAt?: number | undefined;
        }[];
        pendingRequests: {
            v: 1;
            id: string;
            accountId: string;
            pluginId: string;
            capability: 'reviews.comments.write.direct' | 'credentials.materialize.raw';
            targetScope: {
                kind: 'account';
            } | {
                kind: 'project';
                projectId: string;
            } | {
                kind: 'workspace';
                workspaceId: string;
            };
            subject: {
                kind: 'general';
            } | {
                kind: 'credential_access_disclosure';
                contribution: {
                    pluginId: string;
                    localId: string;
                };
                credentialSlotId: string;
                purpose: string;
                accessDeclarationDigest: string;
                selectedAuthorityDigest: string;
                selectedRawAccessDigest: string;
            };
            authoritySource: {
                kind: 'bundled';
            } | {
                kind: 'machine_installation';
                machineId: string;
                installationId: string;
            };
            requester: {
                kind: 'user';
                userId: string;
            } | {
                kind: 'plugin';
                pluginId: string;
                sessionId?: string | undefined;
                requestId?: string | undefined;
            } | {
                kind: 'host';
                label?: string | undefined;
            };
            reason: string;
            status: 'pending' | 'granted' | 'dismissed';
            createdAt: number;
            updatedAt: number;
            grantId?: string | undefined;
            createdByUserId?: string | undefined;
            decidedByUserId?: string | undefined;
            decidedAt?: number | undefined;
        }[];
    };
    readonly "plugins.permissions.grants.request": {
        pendingRequest: {
            v: 1;
            id: string;
            accountId: string;
            pluginId: string;
            capability: 'reviews.comments.write.direct' | 'credentials.materialize.raw';
            targetScope: {
                kind: 'account';
            } | {
                kind: 'project';
                projectId: string;
            } | {
                kind: 'workspace';
                workspaceId: string;
            };
            subject: {
                kind: 'general';
            } | {
                kind: 'credential_access_disclosure';
                contribution: {
                    pluginId: string;
                    localId: string;
                };
                credentialSlotId: string;
                purpose: string;
                accessDeclarationDigest: string;
                selectedAuthorityDigest: string;
                selectedRawAccessDigest: string;
            };
            authoritySource: {
                kind: 'bundled';
            } | {
                kind: 'machine_installation';
                machineId: string;
                installationId: string;
            };
            requester: {
                kind: 'user';
                userId: string;
            } | {
                kind: 'plugin';
                pluginId: string;
                sessionId?: string | undefined;
                requestId?: string | undefined;
            } | {
                kind: 'host';
                label?: string | undefined;
            };
            reason: string;
            status: 'pending' | 'granted' | 'dismissed';
            createdAt: number;
            updatedAt: number;
            grantId?: string | undefined;
            createdByUserId?: string | undefined;
            decidedByUserId?: string | undefined;
            decidedAt?: number | undefined;
        };
    };
    readonly "plugins.permissions.grants.grant": {
        grant: {
            v: 1;
            id: string;
            accountId: string;
            pluginId: string;
            capability: 'reviews.comments.write.direct' | 'credentials.materialize.raw';
            targetScope: {
                kind: 'account';
            } | {
                kind: 'project';
                projectId: string;
            } | {
                kind: 'workspace';
                workspaceId: string;
            };
            subject: {
                kind: 'general';
            } | {
                kind: 'credential_access_disclosure';
                contribution: {
                    pluginId: string;
                    localId: string;
                };
                credentialSlotId: string;
                purpose: string;
                accessDeclarationDigest: string;
                selectedAuthorityDigest: string;
                selectedRawAccessDigest: string;
            };
            authoritySource: {
                kind: 'bundled';
            } | {
                kind: 'machine_installation';
                machineId: string;
                installationId: string;
            };
            status: 'active' | 'revoked';
            grantedByUserId: string;
            grantedAt: number;
            createdAt: number;
            updatedAt: number;
            requestId?: string | undefined;
            revokedByUserId?: string | undefined;
            revokedAt?: number | undefined;
        };
        pendingRequest: {
            v: 1;
            id: string;
            accountId: string;
            pluginId: string;
            capability: 'reviews.comments.write.direct' | 'credentials.materialize.raw';
            targetScope: {
                kind: 'account';
            } | {
                kind: 'project';
                projectId: string;
            } | {
                kind: 'workspace';
                workspaceId: string;
            };
            subject: {
                kind: 'general';
            } | {
                kind: 'credential_access_disclosure';
                contribution: {
                    pluginId: string;
                    localId: string;
                };
                credentialSlotId: string;
                purpose: string;
                accessDeclarationDigest: string;
                selectedAuthorityDigest: string;
                selectedRawAccessDigest: string;
            };
            authoritySource: {
                kind: 'bundled';
            } | {
                kind: 'machine_installation';
                machineId: string;
                installationId: string;
            };
            requester: {
                kind: 'user';
                userId: string;
            } | {
                kind: 'plugin';
                pluginId: string;
                sessionId?: string | undefined;
                requestId?: string | undefined;
            } | {
                kind: 'host';
                label?: string | undefined;
            };
            reason: string;
            status: 'pending' | 'granted' | 'dismissed';
            createdAt: number;
            updatedAt: number;
            grantId?: string | undefined;
            createdByUserId?: string | undefined;
            decidedByUserId?: string | undefined;
            decidedAt?: number | undefined;
        };
    };
    readonly "plugins.permissions.grants.revoke": {
        grant: {
            v: 1;
            id: string;
            accountId: string;
            pluginId: string;
            capability: 'reviews.comments.write.direct' | 'credentials.materialize.raw';
            targetScope: {
                kind: 'account';
            } | {
                kind: 'project';
                projectId: string;
            } | {
                kind: 'workspace';
                workspaceId: string;
            };
            subject: {
                kind: 'general';
            } | {
                kind: 'credential_access_disclosure';
                contribution: {
                    pluginId: string;
                    localId: string;
                };
                credentialSlotId: string;
                purpose: string;
                accessDeclarationDigest: string;
                selectedAuthorityDigest: string;
                selectedRawAccessDigest: string;
            };
            authoritySource: {
                kind: 'bundled';
            } | {
                kind: 'machine_installation';
                machineId: string;
                installationId: string;
            };
            status: 'active' | 'revoked';
            grantedByUserId: string;
            grantedAt: number;
            createdAt: number;
            updatedAt: number;
            requestId?: string | undefined;
            revokedByUserId?: string | undefined;
            revokedAt?: number | undefined;
        };
    };
    readonly "plugins.permissions.grants.dismissRequest": {
        pendingRequest: {
            v: 1;
            id: string;
            accountId: string;
            pluginId: string;
            capability: 'reviews.comments.write.direct' | 'credentials.materialize.raw';
            targetScope: {
                kind: 'account';
            } | {
                kind: 'project';
                projectId: string;
            } | {
                kind: 'workspace';
                workspaceId: string;
            };
            subject: {
                kind: 'general';
            } | {
                kind: 'credential_access_disclosure';
                contribution: {
                    pluginId: string;
                    localId: string;
                };
                credentialSlotId: string;
                purpose: string;
                accessDeclarationDigest: string;
                selectedAuthorityDigest: string;
                selectedRawAccessDigest: string;
            };
            authoritySource: {
                kind: 'bundled';
            } | {
                kind: 'machine_installation';
                machineId: string;
                installationId: string;
            };
            requester: {
                kind: 'user';
                userId: string;
            } | {
                kind: 'plugin';
                pluginId: string;
                sessionId?: string | undefined;
                requestId?: string | undefined;
            } | {
                kind: 'host';
                label?: string | undefined;
            };
            reason: string;
            status: 'pending' | 'granted' | 'dismissed';
            createdAt: number;
            updatedAt: number;
            grantId?: string | undefined;
            createdByUserId?: string | undefined;
            decidedByUserId?: string | undefined;
            decidedAt?: number | undefined;
        };
    };
};
