// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
export type AccountSessionsActionInputById = {
    readonly "account.sessions.signOutEverywhere": Record<string, never>;
};

export type AccountSessionsActionResultById = {
    readonly "account.sessions.signOutEverywhere": {
        status: 'signed_out';
    };
};
