// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
import type { JsonValue, PluginJsonValueV2 } from '../actions/pluginActionDtoSupport.js';
export type AutomationEventsActionInputById = {
    readonly "automation.event.sources.list": {
        transport: {
            kind: 'checkpointedPull';
        } | {
            kind: 'socket';
        } | {
            kind: 'durablePush';
        };
        pageSize?: number | undefined;
        cursor?: string | undefined;
        knownRevision?: string | undefined;
        checkpointRetirementCandidates?: {
            automationId: string;
            triggerId: string;
            triggerRevision: number;
            eventRef: {
                pluginId: string;
                localId: string;
            };
            sourceSelectorId: string;
            sourceContractVersion: number;
        }[] | undefined;
    };
    readonly "automation.event.admit": {
        definitions: {
            automationId: string;
            triggerId: string;
            triggerRevision: number;
            sourceSelectorId: string;
        }[];
        eventRef: {
            pluginId: string;
            localId: string;
        };
        occurrenceId: string;
        occurredAt: number;
        observationReceivedAt: number;
        payload: JsonValue;
    };
    readonly "automation.event.source.status.report": {
        kind: 'source';
        automationId: string;
        triggerId: string;
        triggerRevision: number;
        eventRef: {
            pluginId: string;
            localId: string;
        };
        sourceSelectorId: string;
        state: 'uninitialized' | 'baselined' | 'observing' | 'backingOff' | 'attention';
        code: 'none' | 'credentialMissing' | 'credentialRevoked' | 'rateLimited' | 'historyGap' | 'capacityBlocked' | 'definitionStale' | 'sourceContractIncompatible' | 'admissionUnavailable';
        nextRetryAt: number | null;
        observedDelta: number;
        admittedDelta: number;
        skippedDelta: number;
        lastObservedAt?: number | null | undefined;
        lastDispositionAt?: number | null | undefined;
    } | {
        kind: 'catalogReconciliation';
        scope: {
            kind: 'checkpointedPull';
        } | {
            kind: 'socket';
        } | {
            kind: 'durablePush';
            webhookEndpointId: string;
        };
        observedRevision: string;
        adoptedRevision: string | null;
        state: 'current' | 'reconciling' | 'reconciliationLate';
        scanStartedAt: number | null;
        nextRetryAt: number | null;
    };
};

export type AutomationEventsActionResultById = {
    readonly "automation.event.sources.list": {
        kind: 'page';
        revision: string;
        definitions: {
            automationId: string;
            triggerId: string;
            triggerRevision: number;
            eventRef: {
                pluginId: string;
                localId: string;
            };
            sourceInstanceId: string;
            sourceSelectorId: string;
            sourceContractVersion: number;
            sourceConfig: PluginJsonValueV2;
            observationTransport: {
                kind: 'checkpointedPull';
                watcherMaterializationRef: {
                    machineId: string;
                    materializationId: string;
                    pluginId: string;
                };
            } | {
                kind: 'socket';
                watcherMaterializationRef: {
                    machineId: string;
                    materializationId: string;
                    pluginId: string;
                };
            } | {
                kind: 'durablePush';
                webhookEndpointId: string;
                endpointMaterializationRef: {
                    machineId: string;
                    materializationId: string;
                    pluginId: string;
                };
                observationStartsAt: number;
            };
            filter: {
                v: 1;
                all: ({
                    op: 'eq';
                    field: string;
                    value: string | number | boolean | null;
                } | {
                    op: 'in';
                    field: string;
                    values: (string | number | boolean | null)[];
                })[];
            } | null;
            maximumObservationAgeMs: number | null;
        }[];
        nextCursor: string | null;
    } | {
        kind: 'unchanged';
        revision: string;
        checkpointRetirements?: {
            automationId: string;
            triggerId: string;
            triggerRevision: number;
            eventRef: {
                pluginId: string;
                localId: string;
            };
            sourceSelectorId: string;
            sourceContractVersion: number;
        }[] | undefined;
    } | {
        kind: 'cursorStale';
        currentRevision: string;
    };
    readonly "automation.event.admit": {
        results: ({
            kind: 'admitted';
            runId: string;
            checkpointSafe: true;
        } | {
            kind: 'rejoined';
            runId: string;
            checkpointSafe: true;
        } | {
            kind: 'skipped';
            reason: 'filtered' | 'beforeObservationStart' | 'outsideFreshness' | 'definitionRetired' | 'occurrenceRejected';
            checkpointSafe: true;
        } | {
            kind: 'refreshDefinition';
            reason: 'definitionStale' | 'observationTargetChanged';
            checkpointSafe: false;
        } | {
            kind: 'blocked';
            reason: 'capacity' | 'temporarilyUnavailable' | 'occurrenceConflict' | 'noEnabledAssignment';
            checkpointSafe: false;
        })[];
    };
    readonly "automation.event.source.status.report": Record<string, never>;
};
