// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
export type MachineAgentInstallActionInputById = {
    readonly "machines.agents.install": {
        agentId: string;
        intent: 'install' | 'update';
        machineId: string;
        force?: boolean | undefined;
        consent?: {
            vendorRecipe: boolean;
        } | undefined;
    };
    readonly "machines.agents.install.status": {
        jobId: string;
        machineId: string;
        cursor?: number | undefined;
    };
    readonly "machines.agents.install.cancel": {
        jobId: string;
        machineId: string;
    };
};

export type MachineAgentInstallActionResultById = {
    readonly "machines.agents.install": {
        ok: true;
        jobId: string;
    } | {
        ok: false;
        errorCode: 'invalid_request' | 'job_not_found' | 'install_unavailable';
        error: string;
    };
    readonly "machines.agents.install.status": {
        ok: false;
        errorCode: 'invalid_request' | 'job_not_found' | 'install_unavailable';
        error: string;
    } | {
        ok: true;
        events: ({
            stepId: string;
            label: string;
            state: 'running' | 'done' | 'failed';
            t: 'step';
        } | {
            stepId: string;
            bytesDone: number;
            bytesTotal: number | null;
            t: 'progress';
        } | {
            t: 'log';
            line: string;
        })[];
        steps: {
            stepId: string;
            label: string;
            state: 'running' | 'done' | 'failed';
        }[];
        progress: {
            stepId: string;
            bytesDone: number;
            bytesTotal: number | null;
        }[];
        nextCursor: number;
        done: boolean;
        outcome: {
            kind: 'succeeded';
            version: string | null;
        } | {
            kind: 'failed';
            code: 'consent_required' | 'unsupported_platform' | 'install_not_available' | 'download_failed' | 'verification_failed' | 'timeout' | 'cancelled' | 'install_failed' | 'update_not_available';
            stepId: string;
            message: string;
            guideUrl?: string | undefined;
        } | null;
    };
    readonly "machines.agents.install.cancel": {
        ok: false;
        errorCode: 'invalid_request' | 'job_not_found' | 'install_unavailable';
        error: string;
    } | {
        ok: true;
    };
};
