// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
export type MachineAgentSignInActionInputById = {
    readonly "machines.agents.signIn.start": {
        agentId: string;
        machineId: string;
        method?: 'native' | 'connected' | undefined;
        serviceId?: string | undefined;
    };
    readonly "machines.agents.signIn.status": {
        agentId: string;
        machineId: string;
    };
};

export type MachineAgentSignInActionResultById = {
    readonly "machines.agents.signIn.start": {
        status: 'starting';
        attemptId: string;
    } | {
        status: 'awaitingManual';
        attemptId: string;
    } | {
        status: 'awaitingOAuth';
        attemptId: string;
        callbackUrl: string;
        authorizationUrl?: string | undefined;
        expiresAtMs?: number | undefined;
    } | {
        status: 'awaitingDeviceAuthorization';
        attemptId: string;
        verificationUri?: string | undefined;
        verificationUriComplete?: string | undefined;
        userCode?: string | undefined;
        expiresAtMs?: number | undefined;
        pollIntervalMs?: number | undefined;
    } | {
        status: 'configurationRequired';
        target: {
            kind: 'service';
            service: {
                pluginId: string;
                localId: string;
            };
            modeId: string;
        } | {
            kind: 'account';
            account: {
                service: {
                    pluginId: string;
                    localId: string;
                };
                accountId: string;
            };
            modeId: string;
        } | {
            kind: 'attempt';
            attemptId: string;
            service: {
                pluginId: string;
                localId: string;
            };
            modeId: string;
        };
        missingFieldIds: string[];
        attemptId?: string | undefined;
    } | {
        status: 'pending';
        attemptId: string;
        retryAfterMs: number;
    } | {
        status: 'outcomeUnknown';
        attemptId: string;
        diagnostic: unknown;
    } | {
        status: 'reconnectRequired';
        attemptId: string;
        code: string;
    } | {
        status: 'connected';
        attemptId: string;
        account: {
            service: {
                pluginId: string;
                localId: string;
            };
            accountId: string;
        };
    } | {
        status: 'cancelled';
        attemptId: string;
    } | {
        status: 'cleanupPending';
        attemptId: string;
        code: 'connected_account_attempt_cleanup_pending';
    } | {
        status: 'rejected';
        code: string;
        attemptId?: string | undefined;
        diagnostic?: unknown;
        failureClass?: 'rateLimit' | undefined;
        retryNotBeforeMs?: number | undefined;
    } | {
        status: 'unavailable';
        code: string;
        attemptId?: string | undefined;
        diagnostic?: unknown;
        failureClass?: 'rateLimit' | undefined;
        retryNotBeforeMs?: number | undefined;
    } | {
        status: 'conflict';
        code: string;
        attemptId?: string | undefined;
        diagnostic?: unknown;
    } | {
        terminalKey: string;
    } | {
        ok: false;
        errorCode: string;
        error: string;
    };
    readonly "machines.agents.signIn.status": {
        status: 'unknown' | 'signedIn' | 'signedOut';
        accountLabel: string | null;
        checkedAt: number;
        nativeLogin: 'login_terminal' | 'status_only' | 'manual_only' | 'unsupported';
        connectedServices: {
            serviceId: string;
            title: string;
        }[];
    };
};
