// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
export type SavedSecretSharingActionInputById = {
    readonly "secrets.shared.list": Record<string, never>;
    readonly "secrets.shared.create": {
        resourceId: string;
        displayName: string;
        kind: 'apiKey' | 'token' | 'password' | 'other';
        encryptionMode: 'plain' | 'e2ee';
        storedContent: {
            t: 'plain';
            v: {
                v: 1;
                name: string;
                kind: 'apiKey' | 'token' | 'password' | 'other';
                value: string;
            };
        } | {
            t: 'encrypted';
            c: string;
        };
        accountGrants?: string[] | undefined;
        teamGrants?: string[] | undefined;
        groupGrants?: string[] | undefined;
        keyEnvelopes?: {
            recipientAccountId: string;
            encryptedDataKey: string;
            recipientContentPublicKeyFingerprint: string;
        }[] | undefined;
    };
    readonly "secrets.shared.promote": {
        resourceId: string;
        displayName: string;
        kind: 'apiKey' | 'token' | 'password' | 'other';
        encryptionMode: 'plain' | 'e2ee';
        storedContent: {
            t: 'plain';
            v: {
                v: 1;
                name: string;
                kind: 'apiKey' | 'token' | 'password' | 'other';
                value: string;
            };
        } | {
            t: 'encrypted';
            c: string;
        };
        expectedSettingsVersion: number;
        nextSettings: {
            t: 'plain';
            v: {
                [x: string]: unknown;
            };
        } | {
            t: 'encrypted';
            c: string;
        } | null;
        accountGrants?: string[] | undefined;
        teamGrants?: string[] | undefined;
        groupGrants?: string[] | undefined;
        keyEnvelopes?: {
            recipientAccountId: string;
            encryptedDataKey: string;
            recipientContentPublicKeyFingerprint: string;
        }[] | undefined;
    };
    readonly "secrets.shared.grants.set": {
        resourceId: string;
        expectedRevision: number;
        accountGrants: string[];
        teamGrants: string[];
        groupGrants: string[];
        keyEnvelopes?: {
            recipientAccountId: string;
            encryptedDataKey: string;
            recipientContentPublicKeyFingerprint: string;
        }[] | undefined;
    };
    readonly "secrets.shared.update": {
        resourceId: string;
        expectedRevision: number;
        displayName: string;
        kind: 'apiKey' | 'token' | 'password' | 'other';
        storedContent: {
            t: 'plain';
            v: {
                v: 1;
                name: string;
                kind: 'apiKey' | 'token' | 'password' | 'other';
                value: string;
            };
        } | {
            t: 'encrypted';
            c: string;
        };
        toMode?: 'plain' | 'e2ee' | undefined;
        keyEnvelopes?: {
            recipientAccountId: string;
            encryptedDataKey: string;
            recipientContentPublicKeyFingerprint: string;
        }[] | undefined;
    };
    readonly "secrets.shared.delete": {
        resourceId: string;
        expectedRevision: number;
    };
};

export type SavedSecretSharingActionResultById = {
    readonly "secrets.shared.list": {
        resources: ({
            materialStatus: 'resource_corrupt';
            relationship: 'owner';
            repair: {
                kind: 'delete_resource';
                resourceId: string;
                expectedRevision: number;
            };
        } | {
            materialStatus: 'resource_corrupt';
            relationship: 'recipient';
            repair: null;
        } | {
            ref: string;
            source: 'personal' | 'shared_resource';
            relationship: 'owner' | 'recipient';
            name: string | null;
            kind: 'apiKey' | 'token' | 'password' | 'other' | null;
            encryptionMode: 'plain' | 'e2ee' | null;
            owner: {
                firstName: string | null;
                lastName: string | null;
                username: string | null;
                avatarUrl: string | null;
                kind: 'account';
                accountId: string;
            } | null;
            accessSources: ({
                kind: 'account';
            } | {
                kind: 'team';
                teamId: string;
                name: string;
            } | {
                kind: 'group';
                teamId: string;
                teamName: string;
                groupId: string;
                name: string;
            })[];
            audience: {
                accounts: {
                    firstName: string | null;
                    lastName: string | null;
                    username: string | null;
                    avatarUrl: string | null;
                    kind: 'account';
                    accountId: string;
                }[];
                teams: {
                    kind: 'team';
                    teamId: string;
                    name: string;
                }[];
                groups: {
                    kind: 'group';
                    teamId: string;
                    teamName: string;
                    groupId: string;
                    name: string;
                }[];
            } | null;
            ownerAccountId: string | null;
            revision: number | null;
            materialStatus: 'ready' | 'preparing_encrypted_access' | 'recipient_mode_unsupported' | 'temporarily_unavailable' | 'access_removed' | 'deleted' | 'update_required';
            capabilities: {
                use: boolean;
                rename: boolean;
                rotate: boolean;
                manageAccess: boolean;
                delete: boolean;
            };
        })[];
    };
    readonly "secrets.shared.create": {
        resourceId: string;
        revision: number;
    };
    readonly "secrets.shared.promote": {
        resourceId: string;
        settingsVersion: number;
    };
    readonly "secrets.shared.grants.set": {
        resourceId: string;
        revision: number;
    };
    readonly "secrets.shared.update": {
        resourceId: string;
        revision: number;
    };
    readonly "secrets.shared.delete": {
        resourceId: string;
    };
};
