import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import test from 'node:test';

const packageRoot = fileURLToPath(new URL('..', import.meta.url));
const repoRoot = fileURLToPath(new URL('../../..', import.meta.url));
const readPackageFile = (path) => readFileSync(`${packageRoot}/${path}`, 'utf8');
const readRepoFile = (path) => readFileSync(`${repoRoot}/${path}`, 'utf8');

test('iOS and Android ship the shared locked-Cargo evidence generated by their native build', () => {
  const packageJson = JSON.parse(readPackageFile('package.json'));
  const iosBuild = readPackageFile('scripts/build-rust-ios.sh');
  const androidBuild = readPackageFile('scripts/build-rust-android.sh');
  const podspec = readPackageFile('ios/HappierIrohNative.podspec');
  const gradle = readPackageFile('android/build.gradle');

  assert.match(packageJson.scripts['generate:release-evidence'], /generate-native-release-evidence\.mjs/u);
  assert.match(iosBuild, /generate-native-release-evidence\.mjs/u);
  assert.match(androidBuild, /generate-native-release-evidence\.mjs/u);
  assert.match(podspec, /s\.resources\s*=\s*'\.\.\/release-evidence\/\*'/u);
  assert.match(gradle, /assets\.srcDirs\s*\+=\s*\["\$\{projectDir\}\/\.\.\/release-evidence"\]/u);
});

test('Tauri build generates and bundles the same locked-Cargo evidence', () => {
  const uiPackage = JSON.parse(readRepoFile('apps/ui/package.json'));
  const tauriConfig = JSON.parse(readRepoFile('apps/ui/src-tauri/tauri.conf.json'));
  const workflow = readRepoFile('.github/workflows/build-tauri.yml');

  assert.match(
    uiPackage.scripts['tauri:prepare:build'],
    /iroh:generate-release-evidence/u,
  );
  assert.deepEqual(tauriConfig.bundle.resources, {
    '../../../packages/iroh-native/release-evidence/THIRD-PARTY-NOTICES.txt':
      'licenses/iroh-native/THIRD-PARTY-NOTICES.txt',
    '../../../packages/iroh-native/release-evidence/sbom.cdx.json':
      'licenses/iroh-native/sbom.cdx.json',
  });

  const rustToolchainSteps = [
    ...workflow.matchAll(
      /uses: dtolnay\/rust-toolchain@[a-f0-9]+\n\s+with:\n([\s\S]*?)(?=\n\s+- name:)/gu,
    ),
  ];
  assert.equal(rustToolchainSteps.length, 2);
  for (const [, inputs] of rustToolchainSteps) {
    assert.match(inputs, /^\s+toolchain:\s*1\.94\.1$/mu);
    assert.match(inputs, /^\s+targets:\s*\$\{\{ matrix\.tauri_target \}\}$/mu);
  }
});

test('pinned Rust actions name the toolchain whose targets they install', () => {
  for (const workflowPath of [
    '.github/workflows/build-tauri.yml',
    '.github/workflows/publish-ui-web.yml',
    '.github/workflows/tests.yml',
  ]) {
    const workflow = readRepoFile(workflowPath);
    const steps = [
      ...workflow.matchAll(
        /uses: dtolnay\/rust-toolchain@[a-f0-9]+(?:\n\s+with:\n([\s\S]*?))?(?=\n\s+- name:)/gu,
      ),
    ];
    assert.ok(steps.length > 0, `${workflowPath} must contain a pinned Rust action`);
    for (const [, inputs = ''] of steps) {
      assert.match(inputs, /^\s+toolchain:\s*1\.94\.1$/mu, workflowPath);
    }
  }
});
