// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.


// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
export type AccountPluginDataActionInputById = {
    readonly "account.plugins.data.erase": {
        pluginId: string;
    };
};
export type AccountPluginDataActionResultById = {
    readonly "account.plugins.data.erase": {
        status: 'completed' | 'partial' | 'failed';
        settings: {
            status: 'completed';
            changed: boolean;
        } | {
            status: 'pending';
            reason: 'conflict' | 'unavailable' | 'outcome-unknown';
        } | {
            status: 'failed';
            reason: 'unexpected';
        };
        data: {
            status: 'completed';
            changed: boolean;
        } | {
            status: 'pending';
            reason: 'unavailable' | 'outcome-unknown' | 'transition-cleanup';
        } | {
            status: 'failed';
            reason: 'account-not-found' | 'request-rejected' | 'invalid-response';
        };
    };
};
