// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.


// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
export type AccountSecurityActionInputById = {
    readonly "account.security.get": Record<string, never>;
};
export type AccountSecurityActionResultById = {
    readonly "account.security.get": {
        v: 1;
        encryptionMode: 'plain' | 'e2ee';
        terminalPresentUserPolicy: 'allowed' | 'disallowed';
        nativeEmail: string | null;
        password: {
            status: 'enrolled';
            revision: number;
        } | {
            status: 'not_enrolled';
            revision: null;
        };
    };
};
