// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.


// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
export type AgentAcpCatalogActionInputById = {
    readonly "agents.acp.backends.upsert": {
        backend: {
            [x: string]: unknown;
            id: string;
            name: string;
            title: string;
            command: string;
            description?: string | undefined;
            args?: string[] | undefined;
            env?: Record<string, {
                t: 'literal';
                v: string;
            } | {
                t: 'savedSecret';
                secretId: string;
            }> | undefined;
            auth?: {
                support: string;
                machineLoginKey?: string | undefined;
                docsUrl?: string | undefined;
                loginCommand?: {
                    command: string;
                    args?: string[] | undefined;
                } | undefined;
                envVars?: string[] | undefined;
            } | undefined;
            defaultMode?: string | undefined;
            defaultModel?: string | undefined;
            capabilities?: Record<string, unknown> | undefined;
            createdAt?: number | undefined;
            updatedAt?: number | undefined;
        };
    };
    readonly "agents.acp.backends.delete": {
        backendId: string;
    };
};
export type AgentAcpCatalogActionResultById = {
    readonly "agents.acp.backends.upsert": {
        backend: {
            id: string;
            name: string;
            title: string;
            command: string;
            args: string[];
            env: Record<string, {
                t: 'literal';
                v: string;
            } | {
                t: 'savedSecret';
                secretId: string;
            }>;
            capabilities: {
                supportsLoadSession: boolean;
                supportsModes: 'unknown' | 'yes' | 'no';
                supportsModels: 'unknown' | 'yes' | 'no';
                supportsConfigOptions: 'unknown' | 'yes' | 'no';
                promptImageSupport: 'unknown' | 'yes' | 'no';
            };
            createdAt: number;
            updatedAt: number;
            description?: string | undefined;
            auth?: {
                support: 'login_terminal' | 'status_only' | 'manual_only' | 'unsupported';
                machineLoginKey?: string | undefined;
                docsUrl?: string | undefined;
                loginCommand?: {
                    command: string;
                    args: string[];
                } | undefined;
                envVars?: string[] | undefined;
            } | undefined;
            defaultMode?: string | undefined;
            defaultModel?: string | undefined;
        };
    };
    readonly "agents.acp.backends.delete": {
        backendId: string;
        deleted: true;
    };
};
