// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.


// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
export type AppShellActionInputById = {
    readonly "inbox.mark_all_read": {
        targets: {
            serverId: string;
            sessionId: string;
        }[];
    };
    readonly "session.draft.delete": {
        draftId: string;
    };
    readonly "session.draft.directory.set": {
        ref: {
            readonly kind: 'session';
            readonly sessionId: string;
        } | {
            readonly kind: 'newSession';
            readonly instanceId: string;
        } | {
            readonly kind: 'pendingMessage';
            readonly sessionId: string;
            readonly localId: string;
        } | {
            readonly kind: 'participantMessage';
            readonly sessionId: string;
            readonly instanceId: string;
        } | {
            readonly kind: 'automationAuthoring';
            readonly sessionId: string;
            readonly instanceId: string;
        } | {
            readonly kind: 'workflowAuthoring';
            readonly draftId: string;
            readonly blockId: string;
            readonly instanceId: string;
        };
        directory: {
            kind: 'path';
            path: string;
        } | {
            kind: 'managed';
        };
    };
};
export type AppShellActionResultById = {
    readonly "inbox.mark_all_read": {
        results: {
            serverId: string;
            sessionId: string;
            status: 'succeeded' | 'failed' | 'skipped' | 'cancelled';
        }[];
    };
    readonly "session.draft.delete": {
        status: 'deleted' | 'missing' | 'launch_custody' | 'unavailable';
    };
    readonly "session.draft.directory.set": {
        status: 'unavailable' | 'applied';
    };
};
