// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.

import type { JsonValue } from './strictJsonValue.generated.js';

export type AutomationConversationActionInputById = {
    readonly "automation.conversation.targets.list": {
        limit?: number | undefined;
        cursor?: string | null | undefined;
    };
    readonly "automation.conversation.target.verify": {
        automationId: string;
        resultDelivery?: 'finalResult' | undefined;
    };
    readonly "automation.conversation.admit": {
        automationId: string;
        bindingId: string;
        occurrenceId: string;
        occurredAt: number;
        sender: JsonValue;
        text: string;
        resultDelivery: {
            kind: 'none';
        } | {
            kind: 'finalResult';
            actionRef: {
                pluginId: string;
                localId: string;
            };
            opaqueContext: JsonValue;
        };
    };
};
export type AutomationConversationActionResultById = {
    readonly "automation.conversation.targets.list": {
        items: {
            automationId: string;
            label: string;
            execution: {
                targetType: 'new_session' | 'existing_session' | 'execution_run' | null;
                enabled: boolean;
            };
        }[];
        nextCursor: string | null;
    };
    readonly "automation.conversation.target.verify": {
        kind: 'verified';
    } | {
        kind: 'notVerified';
        reason: 'notFound' | 'resultDeliveryUnsupported';
    };
    readonly "automation.conversation.admit": {
        kind: 'admitted';
        runId: string;
        checkpointSafe: true;
    } | {
        kind: 'rejoined';
        runId: string;
        checkpointSafe: true;
    } | {
        kind: 'blocked';
        reason: 'resultDeliveryUnsupported' | 'capacity' | 'temporarilyUnavailable' | 'occurrenceConflict' | 'noEnabledAssignment';
        checkpointSafe: false;
    };
};
