// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.

import type { QualifiedAudienceSelection } from './pluginActionDtoSupport.generated.js';

export type BoardsActionInputById = {
    readonly "boards.list": Record<string, never>;
    readonly "boards.apply": {
        intent: {
            kind: 'create';
            board: {
                id: string;
                name: string;
            };
        } | {
            kind: 'delete';
            boardId: string;
        } | {
            kind: 'update';
            boardId: string;
            patch: {
                name?: string | undefined;
                mode?: 'canvas' | 'by_status' | undefined;
                snap?: boolean | undefined;
                pinnedInSessions?: boolean | undefined;
                source?: {
                    sections?: ('needs_you' | 'running' | 'my_machines')[] | undefined;
                    filter?: {
                        show: 'sessions' | 'runs' | 'both';
                        startedBy: ('you' | 'triggers' | 'agents')[];
                        scope: 'my_work' | 'assigned_to_me' | 'following' | 'involving_me' | 'all_accessible';
                        attention: 'any' | 'needs_my_attention';
                        homeServerIds: string[];
                        audiences: ({
                            kind: 'outside_teams';
                            serverId: string;
                        } | {
                            kind: 'team';
                            teamId: string;
                            serverId: string;
                        } | {
                            kind: 'group';
                            teamId: string;
                            groupId: string;
                            serverId: string;
                        })[];
                        tagIds: {
                            serverId: string;
                            tagId: string;
                        }[];
                        source: 'all' | 'persisted' | 'direct';
                    } | undefined;
                    picked?: {
                        kind: 'session' | 'workflow_run' | 'workflow' | 'machine';
                        qualifiedId: {
                            serverId: string;
                            id: string;
                        };
                    }[] | undefined;
                } | undefined;
            };
        } | {
            kind: 'add_items';
            boardId: string;
            refs: {
                kind: 'session' | 'workflow_run' | 'workflow' | 'machine';
                qualifiedId: {
                    serverId: string;
                    id: string;
                };
            }[];
            positionsByItemRef?: Record<string, {
                x: number;
                y: number;
            }> | undefined;
        } | {
            kind: 'remove_item';
            boardId: string;
            ref: {
                kind: 'session' | 'workflow_run' | 'workflow' | 'machine';
                qualifiedId: {
                    serverId: string;
                    id: string;
                };
            };
            membership?: {
                liveItemKeys: string[];
                unavailableServerIds: string[];
            } | undefined;
        } | {
            kind: 'set_positions';
            boardId: string;
            positionsByItemRef: Record<string, {
                x: number;
                y: number;
            }>;
            membership?: {
                liveItemKeys: string[];
                unavailableServerIds: string[];
            } | undefined;
        };
        boardId?: string | undefined;
    };
};
export type BoardsActionResultById = {
    readonly "boards.list": {
        boards: Readonly<{
            id: string;
            name: string;
            source: Readonly<{
                sections?: readonly ('needs_you' | 'running' | 'my_machines')[] | undefined;
                filter?: Readonly<{
                    show: 'sessions' | 'runs' | 'both';
                    startedBy: readonly ('you' | 'triggers' | 'agents')[];
                    scope: 'my_work' | 'assigned_to_me' | 'following' | 'involving_me' | 'all_accessible';
                    attention: 'any' | 'needs_my_attention';
                    homeServerIds: readonly string[];
                    audiences: readonly QualifiedAudienceSelection[];
                    tagIds: readonly Readonly<{
                        serverId: string;
                        tagId: string;
                    }>[];
                    source: 'all' | 'persisted' | 'direct';
                }> | undefined;
                picked: readonly Readonly<{
                    kind: 'session' | 'workflow_run' | 'workflow' | 'machine';
                    qualifiedId: Readonly<{
                        serverId: string;
                        id: string;
                    }>;
                }>[];
                unknown?: Readonly<{
                    sections?: readonly string[] | undefined;
                    picked?: readonly unknown[] | undefined;
                }> | undefined;
            }>;
            mode: 'canvas' | 'by_status';
            snap: boolean;
            positionsByItemRef: Readonly<Record<string, Readonly<{
                x: number;
                y: number;
            }>>>;
            pinnedInSessions: boolean;
        }>[];
    };
    readonly "boards.apply": {
        boardId: string;
        board: Readonly<{
            id: string;
            name: string;
            source: Readonly<{
                sections?: readonly ('needs_you' | 'running' | 'my_machines')[] | undefined;
                filter?: Readonly<{
                    show: 'sessions' | 'runs' | 'both';
                    startedBy: readonly ('you' | 'triggers' | 'agents')[];
                    scope: 'my_work' | 'assigned_to_me' | 'following' | 'involving_me' | 'all_accessible';
                    attention: 'any' | 'needs_my_attention';
                    homeServerIds: readonly string[];
                    audiences: readonly QualifiedAudienceSelection[];
                    tagIds: readonly Readonly<{
                        serverId: string;
                        tagId: string;
                    }>[];
                    source: 'all' | 'persisted' | 'direct';
                }> | undefined;
                picked: readonly Readonly<{
                    kind: 'session' | 'workflow_run' | 'workflow' | 'machine';
                    qualifiedId: Readonly<{
                        serverId: string;
                        id: string;
                    }>;
                }>[];
                unknown?: Readonly<{
                    sections?: readonly string[] | undefined;
                    picked?: readonly unknown[] | undefined;
                }> | undefined;
            }>;
            mode: 'canvas' | 'by_status';
            snap: boolean;
            positionsByItemRef: Readonly<Record<string, Readonly<{
                x: number;
                y: number;
            }>>>;
            pinnedInSessions: boolean;
        }> | null;
    };
};
