// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.


// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
export type BrowserDiagnosticsActionInputById = {
    readonly "browser.diagnostics.snapshot": {
        [x: string]: unknown;
        browserSessionId: string;
        viewId: string;
    };
    readonly "browser.diagnostics.clear": {
        [x: string]: unknown;
        browserSessionId: string;
        viewId: string;
    };
    readonly "browser.diagnostics.pause": {
        [x: string]: unknown;
        browserSessionId: string;
        viewId: string;
    };
    readonly "browser.diagnostics.resume": {
        [x: string]: unknown;
        browserSessionId: string;
        viewId: string;
    };
    readonly "browser.diagnostics.eval": {
        v: 1;
        evalRequestId: string;
        viewId: string;
        navigationGeneration: number;
        tier: 'cdp' | 'injectedPage';
        expression: string;
        objectGroupId: string;
        diagnosticsInteractionEnabled: true;
        timeoutMs?: number | undefined;
    };
    readonly "browser.diagnostics.getProperties": {
        v: 1;
        propertyRequestId: string;
        viewId: string;
        navigationGeneration: number;
        tier: 'cdp' | 'injectedPage';
        objectId: string;
        objectGroupId: string;
        diagnosticsInteractionEnabled: true;
    };
    readonly "browser.diagnostics.releaseObjectGroup": {
        v: 1;
        releaseRequestId: string;
        viewId: string;
        navigationGeneration: number;
        tier: 'cdp' | 'injectedPage';
        objectGroupId: string;
        diagnosticsInteractionEnabled: true;
    };
    readonly "browser.diagnostics.elementPicker.start": {
        v: 1;
        pickerRequestId: string;
        viewId: string;
        navigationGeneration: number;
        tier: 'cdp' | 'injectedPage';
        action: 'start' | 'cancel';
        diagnosticsInteractionEnabled: true;
    };
    readonly "browser.diagnostics.elementPicker.cancel": {
        v: 1;
        pickerRequestId: string;
        viewId: string;
        navigationGeneration: number;
        tier: 'cdp' | 'injectedPage';
        action: 'start' | 'cancel';
        diagnosticsInteractionEnabled: true;
    };
};
export type BrowserDiagnosticsActionResultById = {
    readonly "browser.diagnostics.snapshot": {
        v: 1;
        machineId: string;
        generatedAt: number;
        refreshState: 'error' | 'idle' | 'refreshing';
        events: {
            v: 1;
            eventId: string;
            browserSessionId: string;
            viewId: string;
            navigationGeneration: number;
            capturedAtMs: number;
            family: 'console' | 'pageError' | 'network' | 'elements' | 'resources' | 'storage' | 'pageInfo' | 'performance' | 'screenshot' | 'proxyTunnel';
            kind: 'console.entry' | 'pageError.thrown' | 'network.requestStarted' | 'network.response' | 'network.finished' | 'network.failed' | 'network.redirect' | 'network.websocketOpened' | 'network.websocketSummary' | 'network.websocketClosed' | 'network.eventSourceOpened' | 'network.eventSourceSummary' | 'network.eventSourceClosed' | 'network.sendBeacon' | 'elements.snapshot' | 'elements.pickerState' | 'resources.snapshot' | 'storage.availability' | 'storage.keyInventory' | 'pageInfo.snapshot' | 'pageInfo.capabilities' | 'pageInfo.domSnapshot' | 'performance.vitals' | 'screenshot.metadata' | 'proxyTunnel.snapshot' | 'diagnostics.unavailable' | 'eval.requested' | 'eval.completed' | 'eval.failed' | 'eval.timedOut' | 'collector.degraded';
            fidelity: 'cdp' | 'injectedPage' | 'previewProxy' | 'nativeCallback' | 'streamFrame' | 'unavailable';
            trusted: boolean;
            data: Record<string, unknown>;
            redaction: {
                level: 'unavailable' | 'none' | 'metadataOnly' | 'valuesRedacted';
                queryRedacted: boolean;
                headersRedacted: boolean;
                truncated: boolean;
            };
            collector?: {
                collectorId: string;
                nonce: string;
                version: string;
            } | undefined;
            unavailableReason?: 'feature_disabled' | 'adapter_unavailable' | 'policy_denied' | 'collector_denied' | 'collector_unavailable' | 'collector_degraded' | 'navigation_stale' | 'target_detached' | 'page_crashed' | 'unsupported_fidelity' | undefined;
        }[];
        diagnostics: Record<string, unknown>[];
    };
    readonly "browser.diagnostics.clear": {
        ok: true;
    };
    readonly "browser.diagnostics.pause": {
        ok: true;
        status: 'paused';
        viewId: string;
    };
    readonly "browser.diagnostics.resume": {
        ok: true;
        status: 'resumed';
        viewId: string;
    };
    readonly "browser.diagnostics.eval": {
        v: 1;
        evalRequestId: string;
        viewId: string;
        navigationGeneration: number;
        status: 'completed' | 'failed' | 'timedOut' | 'blocked' | 'collectorDegraded';
        tier: 'cdp' | 'injectedPage';
        audited: true;
        result?: {
            type: 'string' | 'number' | 'bigint' | 'boolean' | 'symbol' | 'undefined' | 'object' | 'function' | 'null';
            preview: {
                name: string;
                valuePreview: string;
                truncated: boolean;
            }[];
            value?: string | number | boolean | null | undefined;
            objectId?: string | undefined;
            className?: string | undefined;
            description?: string | undefined;
        } | undefined;
        errorCode?: 'feature_disabled' | 'adapter_unavailable' | 'policy_denied' | 'collector_denied' | 'collector_unavailable' | 'collector_degraded' | 'navigation_stale' | 'target_detached' | 'page_crashed' | 'unsupported_fidelity' | undefined;
    };
    readonly "browser.diagnostics.getProperties": {
        v: 1;
        propertyRequestId: string;
        viewId: string;
        navigationGeneration: number;
        tier: 'cdp' | 'injectedPage';
        status: 'completed' | 'failed' | 'blocked' | 'collectorDegraded';
        audited: true;
        objectId: string;
        properties: {
            name: string;
            value: {
                type: 'string' | 'number' | 'bigint' | 'boolean' | 'symbol' | 'undefined' | 'object' | 'function' | 'null';
                preview: {
                    name: string;
                    valuePreview: string;
                    truncated: boolean;
                }[];
                value?: string | number | boolean | null | undefined;
                objectId?: string | undefined;
                className?: string | undefined;
                description?: string | undefined;
            };
            enumerable: boolean;
        }[];
        errorCode?: 'feature_disabled' | 'adapter_unavailable' | 'policy_denied' | 'collector_denied' | 'collector_unavailable' | 'collector_degraded' | 'navigation_stale' | 'target_detached' | 'page_crashed' | 'unsupported_fidelity' | undefined;
    };
    readonly "browser.diagnostics.releaseObjectGroup": {
        v: 1;
        releaseRequestId: string;
        viewId: string;
        navigationGeneration: number;
        tier: 'cdp' | 'injectedPage';
        status: 'completed' | 'failed' | 'blocked' | 'collectorDegraded';
        audited: true;
        objectGroupId: string;
        errorCode?: 'feature_disabled' | 'adapter_unavailable' | 'policy_denied' | 'collector_denied' | 'collector_unavailable' | 'collector_degraded' | 'navigation_stale' | 'target_detached' | 'page_crashed' | 'unsupported_fidelity' | undefined;
    };
    readonly "browser.diagnostics.elementPicker.start": {
        v: 1;
        pickerRequestId: string;
        viewId: string;
        navigationGeneration: number;
        tier: 'cdp' | 'injectedPage';
        status: 'failed' | 'blocked' | 'collectorDegraded' | 'selected' | 'cancelled';
        audited: true;
        backendNodeRef?: string | undefined;
        selectorPath?: string | undefined;
        rect?: {
            x: number;
            y: number;
            width: number;
            height: number;
        } | undefined;
        accessibleName?: string | undefined;
        componentName?: string | undefined;
        sourceLocation?: {
            file: string;
            line?: number | undefined;
            column?: number | undefined;
        } | undefined;
        errorCode?: 'feature_disabled' | 'adapter_unavailable' | 'policy_denied' | 'collector_denied' | 'collector_unavailable' | 'collector_degraded' | 'navigation_stale' | 'target_detached' | 'page_crashed' | 'unsupported_fidelity' | undefined;
    };
    readonly "browser.diagnostics.elementPicker.cancel": {
        v: 1;
        pickerRequestId: string;
        viewId: string;
        navigationGeneration: number;
        tier: 'cdp' | 'injectedPage';
        status: 'failed' | 'blocked' | 'collectorDegraded' | 'selected' | 'cancelled';
        audited: true;
        backendNodeRef?: string | undefined;
        selectorPath?: string | undefined;
        rect?: {
            x: number;
            y: number;
            width: number;
            height: number;
        } | undefined;
        accessibleName?: string | undefined;
        componentName?: string | undefined;
        sourceLocation?: {
            file: string;
            line?: number | undefined;
            column?: number | undefined;
        } | undefined;
        errorCode?: 'feature_disabled' | 'adapter_unavailable' | 'policy_denied' | 'collector_denied' | 'collector_unavailable' | 'collector_degraded' | 'navigation_stale' | 'target_detached' | 'page_crashed' | 'unsupported_fidelity' | undefined;
    };
};
