// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.


// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
export type CaptureViewingActionInputById = {
    readonly "capture.view": {
        sourceId: string;
        sourceOccurrenceId: string;
    };
};
export type CaptureViewingActionResultById = {
    readonly "capture.view": {
        admitted: true;
        sourceId: string;
        sourceOccurrenceId: string;
    };
};
