// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.


// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
export type CommandPaletteActionInputById = {
    readonly "ui.command_palette.list": Record<string, never>;
    readonly "ui.command_palette.invoke": {
        commandId: string;
    };
};
export type CommandPaletteActionResultById = {
    readonly "ui.command_palette.list": {
        commands: {
            id: string;
            title: string;
            subtitle?: string | undefined;
            category?: string | undefined;
        }[];
    };
    readonly "ui.command_palette.invoke": {
        invoked: true;
    };
};
