// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.

import type { JsonValue } from './strictJsonValue.generated.js';

export type CompanionControlsActionInputById = {
    readonly "ui.pet.choose": Record<string, never>;
};
export type CompanionControlsActionResultById = {
    readonly "ui.pet.choose": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
};
