// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.


// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
export type ConnectedServicesConfigurationActionInputById = {
    readonly "connectedServices.accounts.rename": {
        account: {
            service: {
                pluginId: string;
                localId: string;
            };
            accountId: string;
        };
        label: string | null;
    };
    readonly "connectedServices.pools.switchNow": {
        group: {
            service: {
                pluginId: string;
                localId: string;
            };
            groupId: string;
        };
        connectedAccountId: string;
        expectedGeneration: number;
        expectedIncarnation?: string | undefined;
        expectedRuntimeStateRevision?: number | undefined;
        expectedSource?: {
            connectedAccountId: string;
            credentialRevision: string;
            configurationRevision: string | null;
        } | undefined;
        overrideRuntimeCooldown?: boolean | undefined;
    };
    readonly "connectedServices.pools.reorder": {
        group: {
            service: {
                pluginId: string;
                localId: string;
            };
            groupId: string;
        };
        accountIds: string[];
    };
    readonly "connectedServices.pools.default.set": {
        group: {
            service: {
                pluginId: string;
                localId: string;
            };
            groupId: string;
        };
        agentId: string;
        makeDefault: boolean;
        machineId?: string | undefined;
    };
    readonly "connectedServices.quota.reset": {
        machineId: string;
        serviceId: 'openai-codex' | 'openai' | 'anthropic' | 'claude-subscription' | 'gemini' | 'github' | 'bitbucket';
        profileId: string;
        providerCreditId?: string | undefined;
        sourceSnapshotFetchedAtMs?: number | null | undefined;
    };
    readonly "connectedServices.quota.refresh": {
        account: {
            service: {
                pluginId: string;
                localId: string;
            };
            accountId: string;
        };
        machineId: string;
    };
    readonly "connectedServices.identityPrivacy.set": {
        hidden: boolean;
    };
};
export type ConnectedServicesConfigurationActionResultById = {
    readonly "connectedServices.accounts.rename": {
        applied: true;
    };
    readonly "connectedServices.pools.switchNow": {
        applied: true;
    };
    readonly "connectedServices.pools.reorder": {
        applied: true;
    };
    readonly "connectedServices.pools.default.set": {
        applied: true;
    };
    readonly "connectedServices.quota.reset": {
        [x: string]: unknown;
        ok: true;
        snapshot: {
            v: 1;
            serviceId: 'openai-codex' | 'openai' | 'anthropic' | 'claude-subscription' | 'gemini' | 'github' | 'bitbucket';
            profileId: string;
            fetchedAt: number;
            staleAfterMs: number;
            planLabel: string | null;
            accountLabel: string | null;
            meters: {
                meterId: string;
                label: string;
                used: number | null;
                limit: number | null;
                unit: 'unknown' | 'credits' | 'count' | 'tokens' | 'usd' | 'requests';
                utilizationPct: number | null;
                resetsAt: number | null;
                status: 'ok' | 'estimated' | 'unavailable';
                details: {
                    note?: string | null | undefined;
                    code?: string | undefined;
                    rawScope?: string | undefined;
                    remainingPct?: number | null | undefined;
                    scope?: 'unknown' | 'tokens' | 'requests' | 'primary' | 'secondary' | 'daily' | 'weekly' | 'monthly' | 'five_hour' | 'seven_day' | 'session' | 'rolling' | 'model' | undefined;
                    providerLimitId?: string | undefined;
                    limitCategory?: 'unknown' | 'usage_limit' | 'rate_limit' | 'capacity' | 'temporary_throttle' | 'auth_invalid' | 'plan_invalid' | 'validation_failed' | 'disabled' | undefined;
                };
                remaining?: number | null | undefined;
                remainingPct?: number | null | undefined;
                usedPct?: number | null | undefined;
                resetAtMs?: number | null | undefined;
                resetSource?: 'unknown' | 'in_band_snapshot' | 'header' | 'body' | 'provider_event' | 'provider_probe' | 'computed' | 'provider' | 'retry_after' | 'manual' | undefined;
                providerLimitId?: string | undefined;
                windowDurationMs?: number | undefined;
                modelId?: string | null | undefined;
                isExhausted?: boolean | undefined;
                isSoftLimited?: boolean | undefined;
                isCapacityLimited?: boolean | undefined;
                source?: 'unknown' | 'provider_api' | 'background_fetch' | 'runtime_event' | 'runtime_probe' | 'in_band_snapshot' | 'in_band_provider_snapshot' | 'manual_refresh' | 'user_probe' | 'cached' | undefined;
                scope?: 'unknown' | 'tokens' | 'requests' | 'primary' | 'secondary' | 'daily' | 'weekly' | 'monthly' | 'five_hour' | 'seven_day' | 'session' | 'rolling' | 'model' | undefined;
                limitScope?: 'account' | 'unknown' | 'provider' | 'session' | 'model' | 'workspace' | 'organization' | undefined;
                confidence?: 'unknown' | 'exact' | 'derived' | 'estimated' | 'stale' | undefined;
            }[];
            providerId?: string | undefined;
            activeAccountId?: string | undefined;
            fetchedAtMs?: number | undefined;
            staleAtMs?: number | undefined;
            source?: 'unknown' | 'provider_api' | 'background_fetch' | 'runtime_event' | 'runtime_probe' | 'in_band_snapshot' | 'in_band_provider_snapshot' | 'manual_refresh' | 'user_probe' | 'cached' | undefined;
            confidence?: 'unknown' | 'exact' | 'derived' | 'estimated' | 'stale' | undefined;
            evidence?: {
                kind?: string | undefined;
                status?: number | undefined;
                headers?: Record<string, string> | undefined;
                code?: string | undefined;
                message?: string | undefined;
                providerLimitId?: string | undefined;
                observedAtMs?: number | undefined;
            } | undefined;
            recoveryCredits?: {
                availableCount: number;
                credits: {
                    kind: 'unknown' | 'usage_limit_reset' | 'rate_limit_reset' | 'quota_reset';
                    status: 'unknown' | 'available' | 'redeeming' | 'redeemed' | 'expired' | 'unavailable';
                    id?: string | undefined;
                    providerResetType?: string | undefined;
                    appliesToProviderLimitId?: string | null | undefined;
                    grantedAtMs?: number | null | undefined;
                    expiresAtMs?: number | null | undefined;
                    redeemStartedAtMs?: number | null | undefined;
                    redeemedAtMs?: number | null | undefined;
                    title?: string | null | undefined;
                    description?: string | null | undefined;
                }[];
                totalCount?: number | undefined;
                nextExpiresAtMs?: number | null | undefined;
                source?: 'unknown' | 'provider_api' | 'background_fetch' | 'runtime_event' | 'runtime_probe' | 'in_band_snapshot' | 'in_band_provider_snapshot' | 'manual_refresh' | 'user_probe' | 'cached' | undefined;
                confidence?: 'unknown' | 'exact' | 'derived' | 'estimated' | 'stale' | undefined;
            } | undefined;
            subscription?: {
                status: 'unavailable' | 'subscribed' | 'none';
                renewal: 'unknown' | 'on' | 'off';
                observedAtMs: number;
                staleAfterMs: number;
                currentPeriodStartAtMs?: number | undefined;
                currentPeriodEndAtMs?: number | undefined;
                lastRefreshError?: {
                    observedAtMs: number;
                    code: 'network' | 'malformed' | 'provider_backoff' | 'auth_failure' | 'missing_auth';
                    status?: number | undefined;
                } | undefined;
            } | undefined;
        } | null;
        receipt: {
            [x: string]: unknown;
            idempotencyKey: string;
            status: 'consumed' | 'already_consumed' | 'not_available' | 'nothing_to_reset' | 'unknown_after_timeout';
            providerCreditId?: string | undefined;
        };
    } | {
        [x: string]: unknown;
        ok: false;
        error: string;
        errorCode: string;
        receipt?: {
            [x: string]: unknown;
            idempotencyKey: string;
            status: 'consumed' | 'already_consumed' | 'not_available' | 'nothing_to_reset' | 'unknown_after_timeout';
            providerCreditId?: string | undefined;
        } | undefined;
    };
    readonly "connectedServices.quota.refresh": {
        applied: true;
    };
    readonly "connectedServices.identityPrivacy.set": {
        applied: true;
    };
};
