// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.

import type { JsonValue } from './strictJsonValue.generated.js';

export type CurrentUiContextActionInputById = {
    readonly "ui.current_context.read": Record<string, never>;
    readonly "ui.current_context.command.invoke": {
        commandId: string;
    };
};
export type CurrentUiContextActionResultById = {
    readonly "ui.current_context.read": {
        navigation: {
            area: string;
            screen: string;
            title?: string | undefined;
            presentation?: 'screen' | 'modal' | 'pane' | undefined;
        };
        commands: {
            id: string;
            title: string;
            description?: string | undefined;
        }[];
        entity?: {
            kind: string;
            label: string;
            summary?: string | undefined;
            reference?: JsonValue | undefined;
        } | undefined;
        detail?: JsonValue | undefined;
    };
    readonly "ui.current_context.command.invoke": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
};
