// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.

import type { JsonValue } from './strictJsonValue.generated.js';

export type DaemonAdminActionInputById = {
    readonly "daemon.promptAssets.discover": {
        [x: string]: unknown;
        assetTypeId: string;
        scope: 'user' | 'project';
        directory?: string | null | undefined;
    };
    readonly "daemon.promptAssets.delete": {
        [x: string]: unknown;
        assetTypeId: string;
        scope: 'user' | 'project';
        externalRef: Record<string, unknown>;
        directory?: string | null | undefined;
        previewOnly?: boolean | undefined;
        expectedDigest?: string | null | undefined;
    };
    readonly "daemon.promptRegistry.scanSource": {
        [x: string]: unknown;
        sourceId: string;
        configuredSources?: {
            [x: string]: unknown;
            id: string;
            adapterId: string;
            title: string;
            enabled?: boolean | undefined;
            config?: Record<string, unknown> | undefined;
        }[] | undefined;
        query?: string | null | undefined;
    };
    readonly "daemon.promptRegistry.install": {
        [x: string]: unknown;
        sourceId: string;
        itemId: string;
        installTarget: {
            [x: string]: unknown;
            assetTypeId: string;
            scope: 'user' | 'project';
            targetName: string;
            directory?: string | undefined;
            installMode?: 'copy' | 'symlink' | undefined;
        };
        configuredSources?: {
            [x: string]: unknown;
            id: string;
            adapterId: string;
            title: string;
            enabled?: boolean | undefined;
            config?: Record<string, unknown> | undefined;
        }[] | undefined;
        previewOnly?: boolean | undefined;
        expectedDigest?: string | null | undefined;
    };
    readonly "daemon.filesystem.readFile": {
        [x: string]: unknown;
        path: string;
    };
    readonly "daemon.filesystem.writeFile": {
        [x: string]: unknown;
        path: string;
        content: string;
        expectedHash?: string | null | undefined;
    };
    readonly "daemon.filesystem.listDirectory": {
        [x: string]: unknown;
        path: string;
        includeGitIgnore?: boolean | undefined;
    };
    readonly "daemon.filesystem.getDirectoryTree": {
        [x: string]: unknown;
        path: string;
        maxDepth: number;
    };
    readonly "daemon.filesystem.listRoots": Record<string, never>;
    readonly "daemon.filesystem.browseDirectory": {
        [x: string]: unknown;
        path: string;
        includeFiles?: boolean | undefined;
        includeGitIgnore?: boolean | undefined;
        maxEntries?: number | null | undefined;
    };
    readonly "bugreport.collectDiagnostics": {
        [x: string]: unknown;
    };
    readonly "bugreport.getLogTail": {
        [x: string]: unknown;
        path?: string | undefined;
        maxBytes?: number | undefined;
    };
    readonly "bugreport.uploadArtifact": {
        [x: string]: unknown;
        uploadUrl?: string | undefined;
    };
};
export type DaemonAdminActionResultById = {
    readonly "daemon.promptAssets.discover": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "daemon.promptAssets.delete": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "daemon.promptRegistry.scanSource": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "daemon.promptRegistry.install": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "daemon.filesystem.readFile": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "daemon.filesystem.writeFile": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "daemon.filesystem.listDirectory": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "daemon.filesystem.getDirectoryTree": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "daemon.filesystem.listRoots": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "daemon.filesystem.browseDirectory": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "bugreport.collectDiagnostics": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "bugreport.getLogTail": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "bugreport.uploadArtifact": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
};
