// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.

import type { JSONType } from './pluginActionDtoSupport.generated.js';

export type DevicesSimulatorActionInputById = {
    readonly "devices.simulator.list": {
        type: 'simulator.devices.list';
    } & {
        [x: string]: unknown;
        type: 'simulator.devices.list';
    };
    readonly "devices.simulator.stream.keyframe": {
        simulatorId: string;
        type: 'simulator.keyframe.request';
        streamId: string;
        sourceId: string;
        control: {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'tap';
            x: number;
            y: number;
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'long_press';
            x: number;
            y: number;
            leaseId?: string | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'swipe';
            fromX: number;
            fromY: number;
            toX: number;
            toY: number;
            leaseId?: string | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'drag';
            fromX: number;
            fromY: number;
            toX: number;
            toY: number;
            leaseId?: string | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'pinch';
            centerX: number;
            centerY: number;
            startDistance: number;
            endDistance: number;
            leaseId?: string | undefined;
            angle?: number | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'rotate';
            centerX: number;
            centerY: number;
            radius: number;
            startAngle: number;
            endAngle: number;
            leaseId?: string | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'keyboard_text';
            text: string;
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'keyboard_key';
            key: string;
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'hardware_button';
            button: string;
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'orientation';
            orientation: 'portrait' | 'portraitUpsideDown' | 'landscapeLeft' | 'landscapeRight';
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'request_keyframe';
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'set_quality';
            leaseId?: string | undefined;
            maxBitrateBps?: number | undefined;
            maxFramesPerSecond?: number | undefined;
            maxWidth?: number | undefined;
            maxHeight?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'pause_capture';
            leaseId?: string | undefined;
            reasonCode?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'resume_capture';
            leaseId?: string | undefined;
        };
    } & {
        [x: string]: unknown;
        type: 'simulator.keyframe.request';
        control: {
            [x: string]: unknown;
            kind: 'request_keyframe';
        };
    };
    readonly "devices.simulator.stream.snapshot": {
        simulatorId: string;
        type: 'simulator.snapshot.request';
        streamId: string;
        sourceId: string;
        eventId: string;
    } & {
        [x: string]: unknown;
        type: 'simulator.snapshot.request';
    };
    readonly "devices.simulator.stream.quality.set": {
        simulatorId: string;
        type: 'simulator.quality.set';
        streamId: string;
        sourceId: string;
        control: {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'tap';
            x: number;
            y: number;
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'long_press';
            x: number;
            y: number;
            leaseId?: string | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'swipe';
            fromX: number;
            fromY: number;
            toX: number;
            toY: number;
            leaseId?: string | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'drag';
            fromX: number;
            fromY: number;
            toX: number;
            toY: number;
            leaseId?: string | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'pinch';
            centerX: number;
            centerY: number;
            startDistance: number;
            endDistance: number;
            leaseId?: string | undefined;
            angle?: number | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'rotate';
            centerX: number;
            centerY: number;
            radius: number;
            startAngle: number;
            endAngle: number;
            leaseId?: string | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'keyboard_text';
            text: string;
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'keyboard_key';
            key: string;
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'hardware_button';
            button: string;
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'orientation';
            orientation: 'portrait' | 'portraitUpsideDown' | 'landscapeLeft' | 'landscapeRight';
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'request_keyframe';
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'set_quality';
            leaseId?: string | undefined;
            maxBitrateBps?: number | undefined;
            maxFramesPerSecond?: number | undefined;
            maxWidth?: number | undefined;
            maxHeight?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'pause_capture';
            leaseId?: string | undefined;
            reasonCode?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'resume_capture';
            leaseId?: string | undefined;
        };
    } & {
        [x: string]: unknown;
        type: 'simulator.quality.set';
        control: {
            [x: string]: unknown;
            kind: 'set_quality';
        };
    };
    readonly "devices.simulator.stream.fps.set": {
        [x: string]: unknown;
        simulatorId: string;
        streamId: string;
        sourceId: string;
        value: number;
    };
    readonly "devices.simulator.stream.scale.set": {
        [x: string]: unknown;
        simulatorId: string;
        streamId: string;
        sourceId: string;
        value: number;
    };
    readonly "devices.simulator.lease.acquire": {
        simulatorId: string;
        type: 'simulator.lease.acquire';
        streamId: string;
        sourceId: string;
        viewerId: string;
    } & {
        [x: string]: unknown;
        type: 'simulator.lease.acquire';
    };
    readonly "devices.simulator.lease.renew": {
        simulatorId: string;
        type: 'simulator.lease.renew';
        streamId: string;
        sourceId: string;
        leaseId: string;
        viewerId: string;
    } & {
        [x: string]: unknown;
        type: 'simulator.lease.renew';
    };
    readonly "devices.simulator.lease.release": {
        simulatorId: string;
        type: 'simulator.lease.release';
        streamId: string;
        sourceId: string;
        leaseId: string;
    } & {
        [x: string]: unknown;
        type: 'simulator.lease.release';
    };
    readonly "devices.simulator.input.tap": {
        type: 'simulator.control.send';
        control: {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'tap';
            x: number;
            y: number;
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'long_press';
            x: number;
            y: number;
            leaseId?: string | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'swipe';
            fromX: number;
            fromY: number;
            toX: number;
            toY: number;
            leaseId?: string | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'drag';
            fromX: number;
            fromY: number;
            toX: number;
            toY: number;
            leaseId?: string | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'pinch';
            centerX: number;
            centerY: number;
            startDistance: number;
            endDistance: number;
            leaseId?: string | undefined;
            angle?: number | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'rotate';
            centerX: number;
            centerY: number;
            radius: number;
            startAngle: number;
            endAngle: number;
            leaseId?: string | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'keyboard_text';
            text: string;
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'keyboard_key';
            key: string;
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'hardware_button';
            button: string;
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'orientation';
            orientation: 'portrait' | 'portraitUpsideDown' | 'landscapeLeft' | 'landscapeRight';
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'request_keyframe';
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'set_quality';
            leaseId?: string | undefined;
            maxBitrateBps?: number | undefined;
            maxFramesPerSecond?: number | undefined;
            maxWidth?: number | undefined;
            maxHeight?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'pause_capture';
            leaseId?: string | undefined;
            reasonCode?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'resume_capture';
            leaseId?: string | undefined;
        };
    } & {
        [x: string]: unknown;
        type: 'simulator.control.send';
        control: {
            [x: string]: unknown;
            kind: 'tap';
        };
    };
    readonly "devices.simulator.input.swipe": {
        type: 'simulator.control.send';
        control: {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'tap';
            x: number;
            y: number;
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'long_press';
            x: number;
            y: number;
            leaseId?: string | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'swipe';
            fromX: number;
            fromY: number;
            toX: number;
            toY: number;
            leaseId?: string | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'drag';
            fromX: number;
            fromY: number;
            toX: number;
            toY: number;
            leaseId?: string | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'pinch';
            centerX: number;
            centerY: number;
            startDistance: number;
            endDistance: number;
            leaseId?: string | undefined;
            angle?: number | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'rotate';
            centerX: number;
            centerY: number;
            radius: number;
            startAngle: number;
            endAngle: number;
            leaseId?: string | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'keyboard_text';
            text: string;
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'keyboard_key';
            key: string;
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'hardware_button';
            button: string;
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'orientation';
            orientation: 'portrait' | 'portraitUpsideDown' | 'landscapeLeft' | 'landscapeRight';
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'request_keyframe';
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'set_quality';
            leaseId?: string | undefined;
            maxBitrateBps?: number | undefined;
            maxFramesPerSecond?: number | undefined;
            maxWidth?: number | undefined;
            maxHeight?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'pause_capture';
            leaseId?: string | undefined;
            reasonCode?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'resume_capture';
            leaseId?: string | undefined;
        };
    } & {
        [x: string]: unknown;
        type: 'simulator.control.send';
        control: {
            [x: string]: unknown;
            kind: 'swipe';
        };
    };
    readonly "devices.simulator.input.text": {
        type: 'simulator.control.send';
        control: {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'tap';
            x: number;
            y: number;
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'long_press';
            x: number;
            y: number;
            leaseId?: string | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'swipe';
            fromX: number;
            fromY: number;
            toX: number;
            toY: number;
            leaseId?: string | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'drag';
            fromX: number;
            fromY: number;
            toX: number;
            toY: number;
            leaseId?: string | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'pinch';
            centerX: number;
            centerY: number;
            startDistance: number;
            endDistance: number;
            leaseId?: string | undefined;
            angle?: number | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'rotate';
            centerX: number;
            centerY: number;
            radius: number;
            startAngle: number;
            endAngle: number;
            leaseId?: string | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'keyboard_text';
            text: string;
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'keyboard_key';
            key: string;
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'hardware_button';
            button: string;
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'orientation';
            orientation: 'portrait' | 'portraitUpsideDown' | 'landscapeLeft' | 'landscapeRight';
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'request_keyframe';
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'set_quality';
            leaseId?: string | undefined;
            maxBitrateBps?: number | undefined;
            maxFramesPerSecond?: number | undefined;
            maxWidth?: number | undefined;
            maxHeight?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'pause_capture';
            leaseId?: string | undefined;
            reasonCode?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'resume_capture';
            leaseId?: string | undefined;
        };
    } & {
        [x: string]: unknown;
        type: 'simulator.control.send';
        control: {
            [x: string]: unknown;
            kind: 'keyboard_text';
        };
    };
    readonly "devices.simulator.input.key": {
        type: 'simulator.control.send';
        control: {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'tap';
            x: number;
            y: number;
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'long_press';
            x: number;
            y: number;
            leaseId?: string | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'swipe';
            fromX: number;
            fromY: number;
            toX: number;
            toY: number;
            leaseId?: string | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'drag';
            fromX: number;
            fromY: number;
            toX: number;
            toY: number;
            leaseId?: string | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'pinch';
            centerX: number;
            centerY: number;
            startDistance: number;
            endDistance: number;
            leaseId?: string | undefined;
            angle?: number | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'rotate';
            centerX: number;
            centerY: number;
            radius: number;
            startAngle: number;
            endAngle: number;
            leaseId?: string | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'keyboard_text';
            text: string;
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'keyboard_key';
            key: string;
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'hardware_button';
            button: string;
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'orientation';
            orientation: 'portrait' | 'portraitUpsideDown' | 'landscapeLeft' | 'landscapeRight';
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'request_keyframe';
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'set_quality';
            leaseId?: string | undefined;
            maxBitrateBps?: number | undefined;
            maxFramesPerSecond?: number | undefined;
            maxWidth?: number | undefined;
            maxHeight?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'pause_capture';
            leaseId?: string | undefined;
            reasonCode?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'resume_capture';
            leaseId?: string | undefined;
        };
    } & {
        [x: string]: unknown;
        type: 'simulator.control.send';
        control: {
            [x: string]: unknown;
            kind: 'keyboard_key';
        };
    };
    readonly "devices.simulator.input.button": {
        type: 'simulator.control.send';
        control: {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'tap';
            x: number;
            y: number;
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'long_press';
            x: number;
            y: number;
            leaseId?: string | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'swipe';
            fromX: number;
            fromY: number;
            toX: number;
            toY: number;
            leaseId?: string | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'drag';
            fromX: number;
            fromY: number;
            toX: number;
            toY: number;
            leaseId?: string | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'pinch';
            centerX: number;
            centerY: number;
            startDistance: number;
            endDistance: number;
            leaseId?: string | undefined;
            angle?: number | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'rotate';
            centerX: number;
            centerY: number;
            radius: number;
            startAngle: number;
            endAngle: number;
            leaseId?: string | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'keyboard_text';
            text: string;
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'keyboard_key';
            key: string;
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'hardware_button';
            button: string;
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'orientation';
            orientation: 'portrait' | 'portraitUpsideDown' | 'landscapeLeft' | 'landscapeRight';
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'request_keyframe';
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'set_quality';
            leaseId?: string | undefined;
            maxBitrateBps?: number | undefined;
            maxFramesPerSecond?: number | undefined;
            maxWidth?: number | undefined;
            maxHeight?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'pause_capture';
            leaseId?: string | undefined;
            reasonCode?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'resume_capture';
            leaseId?: string | undefined;
        };
    } & {
        [x: string]: unknown;
        type: 'simulator.control.send';
        control: {
            [x: string]: unknown;
            kind: 'hardware_button';
        };
    };
    readonly "devices.simulator.input.pinch": {
        type: 'simulator.control.send';
        control: {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'tap';
            x: number;
            y: number;
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'long_press';
            x: number;
            y: number;
            leaseId?: string | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'swipe';
            fromX: number;
            fromY: number;
            toX: number;
            toY: number;
            leaseId?: string | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'drag';
            fromX: number;
            fromY: number;
            toX: number;
            toY: number;
            leaseId?: string | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'pinch';
            centerX: number;
            centerY: number;
            startDistance: number;
            endDistance: number;
            leaseId?: string | undefined;
            angle?: number | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'rotate';
            centerX: number;
            centerY: number;
            radius: number;
            startAngle: number;
            endAngle: number;
            leaseId?: string | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'keyboard_text';
            text: string;
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'keyboard_key';
            key: string;
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'hardware_button';
            button: string;
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'orientation';
            orientation: 'portrait' | 'portraitUpsideDown' | 'landscapeLeft' | 'landscapeRight';
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'request_keyframe';
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'set_quality';
            leaseId?: string | undefined;
            maxBitrateBps?: number | undefined;
            maxFramesPerSecond?: number | undefined;
            maxWidth?: number | undefined;
            maxHeight?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'pause_capture';
            leaseId?: string | undefined;
            reasonCode?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'resume_capture';
            leaseId?: string | undefined;
        };
    } & {
        [x: string]: unknown;
        type: 'simulator.control.send';
        control: {
            [x: string]: unknown;
            kind: 'pinch';
        };
    };
    readonly "devices.simulator.input.rotate": {
        type: 'simulator.control.send';
        control: {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'tap';
            x: number;
            y: number;
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'long_press';
            x: number;
            y: number;
            leaseId?: string | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'swipe';
            fromX: number;
            fromY: number;
            toX: number;
            toY: number;
            leaseId?: string | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'drag';
            fromX: number;
            fromY: number;
            toX: number;
            toY: number;
            leaseId?: string | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'pinch';
            centerX: number;
            centerY: number;
            startDistance: number;
            endDistance: number;
            leaseId?: string | undefined;
            angle?: number | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'rotate';
            centerX: number;
            centerY: number;
            radius: number;
            startAngle: number;
            endAngle: number;
            leaseId?: string | undefined;
            durationMs?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'keyboard_text';
            text: string;
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'keyboard_key';
            key: string;
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'hardware_button';
            button: string;
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'orientation';
            orientation: 'portrait' | 'portraitUpsideDown' | 'landscapeLeft' | 'landscapeRight';
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'request_keyframe';
            leaseId?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'set_quality';
            leaseId?: string | undefined;
            maxBitrateBps?: number | undefined;
            maxFramesPerSecond?: number | undefined;
            maxWidth?: number | undefined;
            maxHeight?: number | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'pause_capture';
            leaseId?: string | undefined;
            reasonCode?: string | undefined;
        } | {
            v: 1;
            streamId: string;
            sourceId: string;
            eventId: string;
            kind: 'resume_capture';
            leaseId?: string | undefined;
        };
    } & {
        [x: string]: unknown;
        type: 'simulator.control.send';
        control: {
            [x: string]: unknown;
            kind: 'rotate';
        };
    };
    readonly "devices.simulator.sideband.request": {
        simulatorId: string;
        type: 'simulator.sideband.request';
        kind: 'accessibility_tree' | 'logs' | 'device_config' | 'app_metadata' | 'network_diagnostics' | 'route' | 'capture_health';
    } & {
        [x: string]: unknown;
        type: 'simulator.sideband.request';
    };
};
export type DevicesSimulatorActionResultById = {
    readonly "devices.simulator.list": {
        v: 1;
        machineId: string;
        generatedAt: number;
        refreshState: 'error' | 'idle' | 'refreshing';
        resources: {
            v: 1;
            simulatorId: string;
            platform: 'ios' | 'android';
            deviceId: string;
            displayName: string;
            capture: {
                status: 'available';
                sourceId: string;
                supportedCodecs: ('image.frame.v1' | 'image.mjpeg' | 'h264.avcc')[];
                inputMode: 'none' | 'shared' | 'exclusive';
                supportedInputKinds?: ('tap' | 'long_press' | 'swipe' | 'drag' | 'pinch' | 'rotate' | 'keyboard_text' | 'keyboard_key' | 'hardware_button' | 'orientation')[] | undefined;
                streamControls?: {
                    requestKeyframe: boolean;
                    snapshot: boolean;
                    setQuality: boolean;
                    setFps: boolean;
                    setScale: boolean;
                } | undefined;
            } | {
                status: 'unavailable';
                reasonCode: string;
                sourceId?: string | undefined;
            };
            appId?: string | undefined;
            unavailableReason?: string | undefined;
        }[];
        diagnostics: Record<string, unknown>[];
    };
    readonly "devices.simulator.stream.keyframe": {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'accepted';
        lease?: {
            [x: string]: unknown;
            v: 1;
            leaseId: string;
            streamId: string;
            sourceId: string;
            holderId: string;
            mode: 'exclusive';
            acquiredAtMs: number;
            expiresAtMs: number;
        } | undefined;
        sideband?: {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'accessibility_tree';
            tree: JSONType;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'logs';
            level: 'error' | 'debug' | 'info' | 'warn';
            message: string;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'device_config';
            config: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'app_metadata';
            metadata: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'network_diagnostics';
            diagnostics: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'route';
            route: string;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'capture_health';
            status: 'available' | 'unavailable' | 'starting' | 'degraded';
            reasonCode?: string | undefined;
        } | undefined;
        stream?: {
            v: 1;
            streamId: string;
            sourceId: string;
            streamFamily: string;
            routeKind: 'loopback_direct' | 'server_relay';
            sourceMachineId: string;
            targetMachineId: string;
            expiresAtMs?: number | undefined;
        } | undefined;
    } | {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'rejected';
        reasonCode: string;
    } | {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'unavailable';
        reasonCode: string;
    };
    readonly "devices.simulator.stream.snapshot": {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'accepted';
        lease?: {
            [x: string]: unknown;
            v: 1;
            leaseId: string;
            streamId: string;
            sourceId: string;
            holderId: string;
            mode: 'exclusive';
            acquiredAtMs: number;
            expiresAtMs: number;
        } | undefined;
        sideband?: {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'accessibility_tree';
            tree: JSONType;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'logs';
            level: 'error' | 'debug' | 'info' | 'warn';
            message: string;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'device_config';
            config: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'app_metadata';
            metadata: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'network_diagnostics';
            diagnostics: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'route';
            route: string;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'capture_health';
            status: 'available' | 'unavailable' | 'starting' | 'degraded';
            reasonCode?: string | undefined;
        } | undefined;
        stream?: {
            v: 1;
            streamId: string;
            sourceId: string;
            streamFamily: string;
            routeKind: 'loopback_direct' | 'server_relay';
            sourceMachineId: string;
            targetMachineId: string;
            expiresAtMs?: number | undefined;
        } | undefined;
    } | {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'rejected';
        reasonCode: string;
    } | {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'unavailable';
        reasonCode: string;
    };
    readonly "devices.simulator.stream.quality.set": {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'accepted';
        lease?: {
            [x: string]: unknown;
            v: 1;
            leaseId: string;
            streamId: string;
            sourceId: string;
            holderId: string;
            mode: 'exclusive';
            acquiredAtMs: number;
            expiresAtMs: number;
        } | undefined;
        sideband?: {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'accessibility_tree';
            tree: JSONType;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'logs';
            level: 'error' | 'debug' | 'info' | 'warn';
            message: string;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'device_config';
            config: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'app_metadata';
            metadata: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'network_diagnostics';
            diagnostics: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'route';
            route: string;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'capture_health';
            status: 'available' | 'unavailable' | 'starting' | 'degraded';
            reasonCode?: string | undefined;
        } | undefined;
        stream?: {
            v: 1;
            streamId: string;
            sourceId: string;
            streamFamily: string;
            routeKind: 'loopback_direct' | 'server_relay';
            sourceMachineId: string;
            targetMachineId: string;
            expiresAtMs?: number | undefined;
        } | undefined;
    } | {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'rejected';
        reasonCode: string;
    } | {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'unavailable';
        reasonCode: string;
    };
    readonly "devices.simulator.stream.fps.set": {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'accepted';
        lease?: {
            [x: string]: unknown;
            v: 1;
            leaseId: string;
            streamId: string;
            sourceId: string;
            holderId: string;
            mode: 'exclusive';
            acquiredAtMs: number;
            expiresAtMs: number;
        } | undefined;
        sideband?: {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'accessibility_tree';
            tree: JSONType;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'logs';
            level: 'error' | 'debug' | 'info' | 'warn';
            message: string;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'device_config';
            config: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'app_metadata';
            metadata: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'network_diagnostics';
            diagnostics: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'route';
            route: string;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'capture_health';
            status: 'available' | 'unavailable' | 'starting' | 'degraded';
            reasonCode?: string | undefined;
        } | undefined;
        stream?: {
            v: 1;
            streamId: string;
            sourceId: string;
            streamFamily: string;
            routeKind: 'loopback_direct' | 'server_relay';
            sourceMachineId: string;
            targetMachineId: string;
            expiresAtMs?: number | undefined;
        } | undefined;
    } | {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'rejected';
        reasonCode: string;
    } | {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'unavailable';
        reasonCode: string;
    };
    readonly "devices.simulator.stream.scale.set": {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'accepted';
        lease?: {
            [x: string]: unknown;
            v: 1;
            leaseId: string;
            streamId: string;
            sourceId: string;
            holderId: string;
            mode: 'exclusive';
            acquiredAtMs: number;
            expiresAtMs: number;
        } | undefined;
        sideband?: {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'accessibility_tree';
            tree: JSONType;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'logs';
            level: 'error' | 'debug' | 'info' | 'warn';
            message: string;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'device_config';
            config: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'app_metadata';
            metadata: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'network_diagnostics';
            diagnostics: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'route';
            route: string;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'capture_health';
            status: 'available' | 'unavailable' | 'starting' | 'degraded';
            reasonCode?: string | undefined;
        } | undefined;
        stream?: {
            v: 1;
            streamId: string;
            sourceId: string;
            streamFamily: string;
            routeKind: 'loopback_direct' | 'server_relay';
            sourceMachineId: string;
            targetMachineId: string;
            expiresAtMs?: number | undefined;
        } | undefined;
    } | {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'rejected';
        reasonCode: string;
    } | {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'unavailable';
        reasonCode: string;
    };
    readonly "devices.simulator.lease.acquire": {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'accepted';
        lease?: {
            [x: string]: unknown;
            v: 1;
            leaseId: string;
            streamId: string;
            sourceId: string;
            holderId: string;
            mode: 'exclusive';
            acquiredAtMs: number;
            expiresAtMs: number;
        } | undefined;
        sideband?: {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'accessibility_tree';
            tree: JSONType;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'logs';
            level: 'error' | 'debug' | 'info' | 'warn';
            message: string;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'device_config';
            config: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'app_metadata';
            metadata: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'network_diagnostics';
            diagnostics: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'route';
            route: string;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'capture_health';
            status: 'available' | 'unavailable' | 'starting' | 'degraded';
            reasonCode?: string | undefined;
        } | undefined;
        stream?: {
            v: 1;
            streamId: string;
            sourceId: string;
            streamFamily: string;
            routeKind: 'loopback_direct' | 'server_relay';
            sourceMachineId: string;
            targetMachineId: string;
            expiresAtMs?: number | undefined;
        } | undefined;
    } | {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'rejected';
        reasonCode: string;
    } | {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'unavailable';
        reasonCode: string;
    };
    readonly "devices.simulator.lease.renew": {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'accepted';
        lease?: {
            [x: string]: unknown;
            v: 1;
            leaseId: string;
            streamId: string;
            sourceId: string;
            holderId: string;
            mode: 'exclusive';
            acquiredAtMs: number;
            expiresAtMs: number;
        } | undefined;
        sideband?: {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'accessibility_tree';
            tree: JSONType;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'logs';
            level: 'error' | 'debug' | 'info' | 'warn';
            message: string;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'device_config';
            config: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'app_metadata';
            metadata: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'network_diagnostics';
            diagnostics: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'route';
            route: string;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'capture_health';
            status: 'available' | 'unavailable' | 'starting' | 'degraded';
            reasonCode?: string | undefined;
        } | undefined;
        stream?: {
            v: 1;
            streamId: string;
            sourceId: string;
            streamFamily: string;
            routeKind: 'loopback_direct' | 'server_relay';
            sourceMachineId: string;
            targetMachineId: string;
            expiresAtMs?: number | undefined;
        } | undefined;
    } | {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'rejected';
        reasonCode: string;
    } | {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'unavailable';
        reasonCode: string;
    };
    readonly "devices.simulator.lease.release": {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'accepted';
        lease?: {
            [x: string]: unknown;
            v: 1;
            leaseId: string;
            streamId: string;
            sourceId: string;
            holderId: string;
            mode: 'exclusive';
            acquiredAtMs: number;
            expiresAtMs: number;
        } | undefined;
        sideband?: {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'accessibility_tree';
            tree: JSONType;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'logs';
            level: 'error' | 'debug' | 'info' | 'warn';
            message: string;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'device_config';
            config: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'app_metadata';
            metadata: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'network_diagnostics';
            diagnostics: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'route';
            route: string;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'capture_health';
            status: 'available' | 'unavailable' | 'starting' | 'degraded';
            reasonCode?: string | undefined;
        } | undefined;
        stream?: {
            v: 1;
            streamId: string;
            sourceId: string;
            streamFamily: string;
            routeKind: 'loopback_direct' | 'server_relay';
            sourceMachineId: string;
            targetMachineId: string;
            expiresAtMs?: number | undefined;
        } | undefined;
    } | {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'rejected';
        reasonCode: string;
    } | {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'unavailable';
        reasonCode: string;
    };
    readonly "devices.simulator.input.tap": {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'accepted';
        lease?: {
            [x: string]: unknown;
            v: 1;
            leaseId: string;
            streamId: string;
            sourceId: string;
            holderId: string;
            mode: 'exclusive';
            acquiredAtMs: number;
            expiresAtMs: number;
        } | undefined;
        sideband?: {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'accessibility_tree';
            tree: JSONType;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'logs';
            level: 'error' | 'debug' | 'info' | 'warn';
            message: string;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'device_config';
            config: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'app_metadata';
            metadata: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'network_diagnostics';
            diagnostics: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'route';
            route: string;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'capture_health';
            status: 'available' | 'unavailable' | 'starting' | 'degraded';
            reasonCode?: string | undefined;
        } | undefined;
        stream?: {
            v: 1;
            streamId: string;
            sourceId: string;
            streamFamily: string;
            routeKind: 'loopback_direct' | 'server_relay';
            sourceMachineId: string;
            targetMachineId: string;
            expiresAtMs?: number | undefined;
        } | undefined;
    } | {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'rejected';
        reasonCode: string;
    } | {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'unavailable';
        reasonCode: string;
    };
    readonly "devices.simulator.input.swipe": {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'accepted';
        lease?: {
            [x: string]: unknown;
            v: 1;
            leaseId: string;
            streamId: string;
            sourceId: string;
            holderId: string;
            mode: 'exclusive';
            acquiredAtMs: number;
            expiresAtMs: number;
        } | undefined;
        sideband?: {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'accessibility_tree';
            tree: JSONType;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'logs';
            level: 'error' | 'debug' | 'info' | 'warn';
            message: string;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'device_config';
            config: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'app_metadata';
            metadata: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'network_diagnostics';
            diagnostics: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'route';
            route: string;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'capture_health';
            status: 'available' | 'unavailable' | 'starting' | 'degraded';
            reasonCode?: string | undefined;
        } | undefined;
        stream?: {
            v: 1;
            streamId: string;
            sourceId: string;
            streamFamily: string;
            routeKind: 'loopback_direct' | 'server_relay';
            sourceMachineId: string;
            targetMachineId: string;
            expiresAtMs?: number | undefined;
        } | undefined;
    } | {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'rejected';
        reasonCode: string;
    } | {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'unavailable';
        reasonCode: string;
    };
    readonly "devices.simulator.input.text": {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'accepted';
        lease?: {
            [x: string]: unknown;
            v: 1;
            leaseId: string;
            streamId: string;
            sourceId: string;
            holderId: string;
            mode: 'exclusive';
            acquiredAtMs: number;
            expiresAtMs: number;
        } | undefined;
        sideband?: {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'accessibility_tree';
            tree: JSONType;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'logs';
            level: 'error' | 'debug' | 'info' | 'warn';
            message: string;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'device_config';
            config: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'app_metadata';
            metadata: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'network_diagnostics';
            diagnostics: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'route';
            route: string;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'capture_health';
            status: 'available' | 'unavailable' | 'starting' | 'degraded';
            reasonCode?: string | undefined;
        } | undefined;
        stream?: {
            v: 1;
            streamId: string;
            sourceId: string;
            streamFamily: string;
            routeKind: 'loopback_direct' | 'server_relay';
            sourceMachineId: string;
            targetMachineId: string;
            expiresAtMs?: number | undefined;
        } | undefined;
    } | {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'rejected';
        reasonCode: string;
    } | {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'unavailable';
        reasonCode: string;
    };
    readonly "devices.simulator.input.key": {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'accepted';
        lease?: {
            [x: string]: unknown;
            v: 1;
            leaseId: string;
            streamId: string;
            sourceId: string;
            holderId: string;
            mode: 'exclusive';
            acquiredAtMs: number;
            expiresAtMs: number;
        } | undefined;
        sideband?: {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'accessibility_tree';
            tree: JSONType;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'logs';
            level: 'error' | 'debug' | 'info' | 'warn';
            message: string;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'device_config';
            config: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'app_metadata';
            metadata: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'network_diagnostics';
            diagnostics: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'route';
            route: string;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'capture_health';
            status: 'available' | 'unavailable' | 'starting' | 'degraded';
            reasonCode?: string | undefined;
        } | undefined;
        stream?: {
            v: 1;
            streamId: string;
            sourceId: string;
            streamFamily: string;
            routeKind: 'loopback_direct' | 'server_relay';
            sourceMachineId: string;
            targetMachineId: string;
            expiresAtMs?: number | undefined;
        } | undefined;
    } | {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'rejected';
        reasonCode: string;
    } | {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'unavailable';
        reasonCode: string;
    };
    readonly "devices.simulator.input.button": {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'accepted';
        lease?: {
            [x: string]: unknown;
            v: 1;
            leaseId: string;
            streamId: string;
            sourceId: string;
            holderId: string;
            mode: 'exclusive';
            acquiredAtMs: number;
            expiresAtMs: number;
        } | undefined;
        sideband?: {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'accessibility_tree';
            tree: JSONType;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'logs';
            level: 'error' | 'debug' | 'info' | 'warn';
            message: string;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'device_config';
            config: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'app_metadata';
            metadata: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'network_diagnostics';
            diagnostics: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'route';
            route: string;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'capture_health';
            status: 'available' | 'unavailable' | 'starting' | 'degraded';
            reasonCode?: string | undefined;
        } | undefined;
        stream?: {
            v: 1;
            streamId: string;
            sourceId: string;
            streamFamily: string;
            routeKind: 'loopback_direct' | 'server_relay';
            sourceMachineId: string;
            targetMachineId: string;
            expiresAtMs?: number | undefined;
        } | undefined;
    } | {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'rejected';
        reasonCode: string;
    } | {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'unavailable';
        reasonCode: string;
    };
    readonly "devices.simulator.input.pinch": {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'accepted';
        lease?: {
            [x: string]: unknown;
            v: 1;
            leaseId: string;
            streamId: string;
            sourceId: string;
            holderId: string;
            mode: 'exclusive';
            acquiredAtMs: number;
            expiresAtMs: number;
        } | undefined;
        sideband?: {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'accessibility_tree';
            tree: JSONType;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'logs';
            level: 'error' | 'debug' | 'info' | 'warn';
            message: string;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'device_config';
            config: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'app_metadata';
            metadata: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'network_diagnostics';
            diagnostics: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'route';
            route: string;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'capture_health';
            status: 'available' | 'unavailable' | 'starting' | 'degraded';
            reasonCode?: string | undefined;
        } | undefined;
        stream?: {
            v: 1;
            streamId: string;
            sourceId: string;
            streamFamily: string;
            routeKind: 'loopback_direct' | 'server_relay';
            sourceMachineId: string;
            targetMachineId: string;
            expiresAtMs?: number | undefined;
        } | undefined;
    } | {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'rejected';
        reasonCode: string;
    } | {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'unavailable';
        reasonCode: string;
    };
    readonly "devices.simulator.input.rotate": {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'accepted';
        lease?: {
            [x: string]: unknown;
            v: 1;
            leaseId: string;
            streamId: string;
            sourceId: string;
            holderId: string;
            mode: 'exclusive';
            acquiredAtMs: number;
            expiresAtMs: number;
        } | undefined;
        sideband?: {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'accessibility_tree';
            tree: JSONType;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'logs';
            level: 'error' | 'debug' | 'info' | 'warn';
            message: string;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'device_config';
            config: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'app_metadata';
            metadata: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'network_diagnostics';
            diagnostics: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'route';
            route: string;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'capture_health';
            status: 'available' | 'unavailable' | 'starting' | 'degraded';
            reasonCode?: string | undefined;
        } | undefined;
        stream?: {
            v: 1;
            streamId: string;
            sourceId: string;
            streamFamily: string;
            routeKind: 'loopback_direct' | 'server_relay';
            sourceMachineId: string;
            targetMachineId: string;
            expiresAtMs?: number | undefined;
        } | undefined;
    } | {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'rejected';
        reasonCode: string;
    } | {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'unavailable';
        reasonCode: string;
    };
    readonly "devices.simulator.sideband.request": {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'accepted';
        lease?: {
            [x: string]: unknown;
            v: 1;
            leaseId: string;
            streamId: string;
            sourceId: string;
            holderId: string;
            mode: 'exclusive';
            acquiredAtMs: number;
            expiresAtMs: number;
        } | undefined;
        sideband?: {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'accessibility_tree';
            tree: JSONType;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'logs';
            level: 'error' | 'debug' | 'info' | 'warn';
            message: string;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'device_config';
            config: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'app_metadata';
            metadata: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'network_diagnostics';
            diagnostics: Record<string, JSONType>;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'route';
            route: string;
        } | {
            v: 1;
            simulatorId: string;
            emittedAtMs: number;
            kind: 'capture_health';
            status: 'available' | 'unavailable' | 'starting' | 'degraded';
            reasonCode?: string | undefined;
        } | undefined;
        stream?: {
            v: 1;
            streamId: string;
            sourceId: string;
            streamFamily: string;
            routeKind: 'loopback_direct' | 'server_relay';
            sourceMachineId: string;
            targetMachineId: string;
            expiresAtMs?: number | undefined;
        } | undefined;
    } | {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'rejected';
        reasonCode: string;
    } | {
        v: 1;
        eventType: 'simulator.devices.list' | 'simulator.stream.open' | 'simulator.stream.close' | 'simulator.lease.acquire' | 'simulator.lease.release' | 'simulator.lease.renew' | 'simulator.control.send' | 'simulator.sideband.request' | 'simulator.quality.set' | 'simulator.keyframe.request' | 'simulator.snapshot.request';
        diagnostics: Record<string, unknown>[];
        status: 'unavailable';
        reasonCode: string;
    };
};
