// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.


// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
export type ExternalSessionsActionInputById = {
    readonly "sessions.external.materialize.start": {
        request: {
            v: 1;
            idempotencyKey: string;
            sessionId: string;
            plan: 'materialize';
            targetStorageMode: 'external-linked';
            targetRuntimeMode: null;
        };
    };
    readonly "sessions.external.operation.status.get": {
        sessionId: string;
        operationId: string;
        revision: number;
    };
    readonly "sessions.external.operation.cancel": {
        sessionId: string;
        operationId: string;
        revision: number;
    };
    readonly "sessions.external.operation.resume": {
        sessionId: string;
        operationId: string;
        revision: number;
    };
    readonly "sessions.external.operation.retry": {
        sessionId: string;
        operationId: string;
        revision: number;
    };
    readonly "sessions.external.operation.discard": {
        sessionId: string;
        operationId: string;
        revision: number;
    };
    readonly "sessions.external.backgroundFollow.set": {
        sessionId: string;
        enabled: boolean;
    };
    readonly "sessions.external.status.get": {
        sessionId: string;
    };
};
export type ExternalSessionsActionResultById = {
    readonly "sessions.external.materialize.start": {
        ok: true;
        operation: {
            sessionId: string;
            operationId: string;
            revision: number;
        };
    } | {
        ok: false;
        error: {
            code: 'upgrade_required' | 'operation_not_found' | 'operation_conflict' | 'stale_revision' | 'invalid_state' | 'not_allowed' | 'reconciliation_required' | 'source_unavailable' | 'internal_error';
            message: string;
        };
    };
    readonly "sessions.external.operation.status.get": {
        ok: true;
        operation: {
            sessionId: string;
            operationId: string;
            revision: number;
        };
        presentation: {
            v: 1;
            operationId: string;
            revision: number;
            kind: 'materialize' | 'takeover_external_linked' | 'takeover_persisted';
            status: 'reconciliation_required' | 'running' | 'awaiting_user_resume' | 'cancel_requested' | 'cancelled' | 'failed' | 'completed' | 'discarded';
            phase: 'validating' | 'quiescing' | 'staging' | 'importing' | 'final_catch_up' | 'admitting' | 'spawning' | 'finalizing' | 'publishing';
        };
    } | {
        ok: false;
        error: {
            code: 'upgrade_required' | 'operation_not_found' | 'operation_conflict' | 'stale_revision' | 'invalid_state' | 'not_allowed' | 'reconciliation_required' | 'source_unavailable' | 'internal_error';
            message: string;
        };
    };
    readonly "sessions.external.operation.cancel": {
        ok: true;
        operation: {
            sessionId: string;
            operationId: string;
            revision: number;
        };
        presentation: {
            v: 1;
            operationId: string;
            revision: number;
            kind: 'materialize' | 'takeover_external_linked' | 'takeover_persisted';
            status: 'reconciliation_required' | 'running' | 'awaiting_user_resume' | 'cancel_requested' | 'cancelled' | 'failed' | 'completed' | 'discarded';
            phase: 'validating' | 'quiescing' | 'staging' | 'importing' | 'final_catch_up' | 'admitting' | 'spawning' | 'finalizing' | 'publishing';
        };
    } | {
        ok: false;
        error: {
            code: 'upgrade_required' | 'operation_not_found' | 'operation_conflict' | 'stale_revision' | 'invalid_state' | 'not_allowed' | 'reconciliation_required' | 'source_unavailable' | 'internal_error';
            message: string;
        };
    };
    readonly "sessions.external.operation.resume": {
        ok: true;
        operation: {
            sessionId: string;
            operationId: string;
            revision: number;
        };
        presentation: {
            v: 1;
            operationId: string;
            revision: number;
            kind: 'materialize' | 'takeover_external_linked' | 'takeover_persisted';
            status: 'reconciliation_required' | 'running' | 'awaiting_user_resume' | 'cancel_requested' | 'cancelled' | 'failed' | 'completed' | 'discarded';
            phase: 'validating' | 'quiescing' | 'staging' | 'importing' | 'final_catch_up' | 'admitting' | 'spawning' | 'finalizing' | 'publishing';
        };
    } | {
        ok: false;
        error: {
            code: 'upgrade_required' | 'operation_not_found' | 'operation_conflict' | 'stale_revision' | 'invalid_state' | 'not_allowed' | 'reconciliation_required' | 'source_unavailable' | 'internal_error';
            message: string;
        };
    };
    readonly "sessions.external.operation.retry": {
        ok: true;
        operation: {
            sessionId: string;
            operationId: string;
            revision: number;
        };
        presentation: {
            v: 1;
            operationId: string;
            revision: number;
            kind: 'materialize' | 'takeover_external_linked' | 'takeover_persisted';
            status: 'reconciliation_required' | 'running' | 'awaiting_user_resume' | 'cancel_requested' | 'cancelled' | 'failed' | 'completed' | 'discarded';
            phase: 'validating' | 'quiescing' | 'staging' | 'importing' | 'final_catch_up' | 'admitting' | 'spawning' | 'finalizing' | 'publishing';
        };
    } | {
        ok: false;
        error: {
            code: 'upgrade_required' | 'operation_not_found' | 'operation_conflict' | 'stale_revision' | 'invalid_state' | 'not_allowed' | 'reconciliation_required' | 'source_unavailable' | 'internal_error';
            message: string;
        };
    };
    readonly "sessions.external.operation.discard": {
        ok: true;
        operation: {
            sessionId: string;
            operationId: string;
            revision: number;
        };
        presentation: {
            v: 1;
            operationId: string;
            revision: number;
            kind: 'materialize' | 'takeover_external_linked' | 'takeover_persisted';
            status: 'reconciliation_required' | 'running' | 'awaiting_user_resume' | 'cancel_requested' | 'cancelled' | 'failed' | 'completed' | 'discarded';
            phase: 'validating' | 'quiescing' | 'staging' | 'importing' | 'final_catch_up' | 'admitting' | 'spawning' | 'finalizing' | 'publishing';
        };
    } | {
        ok: false;
        error: {
            code: 'upgrade_required' | 'operation_not_found' | 'operation_conflict' | 'stale_revision' | 'invalid_state' | 'not_allowed' | 'reconciliation_required' | 'source_unavailable' | 'internal_error';
            message: string;
        };
    };
    readonly "sessions.external.backgroundFollow.set": {
        ok: true;
        enabled: boolean;
        leaseActive: boolean;
        updatedAtMs: number;
    } | {
        ok: false;
        errorCode: 'internal_error' | 'invalid_request' | 'machine_offline' | 'agent_unavailable' | 'agent_timeout' | 'agent_error';
        error: string;
    };
    readonly "sessions.external.status.get": {
        ok: false;
        errorCode: 'internal_error' | 'invalid_request' | 'machine_offline' | 'agent_unavailable' | 'agent_timeout' | 'agent_error';
        error: string;
    } | {
        ok: true;
        machineOnline: boolean;
        runnerActive: boolean;
        activity: 'unknown' | 'running' | 'active_recently' | 'idle';
        canTakeOverDirect: boolean;
        canTakeOverPersist: boolean;
        canForceStop: boolean;
        lastKnownActivityAtMs?: number | undefined;
    };
};
