// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.


// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
export type IdentityProvidersActionInputById = {
    readonly "identity.providers.list": {
        owner?: {
            kind: 'home';
        } | {
            kind: 'team';
            teamId: string;
        } | undefined;
    };
    readonly "identity.providers.create": {
        displayName: string;
        config: {
            v: 1;
            kind: 'oidc';
            issuer: string;
            clientId: string;
            scopes: string;
            httpTimeoutSeconds: number;
            claims: {
                login: string;
                email: string;
                groups: string;
            };
            allow: {
                usersAllowlist: string[];
                emailDomains: string[];
                groupsAny: string[];
                groupsAll: string[];
            };
            fetchUserInfo: boolean;
            storeRefreshToken: boolean;
            ui: {
                buttonColor: string | null;
                iconHint: string | null;
            };
            clientAuthenticationMethod?: 'client_secret_post' | 'client_secret_basic' | undefined;
        };
        clientSecret: string;
        owner?: {
            kind: 'home';
        } | {
            kind: 'team';
            teamId: string;
        } | undefined;
    };
    readonly "identity.providers.update": {
        id: string;
        expectedRevision: number;
        owner?: {
            kind: 'home';
        } | {
            kind: 'team';
            teamId: string;
        } | undefined;
        displayName?: string | undefined;
        config?: {
            v: 1;
            kind: 'oidc';
            issuer: string;
            clientId: string;
            clientAuthenticationMethod: 'client_secret_post' | 'client_secret_basic';
            scopes: string;
            httpTimeoutSeconds: number;
            claims: {
                login: string;
                email: string;
                groups: string;
            };
            allow: {
                usersAllowlist: string[];
                emailDomains: string[];
                groupsAny: string[];
                groupsAll: string[];
            };
            fetchUserInfo: boolean;
            storeRefreshToken: boolean;
            ui: {
                buttonColor: string | null;
                iconHint: string | null;
            };
        } | undefined;
    };
    readonly "identity.providers.secret.replace": {
        id: string;
        expectedRevision: number;
        clientSecret: string;
        owner?: {
            kind: 'home';
        } | {
            kind: 'team';
            teamId: string;
        } | undefined;
    };
    readonly "identity.providers.validate": {
        id: string;
        expectedRevision: number;
        expectedSecurityRevision: number;
        owner?: {
            kind: 'home';
        } | {
            kind: 'team';
            teamId: string;
        } | undefined;
    };
    readonly "identity.providers.test.start": {
        id: string;
        expectedRevision: number;
        expectedSecurityRevision: number;
        owner?: {
            kind: 'home';
        } | {
            kind: 'team';
            teamId: string;
        } | undefined;
    };
    readonly "identity.providers.test.consume": {
        id: string;
        resultHandle: string;
        owner?: {
            kind: 'home';
        } | {
            kind: 'team';
            teamId: string;
        } | undefined;
    };
    readonly "identity.providers.enable": {
        id: string;
        expectedRevision: number;
        expectedSecurityRevision: number;
        owner?: {
            kind: 'home';
        } | {
            kind: 'team';
            teamId: string;
        } | undefined;
    };
    readonly "identity.providers.disable": {
        id: string;
        expectedRevision: number;
        expectedSecurityRevision: number;
        owner?: {
            kind: 'home';
        } | {
            kind: 'team';
            teamId: string;
        } | undefined;
    };
    readonly "identity.providers.remove.preview": {
        id: string;
        expectedRevision: number;
        owner?: {
            kind: 'home';
        } | {
            kind: 'team';
            teamId: string;
        } | undefined;
    };
    readonly "identity.providers.remove": {
        id: string;
        expectedRevision: number;
        owner?: {
            kind: 'home';
        } | {
            kind: 'team';
            teamId: string;
        } | undefined;
    };
};
export type IdentityProvidersActionResultById = {
    readonly "identity.providers.list": {
        items: ({
            kind: 'oidc';
            config: {
                v: 1;
                kind: 'oidc';
                issuer: string;
                clientId: string;
                clientAuthenticationMethod: 'client_secret_post' | 'client_secret_basic';
                scopes: string;
                httpTimeoutSeconds: number;
                claims: {
                    login: string;
                    email: string;
                    groups: string;
                };
                allow: {
                    usersAllowlist: string[];
                    emailDomains: string[];
                    groupsAny: string[];
                    groupsAll: string[];
                };
                fetchUserInfo: boolean;
                storeRefreshToken: boolean;
                ui: {
                    buttonColor: string | null;
                    iconHint: string | null;
                };
            };
            secret: {
                configured: boolean;
                health: 'configured' | 'missing' | 'unreadable';
            };
            v: 1;
            owner: {
                kind: 'home';
            } | {
                kind: 'team';
                teamId: string;
            };
            id: string;
            displayName: string;
            enabled: boolean;
            firstEnabledAt: number | null;
            securityRevision: number;
            revision: number;
            lastSuccessfulTest: {
                at: number;
                testedSecurityRevision: number;
                current: boolean;
            } | null;
            createdByAccountId: string | null;
            createdAt: number;
            updatedAt: number;
            teamConsumers: {
                team: {
                    id: string;
                    name: string;
                };
                binding: {
                    kind: 'identity_connection';
                    id: string;
                    enabled: boolean;
                };
            }[];
            callbackUrl?: string | undefined;
        } | {
            kind: 'github_app_identity';
            config: {
                v: 1;
                kind: 'github_app_identity';
            };
            githubAppInstallationId: string;
            v: 1;
            owner: {
                kind: 'home';
            } | {
                kind: 'team';
                teamId: string;
            };
            id: string;
            displayName: string;
            enabled: boolean;
            firstEnabledAt: number | null;
            securityRevision: number;
            revision: number;
            lastSuccessfulTest: {
                at: number;
                testedSecurityRevision: number;
                current: boolean;
            } | null;
            createdByAccountId: string | null;
            createdAt: number;
            updatedAt: number;
            teamConsumers: {
                team: {
                    id: string;
                    name: string;
                };
                binding: {
                    kind: 'identity_connection';
                    id: string;
                    enabled: boolean;
                };
            }[];
            callbackUrl?: string | undefined;
        })[];
        unreadableCount: number;
    };
    readonly "identity.providers.create": {
        kind: 'oidc';
        config: {
            v: 1;
            kind: 'oidc';
            issuer: string;
            clientId: string;
            clientAuthenticationMethod: 'client_secret_post' | 'client_secret_basic';
            scopes: string;
            httpTimeoutSeconds: number;
            claims: {
                login: string;
                email: string;
                groups: string;
            };
            allow: {
                usersAllowlist: string[];
                emailDomains: string[];
                groupsAny: string[];
                groupsAll: string[];
            };
            fetchUserInfo: boolean;
            storeRefreshToken: boolean;
            ui: {
                buttonColor: string | null;
                iconHint: string | null;
            };
        };
        secret: {
            configured: boolean;
            health: 'configured' | 'missing' | 'unreadable';
        };
        v: 1;
        owner: {
            kind: 'home';
        } | {
            kind: 'team';
            teamId: string;
        };
        id: string;
        displayName: string;
        enabled: boolean;
        firstEnabledAt: number | null;
        securityRevision: number;
        revision: number;
        lastSuccessfulTest: {
            at: number;
            testedSecurityRevision: number;
            current: boolean;
        } | null;
        createdByAccountId: string | null;
        createdAt: number;
        updatedAt: number;
        teamConsumers: {
            team: {
                id: string;
                name: string;
            };
            binding: {
                kind: 'identity_connection';
                id: string;
                enabled: boolean;
            };
        }[];
        callbackUrl?: string | undefined;
    };
    readonly "identity.providers.update": {
        kind: 'oidc';
        config: {
            v: 1;
            kind: 'oidc';
            issuer: string;
            clientId: string;
            clientAuthenticationMethod: 'client_secret_post' | 'client_secret_basic';
            scopes: string;
            httpTimeoutSeconds: number;
            claims: {
                login: string;
                email: string;
                groups: string;
            };
            allow: {
                usersAllowlist: string[];
                emailDomains: string[];
                groupsAny: string[];
                groupsAll: string[];
            };
            fetchUserInfo: boolean;
            storeRefreshToken: boolean;
            ui: {
                buttonColor: string | null;
                iconHint: string | null;
            };
        };
        secret: {
            configured: boolean;
            health: 'configured' | 'missing' | 'unreadable';
        };
        v: 1;
        owner: {
            kind: 'home';
        } | {
            kind: 'team';
            teamId: string;
        };
        id: string;
        displayName: string;
        enabled: boolean;
        firstEnabledAt: number | null;
        securityRevision: number;
        revision: number;
        lastSuccessfulTest: {
            at: number;
            testedSecurityRevision: number;
            current: boolean;
        } | null;
        createdByAccountId: string | null;
        createdAt: number;
        updatedAt: number;
        teamConsumers: {
            team: {
                id: string;
                name: string;
            };
            binding: {
                kind: 'identity_connection';
                id: string;
                enabled: boolean;
            };
        }[];
        callbackUrl?: string | undefined;
    };
    readonly "identity.providers.secret.replace": {
        kind: 'oidc';
        config: {
            v: 1;
            kind: 'oidc';
            issuer: string;
            clientId: string;
            clientAuthenticationMethod: 'client_secret_post' | 'client_secret_basic';
            scopes: string;
            httpTimeoutSeconds: number;
            claims: {
                login: string;
                email: string;
                groups: string;
            };
            allow: {
                usersAllowlist: string[];
                emailDomains: string[];
                groupsAny: string[];
                groupsAll: string[];
            };
            fetchUserInfo: boolean;
            storeRefreshToken: boolean;
            ui: {
                buttonColor: string | null;
                iconHint: string | null;
            };
        };
        secret: {
            configured: boolean;
            health: 'configured' | 'missing' | 'unreadable';
        };
        v: 1;
        owner: {
            kind: 'home';
        } | {
            kind: 'team';
            teamId: string;
        };
        id: string;
        displayName: string;
        enabled: boolean;
        firstEnabledAt: number | null;
        securityRevision: number;
        revision: number;
        lastSuccessfulTest: {
            at: number;
            testedSecurityRevision: number;
            current: boolean;
        } | null;
        createdByAccountId: string | null;
        createdAt: number;
        updatedAt: number;
        teamConsumers: {
            team: {
                id: string;
                name: string;
            };
            binding: {
                kind: 'identity_connection';
                id: string;
                enabled: boolean;
            };
        }[];
        callbackUrl?: string | undefined;
    };
    readonly "identity.providers.validate": {
        kind: 'oidc';
        config: {
            v: 1;
            kind: 'oidc';
            issuer: string;
            clientId: string;
            clientAuthenticationMethod: 'client_secret_post' | 'client_secret_basic';
            scopes: string;
            httpTimeoutSeconds: number;
            claims: {
                login: string;
                email: string;
                groups: string;
            };
            allow: {
                usersAllowlist: string[];
                emailDomains: string[];
                groupsAny: string[];
                groupsAll: string[];
            };
            fetchUserInfo: boolean;
            storeRefreshToken: boolean;
            ui: {
                buttonColor: string | null;
                iconHint: string | null;
            };
        };
        secret: {
            configured: boolean;
            health: 'configured' | 'missing' | 'unreadable';
        };
        v: 1;
        owner: {
            kind: 'home';
        } | {
            kind: 'team';
            teamId: string;
        };
        id: string;
        displayName: string;
        enabled: boolean;
        firstEnabledAt: number | null;
        securityRevision: number;
        revision: number;
        lastSuccessfulTest: {
            at: number;
            testedSecurityRevision: number;
            current: boolean;
        } | null;
        createdByAccountId: string | null;
        createdAt: number;
        updatedAt: number;
        teamConsumers: {
            team: {
                id: string;
                name: string;
            };
            binding: {
                kind: 'identity_connection';
                id: string;
                enabled: boolean;
            };
        }[];
        callbackUrl?: string | undefined;
    };
    readonly "identity.providers.test.start": {
        authorizeUrl: string;
        attemptId: string;
    };
    readonly "identity.providers.test.consume": {
        provider: {
            kind: 'oidc';
            config: {
                v: 1;
                kind: 'oidc';
                issuer: string;
                clientId: string;
                clientAuthenticationMethod: 'client_secret_post' | 'client_secret_basic';
                scopes: string;
                httpTimeoutSeconds: number;
                claims: {
                    login: string;
                    email: string;
                    groups: string;
                };
                allow: {
                    usersAllowlist: string[];
                    emailDomains: string[];
                    groupsAny: string[];
                    groupsAll: string[];
                };
                fetchUserInfo: boolean;
                storeRefreshToken: boolean;
                ui: {
                    buttonColor: string | null;
                    iconHint: string | null;
                };
            };
            secret: {
                configured: boolean;
                health: 'configured' | 'missing' | 'unreadable';
            };
            v: 1;
            owner: {
                kind: 'home';
            } | {
                kind: 'team';
                teamId: string;
            };
            id: string;
            displayName: string;
            enabled: boolean;
            firstEnabledAt: number | null;
            securityRevision: number;
            revision: number;
            lastSuccessfulTest: {
                at: number;
                testedSecurityRevision: number;
                current: boolean;
            } | null;
            createdByAccountId: string | null;
            createdAt: number;
            updatedAt: number;
            teamConsumers: {
                team: {
                    id: string;
                    name: string;
                };
                binding: {
                    kind: 'identity_connection';
                    id: string;
                    enabled: boolean;
                };
            }[];
            callbackUrl?: string | undefined;
        };
        testedAt: number;
        subjectPresent: true;
        diagnostics?: {
            subjectPresent: boolean;
            loginAvailable: boolean;
            emailAvailable: boolean;
            emailVerified: boolean;
            groups: {
                state: 'complete' | 'absent' | 'incomplete';
                count: number | null;
            };
            eligibility: {
                status: 'eligible' | 'ineligible';
                rules: {
                    kind: 'users' | 'email_domains' | 'groups_any' | 'groups_all';
                    matched: boolean;
                }[];
            };
            mappedGroups: {
                id: string;
                name: string;
            }[];
        } | undefined;
    };
    readonly "identity.providers.enable": {
        kind: 'oidc';
        config: {
            v: 1;
            kind: 'oidc';
            issuer: string;
            clientId: string;
            clientAuthenticationMethod: 'client_secret_post' | 'client_secret_basic';
            scopes: string;
            httpTimeoutSeconds: number;
            claims: {
                login: string;
                email: string;
                groups: string;
            };
            allow: {
                usersAllowlist: string[];
                emailDomains: string[];
                groupsAny: string[];
                groupsAll: string[];
            };
            fetchUserInfo: boolean;
            storeRefreshToken: boolean;
            ui: {
                buttonColor: string | null;
                iconHint: string | null;
            };
        };
        secret: {
            configured: boolean;
            health: 'configured' | 'missing' | 'unreadable';
        };
        v: 1;
        owner: {
            kind: 'home';
        } | {
            kind: 'team';
            teamId: string;
        };
        id: string;
        displayName: string;
        enabled: boolean;
        firstEnabledAt: number | null;
        securityRevision: number;
        revision: number;
        lastSuccessfulTest: {
            at: number;
            testedSecurityRevision: number;
            current: boolean;
        } | null;
        createdByAccountId: string | null;
        createdAt: number;
        updatedAt: number;
        teamConsumers: {
            team: {
                id: string;
                name: string;
            };
            binding: {
                kind: 'identity_connection';
                id: string;
                enabled: boolean;
            };
        }[];
        callbackUrl?: string | undefined;
    } | {
        kind: 'github_app_identity';
        config: {
            v: 1;
            kind: 'github_app_identity';
        };
        githubAppInstallationId: string;
        v: 1;
        owner: {
            kind: 'home';
        } | {
            kind: 'team';
            teamId: string;
        };
        id: string;
        displayName: string;
        enabled: boolean;
        firstEnabledAt: number | null;
        securityRevision: number;
        revision: number;
        lastSuccessfulTest: {
            at: number;
            testedSecurityRevision: number;
            current: boolean;
        } | null;
        createdByAccountId: string | null;
        createdAt: number;
        updatedAt: number;
        teamConsumers: {
            team: {
                id: string;
                name: string;
            };
            binding: {
                kind: 'identity_connection';
                id: string;
                enabled: boolean;
            };
        }[];
        callbackUrl?: string | undefined;
    };
    readonly "identity.providers.disable": {
        kind: 'oidc';
        config: {
            v: 1;
            kind: 'oidc';
            issuer: string;
            clientId: string;
            clientAuthenticationMethod: 'client_secret_post' | 'client_secret_basic';
            scopes: string;
            httpTimeoutSeconds: number;
            claims: {
                login: string;
                email: string;
                groups: string;
            };
            allow: {
                usersAllowlist: string[];
                emailDomains: string[];
                groupsAny: string[];
                groupsAll: string[];
            };
            fetchUserInfo: boolean;
            storeRefreshToken: boolean;
            ui: {
                buttonColor: string | null;
                iconHint: string | null;
            };
        };
        secret: {
            configured: boolean;
            health: 'configured' | 'missing' | 'unreadable';
        };
        v: 1;
        owner: {
            kind: 'home';
        } | {
            kind: 'team';
            teamId: string;
        };
        id: string;
        displayName: string;
        enabled: boolean;
        firstEnabledAt: number | null;
        securityRevision: number;
        revision: number;
        lastSuccessfulTest: {
            at: number;
            testedSecurityRevision: number;
            current: boolean;
        } | null;
        createdByAccountId: string | null;
        createdAt: number;
        updatedAt: number;
        teamConsumers: {
            team: {
                id: string;
                name: string;
            };
            binding: {
                kind: 'identity_connection';
                id: string;
                enabled: boolean;
            };
        }[];
        callbackUrl?: string | undefined;
    } | {
        kind: 'github_app_identity';
        config: {
            v: 1;
            kind: 'github_app_identity';
        };
        githubAppInstallationId: string;
        v: 1;
        owner: {
            kind: 'home';
        } | {
            kind: 'team';
            teamId: string;
        };
        id: string;
        displayName: string;
        enabled: boolean;
        firstEnabledAt: number | null;
        securityRevision: number;
        revision: number;
        lastSuccessfulTest: {
            at: number;
            testedSecurityRevision: number;
            current: boolean;
        } | null;
        createdByAccountId: string | null;
        createdAt: number;
        updatedAt: number;
        teamConsumers: {
            team: {
                id: string;
                name: string;
            };
            binding: {
                kind: 'identity_connection';
                id: string;
                enabled: boolean;
            };
        }[];
        callbackUrl?: string | undefined;
    };
    readonly "identity.providers.remove.preview": {
        provider: {
            kind: 'oidc';
            config: {
                v: 1;
                kind: 'oidc';
                issuer: string;
                clientId: string;
                clientAuthenticationMethod: 'client_secret_post' | 'client_secret_basic';
                scopes: string;
                httpTimeoutSeconds: number;
                claims: {
                    login: string;
                    email: string;
                    groups: string;
                };
                allow: {
                    usersAllowlist: string[];
                    emailDomains: string[];
                    groupsAny: string[];
                    groupsAll: string[];
                };
                fetchUserInfo: boolean;
                storeRefreshToken: boolean;
                ui: {
                    buttonColor: string | null;
                    iconHint: string | null;
                };
            };
            secret: {
                configured: boolean;
                health: 'configured' | 'missing' | 'unreadable';
            };
            v: 1;
            owner: {
                kind: 'home';
            } | {
                kind: 'team';
                teamId: string;
            };
            id: string;
            displayName: string;
            enabled: boolean;
            firstEnabledAt: number | null;
            securityRevision: number;
            revision: number;
            lastSuccessfulTest: {
                at: number;
                testedSecurityRevision: number;
                current: boolean;
            } | null;
            createdByAccountId: string | null;
            createdAt: number;
            updatedAt: number;
            teamConsumers: {
                team: {
                    id: string;
                    name: string;
                };
                binding: {
                    kind: 'identity_connection';
                    id: string;
                    enabled: boolean;
                };
            }[];
            callbackUrl?: string | undefined;
        } | {
            kind: 'github_app_identity';
            config: {
                v: 1;
                kind: 'github_app_identity';
            };
            githubAppInstallationId: string;
            v: 1;
            owner: {
                kind: 'home';
            } | {
                kind: 'team';
                teamId: string;
            };
            id: string;
            displayName: string;
            enabled: boolean;
            firstEnabledAt: number | null;
            securityRevision: number;
            revision: number;
            lastSuccessfulTest: {
                at: number;
                testedSecurityRevision: number;
                current: boolean;
            } | null;
            createdByAccountId: string | null;
            createdAt: number;
            updatedAt: number;
            teamConsumers: {
                team: {
                    id: string;
                    name: string;
                };
                binding: {
                    kind: 'identity_connection';
                    id: string;
                    enabled: boolean;
                };
            }[];
            callbackUrl?: string | undefined;
        };
        canRemove: boolean;
        blockers: {
            identityCount: number;
            connectionCount: number;
            affectedAccountIds: string[];
        };
    };
    readonly "identity.providers.remove": {
        outcome: 'removed';
    };
};
