// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.


// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
export type IdentityGithubAppsActionInputById = {
    readonly "identity.githubApps.list": {
        owner: {
            kind: 'home';
        } | {
            kind: 'team';
            teamId: string;
        };
    };
    readonly "identity.githubApps.create": {
        owner: {
            kind: 'home';
        } | {
            kind: 'team';
            teamId: string;
        };
        githubHost: string;
        githubAppId: string;
        githubClientId: string;
        secrets: {
            privateKey: string;
            clientSecret?: string | undefined;
            webhookSecret?: string | undefined;
        };
        githubAppSlug?: string | null | undefined;
        githubOwnerId?: string | null | undefined;
        githubOwnerLogin?: string | null | undefined;
    };
    readonly "identity.githubApps.manifestSetup.start": {
        owner: {
            kind: 'home';
        } | {
            kind: 'team';
            teamId: string;
        };
        appName: string;
        githubOwner: {
            kind: 'account';
        } | {
            kind: 'organization';
            login: string;
        };
    };
    readonly "identity.githubApps.update": {
        owner: {
            kind: 'home';
        } | {
            kind: 'team';
            teamId: string;
        };
        registrationId: string;
        expectedRevision: number;
        patch: {
            githubClientId?: string | undefined;
            githubAppSlug?: string | null | undefined;
            githubOwnerLogin?: string | null | undefined;
            secrets?: {
                clientSecret?: string | null | undefined;
                privateKey?: string | null | undefined;
                webhookSecret?: string | null | undefined;
            } | undefined;
        };
    };
    readonly "identity.githubApps.verifyInstallation": {
        owner: {
            kind: 'home';
        } | {
            kind: 'team';
            teamId: string;
        };
        registrationId: string;
        expectedRegistrationRevision: number;
        expectedInstallationRevision: number;
        githubInstallationId: string;
        githubOrganizationId: string;
    };
    readonly "identity.githubApps.remove": {
        owner: {
            kind: 'home';
        } | {
            kind: 'team';
            teamId: string;
        };
        installationId: string;
        expectedRevision: number;
    };
};
export type IdentityGithubAppsActionResultById = {
    readonly "identity.githubApps.list": {
        registrations: {
            id: string;
            owner: {
                kind: 'home';
            } | {
                kind: 'team';
                teamId: string;
            };
            githubHost: string;
            githubAppId: string;
            githubClientId: string;
            githubAppSlug: string | null;
            githubOwnerId: string | null;
            githubOwnerLogin: string | null;
            revision: number;
            securityRevision: number;
            state: 'draft' | 'verified' | 'disabled' | 'needs_attention';
            secretHealth: {
                clientSecretConfigured: boolean;
                privateKeyConfigured: boolean;
                webhookSecretConfigured: boolean;
            };
            lastVerifiedAt: string | null;
            createdAt: string;
            updatedAt: string;
            callbackUrl?: string | undefined;
        }[];
        installations: {
            id: string;
            registrationId: string;
            githubInstallationId: string;
            githubOrganizationId: string;
            githubOrganizationLogin: string;
            repositorySelection: 'all' | 'selected';
            revision: number;
            state: string;
            verifiedPermissions: Record<string, 'read' | 'write'>;
            verifiedEvents: string[];
            suspendedAt: string | null;
            lastVerifiedAt: string | null;
            teamConsumers: {
                team: {
                    id: string;
                    name: string;
                };
                binding: {
                    kind: 'identity_connection';
                    id: string;
                    providerInstanceId: string;
                    enabled: boolean;
                } | {
                    kind: 'directory_source';
                    id: string;
                    state: 'needs_attention' | 'initializing' | 'active' | 'paused';
                };
            }[];
            requirements?: {
                permissions: Record<string, 'read' | 'write'>;
                events: string[];
                missingPermissions: {
                    permission: string;
                    required: 'read' | 'write';
                }[];
                missingEvents: string[];
            } | undefined;
            prospectiveRequirements?: {
                permissions: Record<string, 'read' | 'write'>;
                events: string[];
                missingPermissions: {
                    permission: string;
                    required: 'read' | 'write';
                }[];
                missingEvents: string[];
            } | undefined;
        }[];
    };
    readonly "identity.githubApps.create": {
        registration: {
            id: string;
            owner: {
                kind: 'home';
            } | {
                kind: 'team';
                teamId: string;
            };
            githubHost: string;
            githubAppId: string;
            githubClientId: string;
            githubAppSlug: string | null;
            githubOwnerId: string | null;
            githubOwnerLogin: string | null;
            revision: number;
            securityRevision: number;
            state: 'draft' | 'verified' | 'disabled' | 'needs_attention';
            secretHealth: {
                clientSecretConfigured: boolean;
                privateKeyConfigured: boolean;
                webhookSecretConfigured: boolean;
            };
            lastVerifiedAt: string | null;
            createdAt: string;
            updatedAt: string;
            callbackUrl?: string | undefined;
        };
    };
    readonly "identity.githubApps.manifestSetup.start": {
        authorizeUrl: string;
    };
    readonly "identity.githubApps.update": {
        registration: {
            id: string;
            owner: {
                kind: 'home';
            } | {
                kind: 'team';
                teamId: string;
            };
            githubHost: string;
            githubAppId: string;
            githubClientId: string;
            githubAppSlug: string | null;
            githubOwnerId: string | null;
            githubOwnerLogin: string | null;
            revision: number;
            securityRevision: number;
            state: 'draft' | 'verified' | 'disabled' | 'needs_attention';
            secretHealth: {
                clientSecretConfigured: boolean;
                privateKeyConfigured: boolean;
                webhookSecretConfigured: boolean;
            };
            lastVerifiedAt: string | null;
            createdAt: string;
            updatedAt: string;
            callbackUrl?: string | undefined;
        };
    };
    readonly "identity.githubApps.verifyInstallation": {
        authorizeUrl: string;
        attemptId: string;
    };
    readonly "identity.githubApps.remove": {
        removed: true;
    };
};
