// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.


/**
 * Mutable structural JSON authored into declarations and carried on wire
 * payloads, admitted by `PluginJsonValueV2Schema`. It is deliberately distinct
 * from the strict runtime value in `json/strictJsonValue.ts`: this spelling
 * describes data before strict normalization, so it stays mutable and carries
 * none of the prototype, accessor, dense-array, well-formed-Unicode, or
 * aggregate-byte guarantees that the strict normalizer enforces. Values of
 * this type may be passed where a strict runtime value is expected; a strict
 * runtime value may not be passed back the other way.
 */
export type PluginJsonValueV2 = null | boolean | number | string | PluginJsonValueV2[] | {
    [key: string]: PluginJsonValueV2;
};
