// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.


// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
export type LaunchProfilesActionInputById = {
    readonly "launch_profiles.publish": {
        profileId: string;
    };
};
export type LaunchProfilesActionResultById = {
    readonly "launch_profiles.publish": {
        artifactId: string;
    };
};
