// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.


// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
export type LocalServicesPublicPreviewActionInputById = {
    readonly "localServices.publicPreview.create": {
        [x: string]: unknown;
        machineId?: string | undefined;
        sessionId?: string | undefined;
        workspaceId?: string | undefined;
        previewId?: string | undefined;
        targetId?: string | undefined;
        exposureId?: string | undefined;
        mode?: 'authenticated' | 'secret_link' | 'public' | undefined;
        ttlMs?: number | undefined;
    };
    readonly "localServices.publicPreview.status": {
        [x: string]: unknown;
        machineId?: string | undefined;
        sessionId?: string | undefined;
        workspaceId?: string | undefined;
        previewId?: string | undefined;
        targetId?: string | undefined;
        exposureId?: string | undefined;
        mode?: 'authenticated' | 'secret_link' | 'public' | undefined;
        ttlMs?: number | undefined;
    };
    readonly "localServices.publicPreview.revoke": {
        [x: string]: unknown;
        machineId?: string | undefined;
        sessionId?: string | undefined;
        workspaceId?: string | undefined;
        previewId?: string | undefined;
        targetId?: string | undefined;
        exposureId?: string | undefined;
        mode?: 'authenticated' | 'secret_link' | 'public' | undefined;
        ttlMs?: number | undefined;
    };
    readonly "localServices.publicPreview.copyUrl": {
        [x: string]: unknown;
        machineId?: string | undefined;
        sessionId?: string | undefined;
        workspaceId?: string | undefined;
        previewId?: string | undefined;
        targetId?: string | undefined;
        exposureId?: string | undefined;
        mode?: 'authenticated' | 'secret_link' | 'public' | undefined;
        ttlMs?: number | undefined;
    };
};
export type LocalServicesPublicPreviewActionResultById = {
    readonly "localServices.publicPreview.create": {
        protocolVersion: 1;
        exposure: {
            exposureId: string;
            previewId: string;
            sessionId: string;
            machineId: string;
            mode: 'authenticated' | 'secret_link' | 'public';
            state: 'pending' | 'active' | 'revoked' | 'expired' | 'rate_limited';
            publicUrl: string;
            issuedAt: number;
            expiresAt: number;
            auditEventIds: string[];
            rateLimitProfileId: string;
            revokedAt?: number | undefined;
            policyDiagnostics?: Record<string, unknown> | undefined;
        };
        snapshot?: {
            v: 1;
            machineId: string;
            generatedAt: number;
            refreshState: 'error' | 'idle' | 'refreshing';
            policy: {
                enabled: boolean;
                allowedModes: ('authenticated' | 'secret_link' | 'public')[];
                dnsTlsRequired: boolean;
                auditRequired: boolean;
                rateLimitProfileIds: string[];
                maxTtlMs?: number | undefined;
                maxConcurrentExposures?: number | undefined;
            };
            exposures: {
                exposureId: string;
                previewId: string;
                sessionId: string;
                machineId: string;
                mode: 'authenticated' | 'secret_link' | 'public';
                state: 'pending' | 'active' | 'revoked' | 'expired' | 'rate_limited';
                publicUrl: string;
                issuedAt: number;
                expiresAt: number;
                auditEventIds: string[];
                rateLimitProfileId: string;
                revokedAt?: number | undefined;
                policyDiagnostics?: Record<string, unknown> | undefined;
            }[];
            diagnostics: {
                v: 1;
                code: 'revoked' | 'expired' | 'invalid_preview_resource' | 'preview_registration_failed' | 'preview_token_secret_missing' | 'preview_public_base_url_missing' | 'preview_not_found' | 'preview_token_missing' | 'token_mismatch' | 'binding_mismatch' | 'not_yet_valid' | 'host_origin_unavailable' | 'https_required' | 'invalid_public_base_url' | 'path_mode_degraded' | 'path_mode_cookie_semantics_unsupported' | 'service_worker_unavailable_in_path_mode' | 'cookie_isolated' | 'cookie_stripped' | 'upstream_header_stripped' | 'credentials_stripped' | 'method_not_allowed' | 'preview_loop_detected' | 'request_body_too_large' | 'response_body_too_large' | 'response_header_too_large' | 'upstream_response_invalid' | 'upstream_stream_failed' | 'invalid_upgrade_request' | 'web_socket_unavailable' | 'pms_observability_unavailable' | 'pms_relay_unavailable' | 'dns_tls_not_ready' | 'public_policy_denied' | 'public_preview_expired' | 'public_preview_rate_limited' | 'public_preview_revoked';
                severity: 'error' | 'info' | 'warning';
                scope: 'privatePreview' | 'publicPreview' | 'previewProxy';
                details: Record<string, unknown>;
                previewId?: string | undefined;
                publicExposureId?: string | undefined;
                emittedAtMs?: number | undefined;
            }[];
            sessionId?: string | undefined;
            previewId?: string | undefined;
        } | undefined;
    };
    readonly "localServices.publicPreview.status": {
        v: 1;
        machineId: string;
        generatedAt: number;
        refreshState: 'error' | 'idle' | 'refreshing';
        policy: {
            enabled: boolean;
            allowedModes: ('authenticated' | 'secret_link' | 'public')[];
            dnsTlsRequired: boolean;
            auditRequired: boolean;
            rateLimitProfileIds: string[];
            maxTtlMs?: number | undefined;
            maxConcurrentExposures?: number | undefined;
        };
        exposures: {
            exposureId: string;
            previewId: string;
            sessionId: string;
            machineId: string;
            mode: 'authenticated' | 'secret_link' | 'public';
            state: 'pending' | 'active' | 'revoked' | 'expired' | 'rate_limited';
            publicUrl: string;
            issuedAt: number;
            expiresAt: number;
            auditEventIds: string[];
            rateLimitProfileId: string;
            revokedAt?: number | undefined;
            policyDiagnostics?: Record<string, unknown> | undefined;
        }[];
        diagnostics: {
            v: 1;
            code: 'revoked' | 'expired' | 'invalid_preview_resource' | 'preview_registration_failed' | 'preview_token_secret_missing' | 'preview_public_base_url_missing' | 'preview_not_found' | 'preview_token_missing' | 'token_mismatch' | 'binding_mismatch' | 'not_yet_valid' | 'host_origin_unavailable' | 'https_required' | 'invalid_public_base_url' | 'path_mode_degraded' | 'path_mode_cookie_semantics_unsupported' | 'service_worker_unavailable_in_path_mode' | 'cookie_isolated' | 'cookie_stripped' | 'upstream_header_stripped' | 'credentials_stripped' | 'method_not_allowed' | 'preview_loop_detected' | 'request_body_too_large' | 'response_body_too_large' | 'response_header_too_large' | 'upstream_response_invalid' | 'upstream_stream_failed' | 'invalid_upgrade_request' | 'web_socket_unavailable' | 'pms_observability_unavailable' | 'pms_relay_unavailable' | 'dns_tls_not_ready' | 'public_policy_denied' | 'public_preview_expired' | 'public_preview_rate_limited' | 'public_preview_revoked';
            severity: 'error' | 'info' | 'warning';
            scope: 'privatePreview' | 'publicPreview' | 'previewProxy';
            details: Record<string, unknown>;
            previewId?: string | undefined;
            publicExposureId?: string | undefined;
            emittedAtMs?: number | undefined;
        }[];
        sessionId?: string | undefined;
        previewId?: string | undefined;
    };
    readonly "localServices.publicPreview.revoke": {
        protocolVersion: 1;
        exposureId: string;
        revokedAt: number;
        snapshot: {
            v: 1;
            machineId: string;
            generatedAt: number;
            refreshState: 'error' | 'idle' | 'refreshing';
            policy: {
                enabled: boolean;
                allowedModes: ('authenticated' | 'secret_link' | 'public')[];
                dnsTlsRequired: boolean;
                auditRequired: boolean;
                rateLimitProfileIds: string[];
                maxTtlMs?: number | undefined;
                maxConcurrentExposures?: number | undefined;
            };
            exposures: {
                exposureId: string;
                previewId: string;
                sessionId: string;
                machineId: string;
                mode: 'authenticated' | 'secret_link' | 'public';
                state: 'pending' | 'active' | 'revoked' | 'expired' | 'rate_limited';
                publicUrl: string;
                issuedAt: number;
                expiresAt: number;
                auditEventIds: string[];
                rateLimitProfileId: string;
                revokedAt?: number | undefined;
                policyDiagnostics?: Record<string, unknown> | undefined;
            }[];
            diagnostics: {
                v: 1;
                code: 'revoked' | 'expired' | 'invalid_preview_resource' | 'preview_registration_failed' | 'preview_token_secret_missing' | 'preview_public_base_url_missing' | 'preview_not_found' | 'preview_token_missing' | 'token_mismatch' | 'binding_mismatch' | 'not_yet_valid' | 'host_origin_unavailable' | 'https_required' | 'invalid_public_base_url' | 'path_mode_degraded' | 'path_mode_cookie_semantics_unsupported' | 'service_worker_unavailable_in_path_mode' | 'cookie_isolated' | 'cookie_stripped' | 'upstream_header_stripped' | 'credentials_stripped' | 'method_not_allowed' | 'preview_loop_detected' | 'request_body_too_large' | 'response_body_too_large' | 'response_header_too_large' | 'upstream_response_invalid' | 'upstream_stream_failed' | 'invalid_upgrade_request' | 'web_socket_unavailable' | 'pms_observability_unavailable' | 'pms_relay_unavailable' | 'dns_tls_not_ready' | 'public_policy_denied' | 'public_preview_expired' | 'public_preview_rate_limited' | 'public_preview_revoked';
                severity: 'error' | 'info' | 'warning';
                scope: 'privatePreview' | 'publicPreview' | 'previewProxy';
                details: Record<string, unknown>;
                previewId?: string | undefined;
                publicExposureId?: string | undefined;
                emittedAtMs?: number | undefined;
            }[];
            sessionId?: string | undefined;
            previewId?: string | undefined;
        };
    };
    readonly "localServices.publicPreview.copyUrl": {
        protocolVersion: 1;
        machineId: string;
        sessionId: string;
        previewId: string;
        exposureId: string;
        publicUrl: string;
    };
};
