// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.


// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
export type LocalServicesActionsActionInputById = {
    readonly "localServices.actions.copyUrl": {
        requestId: string;
        target: {
            kind: 'inventory_entry';
            inventoryEntryId: string;
            machineId: string;
            sessionId?: string | undefined;
            workspaceId?: string | undefined;
        } | {
            kind: 'managed_service';
            managedServiceId: string;
            machineId: string;
            sessionId?: string | undefined;
            workspaceId?: string | undefined;
        };
        action: 'copy_url' | 'open_preview' | 'forget' | 'stop_managed' | 'restart_managed' | 'terminate_detected';
        undoKey?: string | undefined;
        confirmationNonce?: string | undefined;
        force?: boolean | undefined;
    };
    readonly "localServices.actions.openPreview": {
        requestId: string;
        target: {
            kind: 'inventory_entry';
            inventoryEntryId: string;
            machineId: string;
            sessionId?: string | undefined;
            workspaceId?: string | undefined;
        } | {
            kind: 'managed_service';
            managedServiceId: string;
            machineId: string;
            sessionId?: string | undefined;
            workspaceId?: string | undefined;
        };
        action: 'copy_url' | 'open_preview' | 'forget' | 'stop_managed' | 'restart_managed' | 'terminate_detected';
        undoKey?: string | undefined;
        confirmationNonce?: string | undefined;
        force?: boolean | undefined;
    };
    readonly "localServices.actions.forget": {
        requestId: string;
        target: {
            kind: 'inventory_entry';
            inventoryEntryId: string;
            machineId: string;
            sessionId?: string | undefined;
            workspaceId?: string | undefined;
        } | {
            kind: 'managed_service';
            managedServiceId: string;
            machineId: string;
            sessionId?: string | undefined;
            workspaceId?: string | undefined;
        };
        action: 'copy_url' | 'open_preview' | 'forget' | 'stop_managed' | 'restart_managed' | 'terminate_detected';
        undoKey?: string | undefined;
        confirmationNonce?: string | undefined;
        force?: boolean | undefined;
    };
    readonly "localServices.actions.stopManaged": {
        requestId: string;
        target: {
            kind: 'inventory_entry';
            inventoryEntryId: string;
            machineId: string;
            sessionId?: string | undefined;
            workspaceId?: string | undefined;
        } | {
            kind: 'managed_service';
            managedServiceId: string;
            machineId: string;
            sessionId?: string | undefined;
            workspaceId?: string | undefined;
        };
        action: 'copy_url' | 'open_preview' | 'forget' | 'stop_managed' | 'restart_managed' | 'terminate_detected';
        undoKey?: string | undefined;
        confirmationNonce?: string | undefined;
        force?: boolean | undefined;
    };
    readonly "localServices.actions.restartManaged": {
        requestId: string;
        target: {
            kind: 'inventory_entry';
            inventoryEntryId: string;
            machineId: string;
            sessionId?: string | undefined;
            workspaceId?: string | undefined;
        } | {
            kind: 'managed_service';
            managedServiceId: string;
            machineId: string;
            sessionId?: string | undefined;
            workspaceId?: string | undefined;
        };
        action: 'copy_url' | 'open_preview' | 'forget' | 'stop_managed' | 'restart_managed' | 'terminate_detected';
        undoKey?: string | undefined;
        confirmationNonce?: string | undefined;
        force?: boolean | undefined;
    };
    readonly "localServices.actions.terminateDetected": {
        requestId: string;
        target: {
            kind: 'inventory_entry';
            inventoryEntryId: string;
            machineId: string;
            sessionId?: string | undefined;
            workspaceId?: string | undefined;
        } | {
            kind: 'managed_service';
            managedServiceId: string;
            machineId: string;
            sessionId?: string | undefined;
            workspaceId?: string | undefined;
        };
        action: 'copy_url' | 'open_preview' | 'forget' | 'stop_managed' | 'restart_managed' | 'terminate_detected';
        undoKey?: string | undefined;
        confirmationNonce?: string | undefined;
        force?: boolean | undefined;
    };
};
export type LocalServicesActionsActionResultById = {
    readonly "localServices.actions.copyUrl": {
        v: 1;
        requestId: string;
        action: 'copy_url' | 'open_preview' | 'forget' | 'stop_managed' | 'restart_managed' | 'terminate_detected';
        status: 'succeeded' | 'denied' | 'failed';
        auditEvents: {
            v: 1;
            eventId: string;
            requestId: string;
            machineId: string;
            action: 'copy_url' | 'open_preview' | 'forget' | 'stop_managed' | 'restart_managed' | 'terminate_detected';
            result: 'succeeded' | 'denied' | 'failed' | 'requested' | 'confirmed';
            recordedAt: number;
            reasonCode?: string | undefined;
        }[];
        undoKey?: string | undefined;
        reasonCode?: string | undefined;
    };
    readonly "localServices.actions.openPreview": {
        v: 1;
        requestId: string;
        action: 'copy_url' | 'open_preview' | 'forget' | 'stop_managed' | 'restart_managed' | 'terminate_detected';
        status: 'succeeded' | 'denied' | 'failed';
        auditEvents: {
            v: 1;
            eventId: string;
            requestId: string;
            machineId: string;
            action: 'copy_url' | 'open_preview' | 'forget' | 'stop_managed' | 'restart_managed' | 'terminate_detected';
            result: 'succeeded' | 'denied' | 'failed' | 'requested' | 'confirmed';
            recordedAt: number;
            reasonCode?: string | undefined;
        }[];
        undoKey?: string | undefined;
        reasonCode?: string | undefined;
    };
    readonly "localServices.actions.forget": {
        v: 1;
        requestId: string;
        action: 'copy_url' | 'open_preview' | 'forget' | 'stop_managed' | 'restart_managed' | 'terminate_detected';
        status: 'succeeded' | 'denied' | 'failed';
        auditEvents: {
            v: 1;
            eventId: string;
            requestId: string;
            machineId: string;
            action: 'copy_url' | 'open_preview' | 'forget' | 'stop_managed' | 'restart_managed' | 'terminate_detected';
            result: 'succeeded' | 'denied' | 'failed' | 'requested' | 'confirmed';
            recordedAt: number;
            reasonCode?: string | undefined;
        }[];
        undoKey?: string | undefined;
        reasonCode?: string | undefined;
    };
    readonly "localServices.actions.stopManaged": {
        v: 1;
        requestId: string;
        action: 'copy_url' | 'open_preview' | 'forget' | 'stop_managed' | 'restart_managed' | 'terminate_detected';
        status: 'succeeded' | 'denied' | 'failed';
        auditEvents: {
            v: 1;
            eventId: string;
            requestId: string;
            machineId: string;
            action: 'copy_url' | 'open_preview' | 'forget' | 'stop_managed' | 'restart_managed' | 'terminate_detected';
            result: 'succeeded' | 'denied' | 'failed' | 'requested' | 'confirmed';
            recordedAt: number;
            reasonCode?: string | undefined;
        }[];
        undoKey?: string | undefined;
        reasonCode?: string | undefined;
    };
    readonly "localServices.actions.restartManaged": {
        v: 1;
        requestId: string;
        action: 'copy_url' | 'open_preview' | 'forget' | 'stop_managed' | 'restart_managed' | 'terminate_detected';
        status: 'succeeded' | 'denied' | 'failed';
        auditEvents: {
            v: 1;
            eventId: string;
            requestId: string;
            machineId: string;
            action: 'copy_url' | 'open_preview' | 'forget' | 'stop_managed' | 'restart_managed' | 'terminate_detected';
            result: 'succeeded' | 'denied' | 'failed' | 'requested' | 'confirmed';
            recordedAt: number;
            reasonCode?: string | undefined;
        }[];
        undoKey?: string | undefined;
        reasonCode?: string | undefined;
    };
    readonly "localServices.actions.terminateDetected": {
        v: 1;
        requestId: string;
        action: 'copy_url' | 'open_preview' | 'forget' | 'stop_managed' | 'restart_managed' | 'terminate_detected';
        status: 'succeeded' | 'denied' | 'failed';
        auditEvents: {
            v: 1;
            eventId: string;
            requestId: string;
            machineId: string;
            action: 'copy_url' | 'open_preview' | 'forget' | 'stop_managed' | 'restart_managed' | 'terminate_detected';
            result: 'succeeded' | 'denied' | 'failed' | 'requested' | 'confirmed';
            recordedAt: number;
            reasonCode?: string | undefined;
        }[];
        undoKey?: string | undefined;
        reasonCode?: string | undefined;
    };
};
