// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.


// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
export type LocalServicesLauncherActionInputById = {
    readonly "localServices.launcher.snapshot": {
        [x: string]: unknown;
        machineId?: string | undefined;
        sessionId?: string | undefined;
        workspaceId?: string | undefined;
    };
    readonly "localServices.launcher.start": {
        machineId: string;
        targetId: string;
        sessionId?: string | undefined;
        workspaceId?: string | undefined;
    };
    readonly "localServices.launcher.openPreview": {
        [x: string]: unknown;
        machineId?: string | undefined;
        sessionId?: string | undefined;
        workspaceId?: string | undefined;
        targetId?: string | undefined;
    };
    readonly "localServices.launcher.registerPreview": {
        [x: string]: unknown;
        machineId?: string | undefined;
        sessionId?: string | undefined;
        workspaceId?: string | undefined;
        targetId?: string | undefined;
    };
    readonly "localServices.launcher.history.clear": {
        [x: string]: unknown;
        machineId?: string | undefined;
        sessionId?: string | undefined;
        workspaceId?: string | undefined;
        targetId?: string | undefined;
    };
};
export type LocalServicesLauncherActionResultById = {
    readonly "localServices.launcher.snapshot": {
        v: 1;
        machineId: string;
        updatedAt: number;
        targets: {
            id: string;
            source: 'package_script' | 'managed_service' | 'inventory_entry' | 'registered_preview' | 'terminal_url' | 'workspace_file_asset' | 'recent';
            machineId: string;
            title: string;
            confidence: 'high' | 'medium' | 'low';
            state: 'available' | 'starting' | 'stale' | 'unavailable';
            actions: ('start' | 'open' | 'open_preview' | 'register_preview' | 'manage' | 'terminate_detected')[];
            sourceClass?: {
                kind: 'package_script';
                runTargetId: string;
                packageName: string;
                scriptName: string;
                cwd?: string | undefined;
            } | {
                kind: 'managed_service';
                managedServiceId: string;
                inventoryEntryId?: string | undefined;
            } | {
                kind: 'inventory_entry';
                inventoryEntryId: string;
            } | {
                kind: 'registered_preview';
                previewId: string;
            } | {
                kind: 'terminal_url';
                sourceId: string;
                addressLabel: string;
                host?: string | undefined;
                port?: number | undefined;
            } | {
                kind: 'workspace_file_asset';
                sourceId: string;
                assetRef: string;
                mediaType?: string | undefined;
            } | {
                kind: 'recent';
                targetId: string;
            } | undefined;
            sessionId?: string | undefined;
            workspaceId?: string | undefined;
            cwd?: string | undefined;
            subtitle?: string | undefined;
            kind?: string | undefined;
            commandPreview?: string | undefined;
            unavailableReason?: string | undefined;
            browserTarget?: {
                targetId: string;
                kind: 'localServicePreview';
                machineId: string;
                display?: {
                    title: string;
                    addressLabel?: string | undefined;
                    folderLabel?: string | undefined;
                    iconToken?: string | undefined;
                    tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                } | undefined;
                sessionId?: string | undefined;
            } | {
                targetId: string;
                kind: 'hostedPluginWeb';
                pluginId: string;
                contributionId: string;
                display?: {
                    title: string;
                    addressLabel?: string | undefined;
                    folderLabel?: string | undefined;
                    iconToken?: string | undefined;
                    tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                } | undefined;
            } | {
                targetId: string;
                kind: 'externalUrl';
                url: string;
                display?: {
                    title: string;
                    addressLabel?: string | undefined;
                    folderLabel?: string | undefined;
                    iconToken?: string | undefined;
                    tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                } | undefined;
            } | {
                targetId: string;
                kind: 'streamedBrowser';
                streamId: string;
                display?: {
                    title: string;
                    addressLabel?: string | undefined;
                    folderLabel?: string | undefined;
                    iconToken?: string | undefined;
                    tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                } | undefined;
            } | {
                targetId: string;
                kind: 'simulatorPreview';
                deviceId: string;
                display?: {
                    title: string;
                    addressLabel?: string | undefined;
                    folderLabel?: string | undefined;
                    iconToken?: string | undefined;
                    tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                } | undefined;
                sourceId?: string | undefined;
            } | undefined;
        }[];
        sessionId?: string | undefined;
    };
    readonly "localServices.launcher.start": {
        protocolVersion: 1;
        machineId: string;
        targetId: string;
        status: 'succeeded' | 'denied' | 'failed';
        snapshot: {
            v: 1;
            machineId: string;
            updatedAt: number;
            targets: {
                id: string;
                source: 'package_script' | 'managed_service' | 'inventory_entry' | 'registered_preview' | 'terminal_url' | 'workspace_file_asset' | 'recent';
                machineId: string;
                title: string;
                confidence: 'high' | 'medium' | 'low';
                state: 'available' | 'starting' | 'stale' | 'unavailable';
                actions: ('start' | 'open' | 'open_preview' | 'register_preview' | 'manage' | 'terminate_detected')[];
                sourceClass?: {
                    kind: 'package_script';
                    runTargetId: string;
                    packageName: string;
                    scriptName: string;
                    cwd?: string | undefined;
                } | {
                    kind: 'managed_service';
                    managedServiceId: string;
                    inventoryEntryId?: string | undefined;
                } | {
                    kind: 'inventory_entry';
                    inventoryEntryId: string;
                } | {
                    kind: 'registered_preview';
                    previewId: string;
                } | {
                    kind: 'terminal_url';
                    sourceId: string;
                    addressLabel: string;
                    host?: string | undefined;
                    port?: number | undefined;
                } | {
                    kind: 'workspace_file_asset';
                    sourceId: string;
                    assetRef: string;
                    mediaType?: string | undefined;
                } | {
                    kind: 'recent';
                    targetId: string;
                } | undefined;
                sessionId?: string | undefined;
                workspaceId?: string | undefined;
                cwd?: string | undefined;
                subtitle?: string | undefined;
                kind?: string | undefined;
                commandPreview?: string | undefined;
                unavailableReason?: string | undefined;
                browserTarget?: {
                    targetId: string;
                    kind: 'localServicePreview';
                    machineId: string;
                    display?: {
                        title: string;
                        addressLabel?: string | undefined;
                        folderLabel?: string | undefined;
                        iconToken?: string | undefined;
                        tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                    } | undefined;
                    sessionId?: string | undefined;
                } | {
                    targetId: string;
                    kind: 'hostedPluginWeb';
                    pluginId: string;
                    contributionId: string;
                    display?: {
                        title: string;
                        addressLabel?: string | undefined;
                        folderLabel?: string | undefined;
                        iconToken?: string | undefined;
                        tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                    } | undefined;
                } | {
                    targetId: string;
                    kind: 'externalUrl';
                    url: string;
                    display?: {
                        title: string;
                        addressLabel?: string | undefined;
                        folderLabel?: string | undefined;
                        iconToken?: string | undefined;
                        tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                    } | undefined;
                } | {
                    targetId: string;
                    kind: 'streamedBrowser';
                    streamId: string;
                    display?: {
                        title: string;
                        addressLabel?: string | undefined;
                        folderLabel?: string | undefined;
                        iconToken?: string | undefined;
                        tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                    } | undefined;
                } | {
                    targetId: string;
                    kind: 'simulatorPreview';
                    deviceId: string;
                    display?: {
                        title: string;
                        addressLabel?: string | undefined;
                        folderLabel?: string | undefined;
                        iconToken?: string | undefined;
                        tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                    } | undefined;
                    sourceId?: string | undefined;
                } | undefined;
            }[];
            sessionId?: string | undefined;
        };
        reasonCode?: string | undefined;
    };
    readonly "localServices.launcher.openPreview": {
        protocolVersion: 1;
        status: 'unavailable' | 'opened';
        targetId: string;
        browserTarget?: {
            targetId: string;
            kind: 'localServicePreview';
            machineId: string;
            display?: {
                title: string;
                addressLabel?: string | undefined;
                folderLabel?: string | undefined;
                iconToken?: string | undefined;
                tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
            } | undefined;
            sessionId?: string | undefined;
        } | {
            targetId: string;
            kind: 'hostedPluginWeb';
            pluginId: string;
            contributionId: string;
            display?: {
                title: string;
                addressLabel?: string | undefined;
                folderLabel?: string | undefined;
                iconToken?: string | undefined;
                tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
            } | undefined;
        } | {
            targetId: string;
            kind: 'externalUrl';
            url: string;
            display?: {
                title: string;
                addressLabel?: string | undefined;
                folderLabel?: string | undefined;
                iconToken?: string | undefined;
                tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
            } | undefined;
        } | {
            targetId: string;
            kind: 'streamedBrowser';
            streamId: string;
            display?: {
                title: string;
                addressLabel?: string | undefined;
                folderLabel?: string | undefined;
                iconToken?: string | undefined;
                tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
            } | undefined;
        } | {
            targetId: string;
            kind: 'simulatorPreview';
            deviceId: string;
            display?: {
                title: string;
                addressLabel?: string | undefined;
                folderLabel?: string | undefined;
                iconToken?: string | undefined;
                tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
            } | undefined;
            sourceId?: string | undefined;
        } | undefined;
        reasonCode?: string | undefined;
    };
    readonly "localServices.launcher.registerPreview": {
        protocolVersion: 1;
        status: 'unavailable' | 'registered' | 'existing';
        targetId: string;
        previewId?: string | undefined;
        browserTarget?: {
            targetId: string;
            kind: 'localServicePreview';
            machineId: string;
            display?: {
                title: string;
                addressLabel?: string | undefined;
                folderLabel?: string | undefined;
                iconToken?: string | undefined;
                tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
            } | undefined;
            sessionId?: string | undefined;
        } | {
            targetId: string;
            kind: 'hostedPluginWeb';
            pluginId: string;
            contributionId: string;
            display?: {
                title: string;
                addressLabel?: string | undefined;
                folderLabel?: string | undefined;
                iconToken?: string | undefined;
                tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
            } | undefined;
        } | {
            targetId: string;
            kind: 'externalUrl';
            url: string;
            display?: {
                title: string;
                addressLabel?: string | undefined;
                folderLabel?: string | undefined;
                iconToken?: string | undefined;
                tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
            } | undefined;
        } | {
            targetId: string;
            kind: 'streamedBrowser';
            streamId: string;
            display?: {
                title: string;
                addressLabel?: string | undefined;
                folderLabel?: string | undefined;
                iconToken?: string | undefined;
                tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
            } | undefined;
        } | {
            targetId: string;
            kind: 'simulatorPreview';
            deviceId: string;
            display?: {
                title: string;
                addressLabel?: string | undefined;
                folderLabel?: string | undefined;
                iconToken?: string | undefined;
                tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
            } | undefined;
            sourceId?: string | undefined;
        } | undefined;
        reasonCode?: string | undefined;
    };
    readonly "localServices.launcher.history.clear": {
        protocolVersion: 1;
        cleared: number;
        snapshot: {
            v: 1;
            machineId: string;
            updatedAt: number;
            targets: {
                id: string;
                source: 'package_script' | 'managed_service' | 'inventory_entry' | 'registered_preview' | 'terminal_url' | 'workspace_file_asset' | 'recent';
                machineId: string;
                title: string;
                confidence: 'high' | 'medium' | 'low';
                state: 'available' | 'starting' | 'stale' | 'unavailable';
                actions: ('start' | 'open' | 'open_preview' | 'register_preview' | 'manage' | 'terminate_detected')[];
                sourceClass?: {
                    kind: 'package_script';
                    runTargetId: string;
                    packageName: string;
                    scriptName: string;
                    cwd?: string | undefined;
                } | {
                    kind: 'managed_service';
                    managedServiceId: string;
                    inventoryEntryId?: string | undefined;
                } | {
                    kind: 'inventory_entry';
                    inventoryEntryId: string;
                } | {
                    kind: 'registered_preview';
                    previewId: string;
                } | {
                    kind: 'terminal_url';
                    sourceId: string;
                    addressLabel: string;
                    host?: string | undefined;
                    port?: number | undefined;
                } | {
                    kind: 'workspace_file_asset';
                    sourceId: string;
                    assetRef: string;
                    mediaType?: string | undefined;
                } | {
                    kind: 'recent';
                    targetId: string;
                } | undefined;
                sessionId?: string | undefined;
                workspaceId?: string | undefined;
                cwd?: string | undefined;
                subtitle?: string | undefined;
                kind?: string | undefined;
                commandPreview?: string | undefined;
                unavailableReason?: string | undefined;
                browserTarget?: {
                    targetId: string;
                    kind: 'localServicePreview';
                    machineId: string;
                    display?: {
                        title: string;
                        addressLabel?: string | undefined;
                        folderLabel?: string | undefined;
                        iconToken?: string | undefined;
                        tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                    } | undefined;
                    sessionId?: string | undefined;
                } | {
                    targetId: string;
                    kind: 'hostedPluginWeb';
                    pluginId: string;
                    contributionId: string;
                    display?: {
                        title: string;
                        addressLabel?: string | undefined;
                        folderLabel?: string | undefined;
                        iconToken?: string | undefined;
                        tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                    } | undefined;
                } | {
                    targetId: string;
                    kind: 'externalUrl';
                    url: string;
                    display?: {
                        title: string;
                        addressLabel?: string | undefined;
                        folderLabel?: string | undefined;
                        iconToken?: string | undefined;
                        tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                    } | undefined;
                } | {
                    targetId: string;
                    kind: 'streamedBrowser';
                    streamId: string;
                    display?: {
                        title: string;
                        addressLabel?: string | undefined;
                        folderLabel?: string | undefined;
                        iconToken?: string | undefined;
                        tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                    } | undefined;
                } | {
                    targetId: string;
                    kind: 'simulatorPreview';
                    deviceId: string;
                    display?: {
                        title: string;
                        addressLabel?: string | undefined;
                        folderLabel?: string | undefined;
                        iconToken?: string | undefined;
                        tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                    } | undefined;
                    sourceId?: string | undefined;
                } | undefined;
            }[];
            sessionId?: string | undefined;
        };
    };
};
