// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.


// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
export type MachineConnectionActionInputById = {
    readonly "machines.terminal.list": {
        machineId: string;
        serverId?: string | undefined;
    };
    readonly "machines.add.ssh.start": {
        serverId: string;
        host: string;
        username?: string | undefined;
        port?: number | undefined;
        authMode?: 'agent' | 'keyfile' | 'password' | undefined;
        identityFilePath?: string | undefined;
    };
    readonly "machines.add.ssh.status": {
        taskId: string;
    };
    readonly "machines.add.ssh.respond": {
        taskId: string;
        answer: {
            kind: 'ssh.trustHost';
            trusted: boolean;
        } | {
            kind: 'ssh.replaceHostKey';
            trusted: boolean;
        } | {
            kind: 'auth.approveRemoteProvisioning';
            approved: boolean;
        } | {
            kind: 'daemon.replaceRemoteBackgroundServices';
            replaceExistingServices: boolean;
        } | {
            kind: 'releaseChannel.switchDefaultForSetup';
            switchDefaultReleaseChannel: boolean;
        };
    };
    readonly "machines.add.ssh.cancel": {
        taskId: string;
    };
    readonly "homes.connect": {
        address: string;
        displayName?: string | undefined;
        acceptInsecureHttp?: boolean | undefined;
        acceptCanonicalUrl?: boolean | undefined;
    };
    readonly "machines.add.command": {
        method: 'another_computer';
        serverId: string;
        os: 'macos' | 'linux' | 'windows';
    } | {
        method: 'ssh';
        serverId: string;
        os: 'macos' | 'linux' | 'windows';
        host: string;
        username?: string | undefined;
        port?: number | undefined;
        authMode?: 'agent' | 'keyfile' | 'password' | undefined;
        identityFilePath?: string | undefined;
    };
    readonly "machines.pairing.create": {
        serverId: string;
    };
    readonly "machines.terminal.open": {
        terminalKey: string;
        machineId: string;
        cwd?: string | undefined;
        cols?: number | undefined;
        rows?: number | undefined;
        initialCommand?: string | undefined;
        launch?: {
            kind: 'package_script';
            runTargetId: string;
        } | {
            kind: 'agent_login';
            agentId: string;
            launchId?: 'primary' | 'device_code' | undefined;
        } | {
            kind: 'session_attach';
            sessionId: string;
        } | {
            kind: 'happier_cli';
            args: string[];
        } | undefined;
        sessionId?: string | undefined;
        serverId?: string | undefined;
    };
};
export type MachineConnectionActionResultById = {
    readonly "machines.terminal.list": {
        ok: true;
        terminals: {
            terminalId: string;
            terminalKey: string;
            cwd: string;
            ended: boolean;
            exit: {
                exitCode: number | null;
                signal: number | null;
            } | null;
            sessionId?: string | undefined;
        }[];
    } | {
        ok: false;
        errorCode: 'terminal_disabled' | 'terminal_not_found' | 'terminal_cwd_denied' | 'terminal_spawn_failed' | 'terminal_invalid_request' | 'terminal_busy' | 'terminal_resize_unavailable' | 'agent_login_unsupported' | 'agent_cli_missing';
        error: string;
    } | null;
    readonly "machines.add.ssh.start": {
        taskId: string;
    };
    readonly "machines.add.ssh.status": {
        taskId: string;
        status: 'running' | 'canceling' | 'succeeded' | 'failed' | 'canceled';
        currentStepId: string | null;
        awaitingInput: boolean;
        prompt: {
            kind: string;
            message: string;
            requiresPresentUser: boolean;
            fingerprint?: string | undefined;
            existingFingerprint?: string | null | undefined;
            target?: string | undefined;
            publicKey?: string | null | undefined;
        } | null;
        machineId: string | null;
        errorCode: string | null;
    };
    readonly "machines.add.ssh.respond": {
        taskId: string;
    };
    readonly "machines.add.ssh.cancel": {
        taskId: string;
    };
    readonly "homes.connect": {
        kind: 'connected';
        serverId: string;
        serverUrl: string;
        name: string;
    } | {
        kind: 'invalid_address';
    } | {
        kind: 'declined';
    } | {
        kind: 'mixed_content';
    } | {
        kind: 'unreachable';
    };
    readonly "machines.add.command": {
        command: string;
        descriptorFileRequired: boolean;
    };
    readonly "machines.pairing.create": {
        pairId: string;
        link: string;
        expiresAtMs: number;
    };
    readonly "machines.terminal.open": {
        [x: string]: unknown;
        ok: false;
        errorCode: 'terminal_disabled' | 'terminal_not_found' | 'terminal_cwd_denied' | 'terminal_spawn_failed' | 'terminal_invalid_request' | 'terminal_busy' | 'terminal_resize_unavailable' | 'agent_login_unsupported' | 'agent_cli_missing';
        error: string;
    } | {
        [x: string]: unknown;
        ok: true;
        terminalId: string;
        reused: boolean;
    };
};
