// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.


// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
export type NotificationsActionInputById = {
    readonly "notifications.notify_me": {
        message: string;
        title?: string | undefined;
        open?: {
            kind: 'session';
            sessionId: string;
        } | {
            kind: 'workflow_run';
            runId: string;
        } | undefined;
        channels?: string[] | undefined;
    };
};
export type NotificationsActionResultById = {
    readonly "notifications.notify_me": {
        attemptedChannels: number;
        deliveredChannels: number;
    };
};
