// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.

import type { JsonValue } from './strictJsonValue.generated.js';

export type PluginSettingsAdministrationActionInputById = {
    readonly "plugins.settings.list": {
        pluginId: string;
        scope: {
            kind: 'account' | 'daemon';
        };
        target: {
            kind: 'account';
        } | {
            kind: 'daemon';
            serverIdentityId: string;
            machineId: string;
        };
    };
    readonly "plugins.settings.get": {
        pluginId: string;
        scope: {
            kind: 'account' | 'daemon';
        };
        target: {
            kind: 'account';
        } | {
            kind: 'daemon';
            serverIdentityId: string;
            machineId: string;
        };
        localId: string;
    };
    readonly "plugins.settings.set": {
        pluginId: string;
        scope: {
            kind: 'account' | 'daemon';
        };
        target: {
            kind: 'account';
        } | {
            kind: 'daemon';
            serverIdentityId: string;
            machineId: string;
        };
        localId: string;
        value: unknown;
        expectedRevision?: string | undefined;
    };
    readonly "plugins.settings.reset": {
        pluginId: string;
        scope: {
            kind: 'account' | 'daemon';
        };
        target: {
            kind: 'account';
        } | {
            kind: 'daemon';
            serverIdentityId: string;
            machineId: string;
        };
        localId: string;
        expectedRevision?: string | undefined;
    };
    readonly "plugins.settings.secret.status": {
        pluginId: string;
        localId: string;
        scope?: {
            kind: 'account' | 'daemon';
        } | undefined;
        target?: {
            kind: 'account';
        } | {
            kind: 'daemon';
            serverIdentityId: string;
            machineId: string;
        } | undefined;
        secretDaemonTarget?: {
            kind: 'daemon';
            serverIdentityId: string;
            machineId: string;
        } | undefined;
    };
    readonly "plugins.settings.secret.bind": {
        pluginId: string;
        localId: string;
        savedSecretId: string;
        scope?: {
            kind: 'account' | 'daemon';
        } | undefined;
        target?: {
            kind: 'account';
        } | {
            kind: 'daemon';
            serverIdentityId: string;
            machineId: string;
        } | undefined;
        secretDaemonTarget?: {
            kind: 'daemon';
            serverIdentityId: string;
            machineId: string;
        } | undefined;
        expectedRevision?: string | undefined;
    };
    readonly "plugins.settings.secret.unbind": {
        pluginId: string;
        localId: string;
        scope?: {
            kind: 'account' | 'daemon';
        } | undefined;
        target?: {
            kind: 'account';
        } | {
            kind: 'daemon';
            serverIdentityId: string;
            machineId: string;
        } | undefined;
        secretDaemonTarget?: {
            kind: 'daemon';
            serverIdentityId: string;
            machineId: string;
        } | undefined;
        expectedRevision?: string | undefined;
    };
    readonly "plugins.settings.secret.delete": {
        pluginId: string;
        localId: string;
        scope?: {
            kind: 'account' | 'daemon';
        } | undefined;
        target?: {
            kind: 'account';
        } | {
            kind: 'daemon';
            serverIdentityId: string;
            machineId: string;
        } | undefined;
        secretDaemonTarget?: {
            kind: 'daemon';
            serverIdentityId: string;
            machineId: string;
        } | undefined;
        expectedRevision?: string | undefined;
    };
};
export type PluginSettingsAdministrationActionResultById = {
    readonly "plugins.settings.list": {
        ok: true;
        kind: 'plugins.settings.list';
        data: {
            scope: {
                kind: 'account' | 'daemon';
            };
            target: {
                kind: 'account';
            } | {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            revision: string;
            fields: ({
                localId: string;
                secret: true;
                title?: string | undefined;
                description?: string | undefined;
            } | {
                localId: string;
                secret: false;
                value: string | number | boolean | readonly JsonValue[] | {
                    readonly [key: string]: JsonValue;
                } | null;
                title?: string | undefined;
                description?: string | undefined;
            })[];
        };
    } | {
        ok: true;
        kind: 'plugins.settings.get';
        data: {
            scope: {
                kind: 'account' | 'daemon';
            };
            target: {
                kind: 'account';
            } | {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            localId: string;
            revision: string;
            value: string | number | boolean | readonly JsonValue[] | {
                readonly [key: string]: JsonValue;
            } | null;
        };
    } | {
        ok: true;
        kind: 'plugins.settings.set';
        data: {
            scope: {
                kind: 'account' | 'daemon';
            };
            target: {
                kind: 'account';
            } | {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            localId: string;
            revision: string;
            application: {
                kind: 'live';
            };
        };
    } | {
        ok: true;
        kind: 'plugins.settings.reset';
        data: {
            scope: {
                kind: 'account' | 'daemon';
            };
            target: {
                kind: 'account';
            } | {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            localId: string;
            revision: string;
            application: {
                kind: 'live';
            };
        };
    } | {
        ok: true;
        kind: 'plugins.settings.secret.status';
        data: {
            localId: string;
            custody: 'account';
            target: {
                kind: 'account';
            };
            state: 'configured' | 'missing';
            revision: string;
        } | {
            localId: string;
            custody: 'daemon';
            target: {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            state: 'configured' | 'missing' | 'denied' | 'unavailable';
            revision: string;
        };
    } | {
        ok: true;
        kind: 'plugins.settings.secret.bind';
        data: {
            localId: string;
            custody: 'account';
            target: {
                kind: 'account';
            };
            revision: string;
            application: {
                kind: 'live';
            };
        };
    } | {
        ok: true;
        kind: 'plugins.settings.secret.unbind';
        data: {
            localId: string;
            custody: 'account';
            target: {
                kind: 'account';
            };
            revision: string;
            application: {
                kind: 'live';
            };
        };
    } | {
        ok: true;
        kind: 'plugins.settings.secret.delete';
        data: {
            localId: string;
            custody: 'account';
            target: {
                kind: 'account';
            };
            revision: string;
            application: {
                kind: 'live';
            };
        } | {
            localId: string;
            custody: 'daemon';
            target: {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            state: 'configured' | 'missing' | 'denied' | 'unavailable';
            revision: string;
            application: {
                kind: 'live';
            };
        };
    } | {
        ok: false;
        kind: 'plugins.settings.list' | 'plugins.settings.get' | 'plugins.settings.set' | 'plugins.settings.reset' | 'plugins.settings.secret.status' | 'plugins.settings.secret.bind' | 'plugins.settings.secret.unbind' | 'plugins.settings.secret.delete';
        errorCode: string;
        error: string;
    };
    readonly "plugins.settings.get": {
        ok: true;
        kind: 'plugins.settings.list';
        data: {
            scope: {
                kind: 'account' | 'daemon';
            };
            target: {
                kind: 'account';
            } | {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            revision: string;
            fields: ({
                localId: string;
                secret: true;
                title?: string | undefined;
                description?: string | undefined;
            } | {
                localId: string;
                secret: false;
                value: string | number | boolean | readonly JsonValue[] | {
                    readonly [key: string]: JsonValue;
                } | null;
                title?: string | undefined;
                description?: string | undefined;
            })[];
        };
    } | {
        ok: true;
        kind: 'plugins.settings.get';
        data: {
            scope: {
                kind: 'account' | 'daemon';
            };
            target: {
                kind: 'account';
            } | {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            localId: string;
            revision: string;
            value: string | number | boolean | readonly JsonValue[] | {
                readonly [key: string]: JsonValue;
            } | null;
        };
    } | {
        ok: true;
        kind: 'plugins.settings.set';
        data: {
            scope: {
                kind: 'account' | 'daemon';
            };
            target: {
                kind: 'account';
            } | {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            localId: string;
            revision: string;
            application: {
                kind: 'live';
            };
        };
    } | {
        ok: true;
        kind: 'plugins.settings.reset';
        data: {
            scope: {
                kind: 'account' | 'daemon';
            };
            target: {
                kind: 'account';
            } | {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            localId: string;
            revision: string;
            application: {
                kind: 'live';
            };
        };
    } | {
        ok: true;
        kind: 'plugins.settings.secret.status';
        data: {
            localId: string;
            custody: 'account';
            target: {
                kind: 'account';
            };
            state: 'configured' | 'missing';
            revision: string;
        } | {
            localId: string;
            custody: 'daemon';
            target: {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            state: 'configured' | 'missing' | 'denied' | 'unavailable';
            revision: string;
        };
    } | {
        ok: true;
        kind: 'plugins.settings.secret.bind';
        data: {
            localId: string;
            custody: 'account';
            target: {
                kind: 'account';
            };
            revision: string;
            application: {
                kind: 'live';
            };
        };
    } | {
        ok: true;
        kind: 'plugins.settings.secret.unbind';
        data: {
            localId: string;
            custody: 'account';
            target: {
                kind: 'account';
            };
            revision: string;
            application: {
                kind: 'live';
            };
        };
    } | {
        ok: true;
        kind: 'plugins.settings.secret.delete';
        data: {
            localId: string;
            custody: 'account';
            target: {
                kind: 'account';
            };
            revision: string;
            application: {
                kind: 'live';
            };
        } | {
            localId: string;
            custody: 'daemon';
            target: {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            state: 'configured' | 'missing' | 'denied' | 'unavailable';
            revision: string;
            application: {
                kind: 'live';
            };
        };
    } | {
        ok: false;
        kind: 'plugins.settings.list' | 'plugins.settings.get' | 'plugins.settings.set' | 'plugins.settings.reset' | 'plugins.settings.secret.status' | 'plugins.settings.secret.bind' | 'plugins.settings.secret.unbind' | 'plugins.settings.secret.delete';
        errorCode: string;
        error: string;
    };
    readonly "plugins.settings.set": {
        ok: true;
        kind: 'plugins.settings.list';
        data: {
            scope: {
                kind: 'account' | 'daemon';
            };
            target: {
                kind: 'account';
            } | {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            revision: string;
            fields: ({
                localId: string;
                secret: true;
                title?: string | undefined;
                description?: string | undefined;
            } | {
                localId: string;
                secret: false;
                value: string | number | boolean | readonly JsonValue[] | {
                    readonly [key: string]: JsonValue;
                } | null;
                title?: string | undefined;
                description?: string | undefined;
            })[];
        };
    } | {
        ok: true;
        kind: 'plugins.settings.get';
        data: {
            scope: {
                kind: 'account' | 'daemon';
            };
            target: {
                kind: 'account';
            } | {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            localId: string;
            revision: string;
            value: string | number | boolean | readonly JsonValue[] | {
                readonly [key: string]: JsonValue;
            } | null;
        };
    } | {
        ok: true;
        kind: 'plugins.settings.set';
        data: {
            scope: {
                kind: 'account' | 'daemon';
            };
            target: {
                kind: 'account';
            } | {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            localId: string;
            revision: string;
            application: {
                kind: 'live';
            };
        };
    } | {
        ok: true;
        kind: 'plugins.settings.reset';
        data: {
            scope: {
                kind: 'account' | 'daemon';
            };
            target: {
                kind: 'account';
            } | {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            localId: string;
            revision: string;
            application: {
                kind: 'live';
            };
        };
    } | {
        ok: true;
        kind: 'plugins.settings.secret.status';
        data: {
            localId: string;
            custody: 'account';
            target: {
                kind: 'account';
            };
            state: 'configured' | 'missing';
            revision: string;
        } | {
            localId: string;
            custody: 'daemon';
            target: {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            state: 'configured' | 'missing' | 'denied' | 'unavailable';
            revision: string;
        };
    } | {
        ok: true;
        kind: 'plugins.settings.secret.bind';
        data: {
            localId: string;
            custody: 'account';
            target: {
                kind: 'account';
            };
            revision: string;
            application: {
                kind: 'live';
            };
        };
    } | {
        ok: true;
        kind: 'plugins.settings.secret.unbind';
        data: {
            localId: string;
            custody: 'account';
            target: {
                kind: 'account';
            };
            revision: string;
            application: {
                kind: 'live';
            };
        };
    } | {
        ok: true;
        kind: 'plugins.settings.secret.delete';
        data: {
            localId: string;
            custody: 'account';
            target: {
                kind: 'account';
            };
            revision: string;
            application: {
                kind: 'live';
            };
        } | {
            localId: string;
            custody: 'daemon';
            target: {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            state: 'configured' | 'missing' | 'denied' | 'unavailable';
            revision: string;
            application: {
                kind: 'live';
            };
        };
    } | {
        ok: false;
        kind: 'plugins.settings.list' | 'plugins.settings.get' | 'plugins.settings.set' | 'plugins.settings.reset' | 'plugins.settings.secret.status' | 'plugins.settings.secret.bind' | 'plugins.settings.secret.unbind' | 'plugins.settings.secret.delete';
        errorCode: string;
        error: string;
    };
    readonly "plugins.settings.reset": {
        ok: true;
        kind: 'plugins.settings.list';
        data: {
            scope: {
                kind: 'account' | 'daemon';
            };
            target: {
                kind: 'account';
            } | {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            revision: string;
            fields: ({
                localId: string;
                secret: true;
                title?: string | undefined;
                description?: string | undefined;
            } | {
                localId: string;
                secret: false;
                value: string | number | boolean | readonly JsonValue[] | {
                    readonly [key: string]: JsonValue;
                } | null;
                title?: string | undefined;
                description?: string | undefined;
            })[];
        };
    } | {
        ok: true;
        kind: 'plugins.settings.get';
        data: {
            scope: {
                kind: 'account' | 'daemon';
            };
            target: {
                kind: 'account';
            } | {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            localId: string;
            revision: string;
            value: string | number | boolean | readonly JsonValue[] | {
                readonly [key: string]: JsonValue;
            } | null;
        };
    } | {
        ok: true;
        kind: 'plugins.settings.set';
        data: {
            scope: {
                kind: 'account' | 'daemon';
            };
            target: {
                kind: 'account';
            } | {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            localId: string;
            revision: string;
            application: {
                kind: 'live';
            };
        };
    } | {
        ok: true;
        kind: 'plugins.settings.reset';
        data: {
            scope: {
                kind: 'account' | 'daemon';
            };
            target: {
                kind: 'account';
            } | {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            localId: string;
            revision: string;
            application: {
                kind: 'live';
            };
        };
    } | {
        ok: true;
        kind: 'plugins.settings.secret.status';
        data: {
            localId: string;
            custody: 'account';
            target: {
                kind: 'account';
            };
            state: 'configured' | 'missing';
            revision: string;
        } | {
            localId: string;
            custody: 'daemon';
            target: {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            state: 'configured' | 'missing' | 'denied' | 'unavailable';
            revision: string;
        };
    } | {
        ok: true;
        kind: 'plugins.settings.secret.bind';
        data: {
            localId: string;
            custody: 'account';
            target: {
                kind: 'account';
            };
            revision: string;
            application: {
                kind: 'live';
            };
        };
    } | {
        ok: true;
        kind: 'plugins.settings.secret.unbind';
        data: {
            localId: string;
            custody: 'account';
            target: {
                kind: 'account';
            };
            revision: string;
            application: {
                kind: 'live';
            };
        };
    } | {
        ok: true;
        kind: 'plugins.settings.secret.delete';
        data: {
            localId: string;
            custody: 'account';
            target: {
                kind: 'account';
            };
            revision: string;
            application: {
                kind: 'live';
            };
        } | {
            localId: string;
            custody: 'daemon';
            target: {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            state: 'configured' | 'missing' | 'denied' | 'unavailable';
            revision: string;
            application: {
                kind: 'live';
            };
        };
    } | {
        ok: false;
        kind: 'plugins.settings.list' | 'plugins.settings.get' | 'plugins.settings.set' | 'plugins.settings.reset' | 'plugins.settings.secret.status' | 'plugins.settings.secret.bind' | 'plugins.settings.secret.unbind' | 'plugins.settings.secret.delete';
        errorCode: string;
        error: string;
    };
    readonly "plugins.settings.secret.status": {
        ok: true;
        kind: 'plugins.settings.list';
        data: {
            scope: {
                kind: 'account' | 'daemon';
            };
            target: {
                kind: 'account';
            } | {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            revision: string;
            fields: ({
                localId: string;
                secret: true;
                title?: string | undefined;
                description?: string | undefined;
            } | {
                localId: string;
                secret: false;
                value: string | number | boolean | readonly JsonValue[] | {
                    readonly [key: string]: JsonValue;
                } | null;
                title?: string | undefined;
                description?: string | undefined;
            })[];
        };
    } | {
        ok: true;
        kind: 'plugins.settings.get';
        data: {
            scope: {
                kind: 'account' | 'daemon';
            };
            target: {
                kind: 'account';
            } | {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            localId: string;
            revision: string;
            value: string | number | boolean | readonly JsonValue[] | {
                readonly [key: string]: JsonValue;
            } | null;
        };
    } | {
        ok: true;
        kind: 'plugins.settings.set';
        data: {
            scope: {
                kind: 'account' | 'daemon';
            };
            target: {
                kind: 'account';
            } | {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            localId: string;
            revision: string;
            application: {
                kind: 'live';
            };
        };
    } | {
        ok: true;
        kind: 'plugins.settings.reset';
        data: {
            scope: {
                kind: 'account' | 'daemon';
            };
            target: {
                kind: 'account';
            } | {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            localId: string;
            revision: string;
            application: {
                kind: 'live';
            };
        };
    } | {
        ok: true;
        kind: 'plugins.settings.secret.status';
        data: {
            localId: string;
            custody: 'account';
            target: {
                kind: 'account';
            };
            state: 'configured' | 'missing';
            revision: string;
        } | {
            localId: string;
            custody: 'daemon';
            target: {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            state: 'configured' | 'missing' | 'denied' | 'unavailable';
            revision: string;
        };
    } | {
        ok: true;
        kind: 'plugins.settings.secret.bind';
        data: {
            localId: string;
            custody: 'account';
            target: {
                kind: 'account';
            };
            revision: string;
            application: {
                kind: 'live';
            };
        };
    } | {
        ok: true;
        kind: 'plugins.settings.secret.unbind';
        data: {
            localId: string;
            custody: 'account';
            target: {
                kind: 'account';
            };
            revision: string;
            application: {
                kind: 'live';
            };
        };
    } | {
        ok: true;
        kind: 'plugins.settings.secret.delete';
        data: {
            localId: string;
            custody: 'account';
            target: {
                kind: 'account';
            };
            revision: string;
            application: {
                kind: 'live';
            };
        } | {
            localId: string;
            custody: 'daemon';
            target: {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            state: 'configured' | 'missing' | 'denied' | 'unavailable';
            revision: string;
            application: {
                kind: 'live';
            };
        };
    } | {
        ok: false;
        kind: 'plugins.settings.list' | 'plugins.settings.get' | 'plugins.settings.set' | 'plugins.settings.reset' | 'plugins.settings.secret.status' | 'plugins.settings.secret.bind' | 'plugins.settings.secret.unbind' | 'plugins.settings.secret.delete';
        errorCode: string;
        error: string;
    };
    readonly "plugins.settings.secret.bind": {
        ok: true;
        kind: 'plugins.settings.list';
        data: {
            scope: {
                kind: 'account' | 'daemon';
            };
            target: {
                kind: 'account';
            } | {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            revision: string;
            fields: ({
                localId: string;
                secret: true;
                title?: string | undefined;
                description?: string | undefined;
            } | {
                localId: string;
                secret: false;
                value: string | number | boolean | readonly JsonValue[] | {
                    readonly [key: string]: JsonValue;
                } | null;
                title?: string | undefined;
                description?: string | undefined;
            })[];
        };
    } | {
        ok: true;
        kind: 'plugins.settings.get';
        data: {
            scope: {
                kind: 'account' | 'daemon';
            };
            target: {
                kind: 'account';
            } | {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            localId: string;
            revision: string;
            value: string | number | boolean | readonly JsonValue[] | {
                readonly [key: string]: JsonValue;
            } | null;
        };
    } | {
        ok: true;
        kind: 'plugins.settings.set';
        data: {
            scope: {
                kind: 'account' | 'daemon';
            };
            target: {
                kind: 'account';
            } | {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            localId: string;
            revision: string;
            application: {
                kind: 'live';
            };
        };
    } | {
        ok: true;
        kind: 'plugins.settings.reset';
        data: {
            scope: {
                kind: 'account' | 'daemon';
            };
            target: {
                kind: 'account';
            } | {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            localId: string;
            revision: string;
            application: {
                kind: 'live';
            };
        };
    } | {
        ok: true;
        kind: 'plugins.settings.secret.status';
        data: {
            localId: string;
            custody: 'account';
            target: {
                kind: 'account';
            };
            state: 'configured' | 'missing';
            revision: string;
        } | {
            localId: string;
            custody: 'daemon';
            target: {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            state: 'configured' | 'missing' | 'denied' | 'unavailable';
            revision: string;
        };
    } | {
        ok: true;
        kind: 'plugins.settings.secret.bind';
        data: {
            localId: string;
            custody: 'account';
            target: {
                kind: 'account';
            };
            revision: string;
            application: {
                kind: 'live';
            };
        };
    } | {
        ok: true;
        kind: 'plugins.settings.secret.unbind';
        data: {
            localId: string;
            custody: 'account';
            target: {
                kind: 'account';
            };
            revision: string;
            application: {
                kind: 'live';
            };
        };
    } | {
        ok: true;
        kind: 'plugins.settings.secret.delete';
        data: {
            localId: string;
            custody: 'account';
            target: {
                kind: 'account';
            };
            revision: string;
            application: {
                kind: 'live';
            };
        } | {
            localId: string;
            custody: 'daemon';
            target: {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            state: 'configured' | 'missing' | 'denied' | 'unavailable';
            revision: string;
            application: {
                kind: 'live';
            };
        };
    } | {
        ok: false;
        kind: 'plugins.settings.list' | 'plugins.settings.get' | 'plugins.settings.set' | 'plugins.settings.reset' | 'plugins.settings.secret.status' | 'plugins.settings.secret.bind' | 'plugins.settings.secret.unbind' | 'plugins.settings.secret.delete';
        errorCode: string;
        error: string;
    };
    readonly "plugins.settings.secret.unbind": {
        ok: true;
        kind: 'plugins.settings.list';
        data: {
            scope: {
                kind: 'account' | 'daemon';
            };
            target: {
                kind: 'account';
            } | {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            revision: string;
            fields: ({
                localId: string;
                secret: true;
                title?: string | undefined;
                description?: string | undefined;
            } | {
                localId: string;
                secret: false;
                value: string | number | boolean | readonly JsonValue[] | {
                    readonly [key: string]: JsonValue;
                } | null;
                title?: string | undefined;
                description?: string | undefined;
            })[];
        };
    } | {
        ok: true;
        kind: 'plugins.settings.get';
        data: {
            scope: {
                kind: 'account' | 'daemon';
            };
            target: {
                kind: 'account';
            } | {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            localId: string;
            revision: string;
            value: string | number | boolean | readonly JsonValue[] | {
                readonly [key: string]: JsonValue;
            } | null;
        };
    } | {
        ok: true;
        kind: 'plugins.settings.set';
        data: {
            scope: {
                kind: 'account' | 'daemon';
            };
            target: {
                kind: 'account';
            } | {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            localId: string;
            revision: string;
            application: {
                kind: 'live';
            };
        };
    } | {
        ok: true;
        kind: 'plugins.settings.reset';
        data: {
            scope: {
                kind: 'account' | 'daemon';
            };
            target: {
                kind: 'account';
            } | {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            localId: string;
            revision: string;
            application: {
                kind: 'live';
            };
        };
    } | {
        ok: true;
        kind: 'plugins.settings.secret.status';
        data: {
            localId: string;
            custody: 'account';
            target: {
                kind: 'account';
            };
            state: 'configured' | 'missing';
            revision: string;
        } | {
            localId: string;
            custody: 'daemon';
            target: {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            state: 'configured' | 'missing' | 'denied' | 'unavailable';
            revision: string;
        };
    } | {
        ok: true;
        kind: 'plugins.settings.secret.bind';
        data: {
            localId: string;
            custody: 'account';
            target: {
                kind: 'account';
            };
            revision: string;
            application: {
                kind: 'live';
            };
        };
    } | {
        ok: true;
        kind: 'plugins.settings.secret.unbind';
        data: {
            localId: string;
            custody: 'account';
            target: {
                kind: 'account';
            };
            revision: string;
            application: {
                kind: 'live';
            };
        };
    } | {
        ok: true;
        kind: 'plugins.settings.secret.delete';
        data: {
            localId: string;
            custody: 'account';
            target: {
                kind: 'account';
            };
            revision: string;
            application: {
                kind: 'live';
            };
        } | {
            localId: string;
            custody: 'daemon';
            target: {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            state: 'configured' | 'missing' | 'denied' | 'unavailable';
            revision: string;
            application: {
                kind: 'live';
            };
        };
    } | {
        ok: false;
        kind: 'plugins.settings.list' | 'plugins.settings.get' | 'plugins.settings.set' | 'plugins.settings.reset' | 'plugins.settings.secret.status' | 'plugins.settings.secret.bind' | 'plugins.settings.secret.unbind' | 'plugins.settings.secret.delete';
        errorCode: string;
        error: string;
    };
    readonly "plugins.settings.secret.delete": {
        ok: true;
        kind: 'plugins.settings.list';
        data: {
            scope: {
                kind: 'account' | 'daemon';
            };
            target: {
                kind: 'account';
            } | {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            revision: string;
            fields: ({
                localId: string;
                secret: true;
                title?: string | undefined;
                description?: string | undefined;
            } | {
                localId: string;
                secret: false;
                value: string | number | boolean | readonly JsonValue[] | {
                    readonly [key: string]: JsonValue;
                } | null;
                title?: string | undefined;
                description?: string | undefined;
            })[];
        };
    } | {
        ok: true;
        kind: 'plugins.settings.get';
        data: {
            scope: {
                kind: 'account' | 'daemon';
            };
            target: {
                kind: 'account';
            } | {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            localId: string;
            revision: string;
            value: string | number | boolean | readonly JsonValue[] | {
                readonly [key: string]: JsonValue;
            } | null;
        };
    } | {
        ok: true;
        kind: 'plugins.settings.set';
        data: {
            scope: {
                kind: 'account' | 'daemon';
            };
            target: {
                kind: 'account';
            } | {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            localId: string;
            revision: string;
            application: {
                kind: 'live';
            };
        };
    } | {
        ok: true;
        kind: 'plugins.settings.reset';
        data: {
            scope: {
                kind: 'account' | 'daemon';
            };
            target: {
                kind: 'account';
            } | {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            localId: string;
            revision: string;
            application: {
                kind: 'live';
            };
        };
    } | {
        ok: true;
        kind: 'plugins.settings.secret.status';
        data: {
            localId: string;
            custody: 'account';
            target: {
                kind: 'account';
            };
            state: 'configured' | 'missing';
            revision: string;
        } | {
            localId: string;
            custody: 'daemon';
            target: {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            state: 'configured' | 'missing' | 'denied' | 'unavailable';
            revision: string;
        };
    } | {
        ok: true;
        kind: 'plugins.settings.secret.bind';
        data: {
            localId: string;
            custody: 'account';
            target: {
                kind: 'account';
            };
            revision: string;
            application: {
                kind: 'live';
            };
        };
    } | {
        ok: true;
        kind: 'plugins.settings.secret.unbind';
        data: {
            localId: string;
            custody: 'account';
            target: {
                kind: 'account';
            };
            revision: string;
            application: {
                kind: 'live';
            };
        };
    } | {
        ok: true;
        kind: 'plugins.settings.secret.delete';
        data: {
            localId: string;
            custody: 'account';
            target: {
                kind: 'account';
            };
            revision: string;
            application: {
                kind: 'live';
            };
        } | {
            localId: string;
            custody: 'daemon';
            target: {
                kind: 'daemon';
                serverIdentityId: string;
                machineId: string;
            };
            state: 'configured' | 'missing' | 'denied' | 'unavailable';
            revision: string;
            application: {
                kind: 'live';
            };
        };
    } | {
        ok: false;
        kind: 'plugins.settings.list' | 'plugins.settings.get' | 'plugins.settings.set' | 'plugins.settings.reset' | 'plugins.settings.secret.status' | 'plugins.settings.secret.bind' | 'plugins.settings.secret.unbind' | 'plugins.settings.secret.delete';
        errorCode: string;
        error: string;
    };
};
