// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.

import type { PluginJsonValueV2 } from './jsonSchema.generated.js';

export type PluginDevLoopActionInputById = {
    readonly "plugins.scaffold": {
        targetDir: string;
        id: string;
        name: string;
        ui?: 'declarative' | 'hostedWeb' | 'reactNative' | undefined;
        template?: 'session-agent' | undefined;
    };
    readonly "plugins.install": {
        path: string;
        dev?: boolean | undefined;
        dryRun?: boolean | undefined;
        force?: boolean | undefined;
    };
    readonly "plugins.uninstall": {
        pluginId: string;
    };
    readonly "plugins.dev.submit": {
        projectRoot: string;
        sdkRegistryOrigin?: string | undefined;
    };
    readonly "plugins.dev.install": {
        projectRoot: string;
        sdkRegistryOrigin?: string | undefined;
    };
    readonly "plugins.dev.typecheck": {
        projectRoot: string;
        sdkRegistryOrigin?: string | undefined;
    };
    readonly "plugins.dev.build": {
        projectRoot: string;
        sdkRegistryOrigin?: string | undefined;
    };
    readonly "plugins.dev.test": {
        projectRoot: string;
        sdkRegistryOrigin?: string | undefined;
    };
    readonly "plugins.doctor": {
        locator: string;
    };
    readonly "plugins.pack": {
        locator: string;
        outPath?: string | undefined;
        sdkRegistryOrigin?: string | undefined;
    };
    readonly "plugins.reload": {
        pluginId: string;
    };
    readonly "plugins.list": Record<string, never>;
    readonly "plugins.change.status": {
        pendingChangeId: string;
    };
    readonly "plugins.sessionHooks.status.get": {
        intent: 'passive_inventory';
        agent?: {
            localId: string;
        } | undefined;
        cursor?: string | undefined;
        limit?: number | undefined;
    } | {
        intent: 'install_preview';
        agent: {
            localId: string;
        };
    } | {
        intent: 'installation_recheck';
        agent: {
            localId: string;
        };
        installationId: string;
    };
    readonly "plugins.sessionHooks.install": {
        agent: {
            localId: string;
        };
        expectedPreviewId: string;
    };
    readonly "plugins.sessionHooks.disable": {
        agent: {
            localId: string;
        };
        installationId: string;
    };
    readonly "plugins.sessionHooks.enable": {
        agent: {
            localId: string;
        };
        installationId: string;
    };
    readonly "plugins.sessionHooks.uninstall": {
        agent: {
            localId: string;
        };
        installationId: string;
    };
};
export type PluginDevLoopActionResultById = {
    readonly "plugins.scaffold": {
        [x: string]: unknown;
        ok: false;
        kind: 'plugins_install' | 'plugins_dev_submit' | 'plugins_reload';
        outcome: 'reviewRequired';
        pendingReview: {
            [x: string]: unknown;
            kind: 'reviewRequired';
            reviewKind: 'projectTrust' | 'installation';
            pendingChangeId: string;
            review: {
                [x: string]: unknown;
            };
        };
        pendingChangeId?: undefined;
        review?: undefined;
    } | {
        [x: string]: unknown;
        ok: true;
        kind: 'plugins_change_status';
        status: {
            [x: string]: unknown;
        };
    } | {
        [x: string]: unknown;
        ok: boolean;
        kind: 'plugins_install' | 'plugins_dev_submit' | 'plugins_reload' | 'plugins_scaffold' | 'plugins_uninstall' | 'plugins_dev_install' | 'plugins_dev_typecheck' | 'plugins_dev_build' | 'plugins_dev_test' | 'plugins_doctor' | 'plugins_pack' | 'plugins_list';
        outcome?: 'applied' | 'failed' | undefined;
        pendingReview?: undefined;
        pendingChangeId?: undefined;
        review?: undefined;
    };
    readonly "plugins.install": {
        [x: string]: unknown;
        ok: false;
        kind: 'plugins_install' | 'plugins_dev_submit' | 'plugins_reload';
        outcome: 'reviewRequired';
        pendingReview: {
            [x: string]: unknown;
            kind: 'reviewRequired';
            reviewKind: 'projectTrust' | 'installation';
            pendingChangeId: string;
            review: {
                [x: string]: unknown;
            };
        };
        pendingChangeId?: undefined;
        review?: undefined;
    } | {
        [x: string]: unknown;
        ok: true;
        kind: 'plugins_change_status';
        status: {
            [x: string]: unknown;
        };
    } | {
        [x: string]: unknown;
        ok: boolean;
        kind: 'plugins_install' | 'plugins_dev_submit' | 'plugins_reload' | 'plugins_scaffold' | 'plugins_uninstall' | 'plugins_dev_install' | 'plugins_dev_typecheck' | 'plugins_dev_build' | 'plugins_dev_test' | 'plugins_doctor' | 'plugins_pack' | 'plugins_list';
        outcome?: 'applied' | 'failed' | undefined;
        pendingReview?: undefined;
        pendingChangeId?: undefined;
        review?: undefined;
    };
    readonly "plugins.uninstall": {
        [x: string]: unknown;
        ok: false;
        kind: 'plugins_install' | 'plugins_dev_submit' | 'plugins_reload';
        outcome: 'reviewRequired';
        pendingReview: {
            [x: string]: unknown;
            kind: 'reviewRequired';
            reviewKind: 'projectTrust' | 'installation';
            pendingChangeId: string;
            review: {
                [x: string]: unknown;
            };
        };
        pendingChangeId?: undefined;
        review?: undefined;
    } | {
        [x: string]: unknown;
        ok: true;
        kind: 'plugins_change_status';
        status: {
            [x: string]: unknown;
        };
    } | {
        [x: string]: unknown;
        ok: boolean;
        kind: 'plugins_install' | 'plugins_dev_submit' | 'plugins_reload' | 'plugins_scaffold' | 'plugins_uninstall' | 'plugins_dev_install' | 'plugins_dev_typecheck' | 'plugins_dev_build' | 'plugins_dev_test' | 'plugins_doctor' | 'plugins_pack' | 'plugins_list';
        outcome?: 'applied' | 'failed' | undefined;
        pendingReview?: undefined;
        pendingChangeId?: undefined;
        review?: undefined;
    };
    readonly "plugins.dev.submit": {
        [x: string]: unknown;
        ok: false;
        kind: 'plugins_install' | 'plugins_dev_submit' | 'plugins_reload';
        outcome: 'reviewRequired';
        pendingReview: {
            [x: string]: unknown;
            kind: 'reviewRequired';
            reviewKind: 'projectTrust' | 'installation';
            pendingChangeId: string;
            review: {
                [x: string]: unknown;
            };
        };
        pendingChangeId?: undefined;
        review?: undefined;
    } | {
        [x: string]: unknown;
        ok: true;
        kind: 'plugins_change_status';
        status: {
            [x: string]: unknown;
        };
    } | {
        [x: string]: unknown;
        ok: boolean;
        kind: 'plugins_install' | 'plugins_dev_submit' | 'plugins_reload' | 'plugins_scaffold' | 'plugins_uninstall' | 'plugins_dev_install' | 'plugins_dev_typecheck' | 'plugins_dev_build' | 'plugins_dev_test' | 'plugins_doctor' | 'plugins_pack' | 'plugins_list';
        outcome?: 'applied' | 'failed' | undefined;
        pendingReview?: undefined;
        pendingChangeId?: undefined;
        review?: undefined;
    };
    readonly "plugins.dev.install": {
        [x: string]: unknown;
        ok: false;
        kind: 'plugins_install' | 'plugins_dev_submit' | 'plugins_reload';
        outcome: 'reviewRequired';
        pendingReview: {
            [x: string]: unknown;
            kind: 'reviewRequired';
            reviewKind: 'projectTrust' | 'installation';
            pendingChangeId: string;
            review: {
                [x: string]: unknown;
            };
        };
        pendingChangeId?: undefined;
        review?: undefined;
    } | {
        [x: string]: unknown;
        ok: true;
        kind: 'plugins_change_status';
        status: {
            [x: string]: unknown;
        };
    } | {
        [x: string]: unknown;
        ok: boolean;
        kind: 'plugins_install' | 'plugins_dev_submit' | 'plugins_reload' | 'plugins_scaffold' | 'plugins_uninstall' | 'plugins_dev_install' | 'plugins_dev_typecheck' | 'plugins_dev_build' | 'plugins_dev_test' | 'plugins_doctor' | 'plugins_pack' | 'plugins_list';
        outcome?: 'applied' | 'failed' | undefined;
        pendingReview?: undefined;
        pendingChangeId?: undefined;
        review?: undefined;
    };
    readonly "plugins.dev.typecheck": {
        [x: string]: unknown;
        ok: false;
        kind: 'plugins_install' | 'plugins_dev_submit' | 'plugins_reload';
        outcome: 'reviewRequired';
        pendingReview: {
            [x: string]: unknown;
            kind: 'reviewRequired';
            reviewKind: 'projectTrust' | 'installation';
            pendingChangeId: string;
            review: {
                [x: string]: unknown;
            };
        };
        pendingChangeId?: undefined;
        review?: undefined;
    } | {
        [x: string]: unknown;
        ok: true;
        kind: 'plugins_change_status';
        status: {
            [x: string]: unknown;
        };
    } | {
        [x: string]: unknown;
        ok: boolean;
        kind: 'plugins_install' | 'plugins_dev_submit' | 'plugins_reload' | 'plugins_scaffold' | 'plugins_uninstall' | 'plugins_dev_install' | 'plugins_dev_typecheck' | 'plugins_dev_build' | 'plugins_dev_test' | 'plugins_doctor' | 'plugins_pack' | 'plugins_list';
        outcome?: 'applied' | 'failed' | undefined;
        pendingReview?: undefined;
        pendingChangeId?: undefined;
        review?: undefined;
    };
    readonly "plugins.dev.build": {
        [x: string]: unknown;
        ok: false;
        kind: 'plugins_install' | 'plugins_dev_submit' | 'plugins_reload';
        outcome: 'reviewRequired';
        pendingReview: {
            [x: string]: unknown;
            kind: 'reviewRequired';
            reviewKind: 'projectTrust' | 'installation';
            pendingChangeId: string;
            review: {
                [x: string]: unknown;
            };
        };
        pendingChangeId?: undefined;
        review?: undefined;
    } | {
        [x: string]: unknown;
        ok: true;
        kind: 'plugins_change_status';
        status: {
            [x: string]: unknown;
        };
    } | {
        [x: string]: unknown;
        ok: boolean;
        kind: 'plugins_install' | 'plugins_dev_submit' | 'plugins_reload' | 'plugins_scaffold' | 'plugins_uninstall' | 'plugins_dev_install' | 'plugins_dev_typecheck' | 'plugins_dev_build' | 'plugins_dev_test' | 'plugins_doctor' | 'plugins_pack' | 'plugins_list';
        outcome?: 'applied' | 'failed' | undefined;
        pendingReview?: undefined;
        pendingChangeId?: undefined;
        review?: undefined;
    };
    readonly "plugins.dev.test": {
        [x: string]: unknown;
        ok: false;
        kind: 'plugins_install' | 'plugins_dev_submit' | 'plugins_reload';
        outcome: 'reviewRequired';
        pendingReview: {
            [x: string]: unknown;
            kind: 'reviewRequired';
            reviewKind: 'projectTrust' | 'installation';
            pendingChangeId: string;
            review: {
                [x: string]: unknown;
            };
        };
        pendingChangeId?: undefined;
        review?: undefined;
    } | {
        [x: string]: unknown;
        ok: true;
        kind: 'plugins_change_status';
        status: {
            [x: string]: unknown;
        };
    } | {
        [x: string]: unknown;
        ok: boolean;
        kind: 'plugins_install' | 'plugins_dev_submit' | 'plugins_reload' | 'plugins_scaffold' | 'plugins_uninstall' | 'plugins_dev_install' | 'plugins_dev_typecheck' | 'plugins_dev_build' | 'plugins_dev_test' | 'plugins_doctor' | 'plugins_pack' | 'plugins_list';
        outcome?: 'applied' | 'failed' | undefined;
        pendingReview?: undefined;
        pendingChangeId?: undefined;
        review?: undefined;
    };
    readonly "plugins.doctor": {
        [x: string]: unknown;
        ok: false;
        kind: 'plugins_install' | 'plugins_dev_submit' | 'plugins_reload';
        outcome: 'reviewRequired';
        pendingReview: {
            [x: string]: unknown;
            kind: 'reviewRequired';
            reviewKind: 'projectTrust' | 'installation';
            pendingChangeId: string;
            review: {
                [x: string]: unknown;
            };
        };
        pendingChangeId?: undefined;
        review?: undefined;
    } | {
        [x: string]: unknown;
        ok: true;
        kind: 'plugins_change_status';
        status: {
            [x: string]: unknown;
        };
    } | {
        [x: string]: unknown;
        ok: boolean;
        kind: 'plugins_install' | 'plugins_dev_submit' | 'plugins_reload' | 'plugins_scaffold' | 'plugins_uninstall' | 'plugins_dev_install' | 'plugins_dev_typecheck' | 'plugins_dev_build' | 'plugins_dev_test' | 'plugins_doctor' | 'plugins_pack' | 'plugins_list';
        outcome?: 'applied' | 'failed' | undefined;
        pendingReview?: undefined;
        pendingChangeId?: undefined;
        review?: undefined;
    };
    readonly "plugins.pack": {
        [x: string]: unknown;
        ok: false;
        kind: 'plugins_install' | 'plugins_dev_submit' | 'plugins_reload';
        outcome: 'reviewRequired';
        pendingReview: {
            [x: string]: unknown;
            kind: 'reviewRequired';
            reviewKind: 'projectTrust' | 'installation';
            pendingChangeId: string;
            review: {
                [x: string]: unknown;
            };
        };
        pendingChangeId?: undefined;
        review?: undefined;
    } | {
        [x: string]: unknown;
        ok: true;
        kind: 'plugins_change_status';
        status: {
            [x: string]: unknown;
        };
    } | {
        [x: string]: unknown;
        ok: boolean;
        kind: 'plugins_install' | 'plugins_dev_submit' | 'plugins_reload' | 'plugins_scaffold' | 'plugins_uninstall' | 'plugins_dev_install' | 'plugins_dev_typecheck' | 'plugins_dev_build' | 'plugins_dev_test' | 'plugins_doctor' | 'plugins_pack' | 'plugins_list';
        outcome?: 'applied' | 'failed' | undefined;
        pendingReview?: undefined;
        pendingChangeId?: undefined;
        review?: undefined;
    };
    readonly "plugins.reload": {
        [x: string]: unknown;
        ok: false;
        kind: 'plugins_install' | 'plugins_dev_submit' | 'plugins_reload';
        outcome: 'reviewRequired';
        pendingReview: {
            [x: string]: unknown;
            kind: 'reviewRequired';
            reviewKind: 'projectTrust' | 'installation';
            pendingChangeId: string;
            review: {
                [x: string]: unknown;
            };
        };
        pendingChangeId?: undefined;
        review?: undefined;
    } | {
        [x: string]: unknown;
        ok: true;
        kind: 'plugins_change_status';
        status: {
            [x: string]: unknown;
        };
    } | {
        [x: string]: unknown;
        ok: boolean;
        kind: 'plugins_install' | 'plugins_dev_submit' | 'plugins_reload' | 'plugins_scaffold' | 'plugins_uninstall' | 'plugins_dev_install' | 'plugins_dev_typecheck' | 'plugins_dev_build' | 'plugins_dev_test' | 'plugins_doctor' | 'plugins_pack' | 'plugins_list';
        outcome?: 'applied' | 'failed' | undefined;
        pendingReview?: undefined;
        pendingChangeId?: undefined;
        review?: undefined;
    };
    readonly "plugins.list": {
        [x: string]: unknown;
        ok: false;
        kind: 'plugins_install' | 'plugins_dev_submit' | 'plugins_reload';
        outcome: 'reviewRequired';
        pendingReview: {
            [x: string]: unknown;
            kind: 'reviewRequired';
            reviewKind: 'projectTrust' | 'installation';
            pendingChangeId: string;
            review: {
                [x: string]: unknown;
            };
        };
        pendingChangeId?: undefined;
        review?: undefined;
    } | {
        [x: string]: unknown;
        ok: true;
        kind: 'plugins_change_status';
        status: {
            [x: string]: unknown;
        };
    } | {
        [x: string]: unknown;
        ok: boolean;
        kind: 'plugins_install' | 'plugins_dev_submit' | 'plugins_reload' | 'plugins_scaffold' | 'plugins_uninstall' | 'plugins_dev_install' | 'plugins_dev_typecheck' | 'plugins_dev_build' | 'plugins_dev_test' | 'plugins_doctor' | 'plugins_pack' | 'plugins_list';
        outcome?: 'applied' | 'failed' | undefined;
        pendingReview?: undefined;
        pendingChangeId?: undefined;
        review?: undefined;
    };
    readonly "plugins.change.status": {
        [x: string]: unknown;
        ok: false;
        kind: 'plugins_install' | 'plugins_dev_submit' | 'plugins_reload';
        outcome: 'reviewRequired';
        pendingReview: {
            [x: string]: unknown;
            kind: 'reviewRequired';
            reviewKind: 'projectTrust' | 'installation';
            pendingChangeId: string;
            review: {
                [x: string]: unknown;
            };
        };
        pendingChangeId?: undefined;
        review?: undefined;
    } | {
        [x: string]: unknown;
        ok: true;
        kind: 'plugins_change_status';
        status: {
            [x: string]: unknown;
        };
    } | {
        [x: string]: unknown;
        ok: boolean;
        kind: 'plugins_install' | 'plugins_dev_submit' | 'plugins_reload' | 'plugins_scaffold' | 'plugins_uninstall' | 'plugins_dev_install' | 'plugins_dev_typecheck' | 'plugins_dev_build' | 'plugins_dev_test' | 'plugins_doctor' | 'plugins_pack' | 'plugins_list';
        outcome?: 'applied' | 'failed' | undefined;
        pendingReview?: undefined;
        pendingChangeId?: undefined;
        review?: undefined;
    };
    readonly "plugins.sessionHooks.status.get": {
        ok: true;
        rows: {
            agent: {
                pluginId: string;
                localId: string;
            };
            status: {
                state: 'not_installed';
                installPreview?: Readonly<{
                    previewId: string;
                    targets: readonly Readonly<{
                        targetId: string;
                        absolutePath: string;
                        changes: readonly Readonly<{
                            kind: 'append_json_array_entry';
                            collectionId: string;
                            eventId: string;
                            nativeEventName: string;
                            entry: Readonly<{
                                matcher: string | null;
                                hooks: readonly [
                                    Readonly<{
                                        type: 'command';
                                        command: string;
                                        timeout: number;
                                    }>
                                ];
                            }>;
                        }>[];
                    }>[];
                }> | undefined;
            } | {
                state: 'installed_enabled';
                installationId: string;
            } | {
                state: 'installed_disabled';
                installationId: string;
            } | {
                state: 'needs_attention';
                diagnostic: {
                    code: string;
                    severity: 'error' | 'info' | 'warning';
                    message?: string | undefined;
                    details?: PluginJsonValueV2 | undefined;
                    remediation?: {
                        kind: 'retry';
                    } | {
                        kind: 'openSettings';
                        path: string;
                    } | {
                        kind: 'selectAccount';
                        service: {
                            pluginId: string;
                            localId: string;
                        };
                    } | {
                        kind: 'installDependency';
                        dependencyId: string;
                    } | {
                        kind: 'openUrl';
                        url: string;
                    } | undefined;
                };
                installationId?: string | undefined;
            } | {
                state: 'unsupported';
                reason: 'version_unsupported' | 'installation_unsupported';
            } | {
                state: 'unavailable';
                installationId: string;
            };
        }[];
        nextCursor: string | null;
        diagnostics: {
            code: 'installation_record_invalid' | 'installation_record_read_failed';
            retryable: boolean;
        }[];
    } | {
        ok: false;
        diagnostic: {
            code: 'version_unsupported' | 'installation_unsupported' | 'feature_disabled' | 'agent_unavailable' | 'invalid_config' | 'concurrent_edit' | 'listener_unavailable' | 'permission_denied' | 'installation_replaced' | 'operation_failed';
            retryable: boolean;
        };
    };
    readonly "plugins.sessionHooks.install": {
        ok: false;
        diagnostic: {
            code: 'version_unsupported' | 'installation_unsupported' | 'feature_disabled' | 'agent_unavailable' | 'invalid_config' | 'concurrent_edit' | 'listener_unavailable' | 'permission_denied' | 'installation_replaced' | 'operation_failed';
            retryable: boolean;
        };
    } | {
        ok: true;
        status: {
            state: 'installed_enabled';
            installationId: string;
        } | {
            state: 'installed_disabled';
            installationId: string;
        } | {
            state: 'needs_attention';
            diagnostic: {
                code: string;
                severity: 'error' | 'info' | 'warning';
                message?: string | undefined;
                details?: PluginJsonValueV2 | undefined;
                remediation?: {
                    kind: 'retry';
                } | {
                    kind: 'openSettings';
                    path: string;
                } | {
                    kind: 'selectAccount';
                    service: {
                        pluginId: string;
                        localId: string;
                    };
                } | {
                    kind: 'installDependency';
                    dependencyId: string;
                } | {
                    kind: 'openUrl';
                    url: string;
                } | undefined;
            };
            installationId: string;
        };
    };
    readonly "plugins.sessionHooks.disable": {
        ok: false;
        diagnostic: {
            code: 'version_unsupported' | 'installation_unsupported' | 'feature_disabled' | 'agent_unavailable' | 'invalid_config' | 'concurrent_edit' | 'listener_unavailable' | 'permission_denied' | 'installation_replaced' | 'operation_failed';
            retryable: boolean;
        };
    } | {
        ok: true;
        status: {
            state: 'installed_enabled';
            installationId: string;
        } | {
            state: 'installed_disabled';
            installationId: string;
        } | {
            state: 'needs_attention';
            diagnostic: {
                code: string;
                severity: 'error' | 'info' | 'warning';
                message?: string | undefined;
                details?: PluginJsonValueV2 | undefined;
                remediation?: {
                    kind: 'retry';
                } | {
                    kind: 'openSettings';
                    path: string;
                } | {
                    kind: 'selectAccount';
                    service: {
                        pluginId: string;
                        localId: string;
                    };
                } | {
                    kind: 'installDependency';
                    dependencyId: string;
                } | {
                    kind: 'openUrl';
                    url: string;
                } | undefined;
            };
            installationId: string;
        };
    };
    readonly "plugins.sessionHooks.enable": {
        ok: false;
        diagnostic: {
            code: 'version_unsupported' | 'installation_unsupported' | 'feature_disabled' | 'agent_unavailable' | 'invalid_config' | 'concurrent_edit' | 'listener_unavailable' | 'permission_denied' | 'installation_replaced' | 'operation_failed';
            retryable: boolean;
        };
    } | {
        ok: true;
        status: {
            state: 'installed_enabled';
            installationId: string;
        } | {
            state: 'installed_disabled';
            installationId: string;
        } | {
            state: 'needs_attention';
            diagnostic: {
                code: string;
                severity: 'error' | 'info' | 'warning';
                message?: string | undefined;
                details?: PluginJsonValueV2 | undefined;
                remediation?: {
                    kind: 'retry';
                } | {
                    kind: 'openSettings';
                    path: string;
                } | {
                    kind: 'selectAccount';
                    service: {
                        pluginId: string;
                        localId: string;
                    };
                } | {
                    kind: 'installDependency';
                    dependencyId: string;
                } | {
                    kind: 'openUrl';
                    url: string;
                } | undefined;
            };
            installationId: string;
        };
    };
    readonly "plugins.sessionHooks.uninstall": {
        ok: false;
        diagnostic: {
            code: 'version_unsupported' | 'installation_unsupported' | 'feature_disabled' | 'agent_unavailable' | 'invalid_config' | 'concurrent_edit' | 'listener_unavailable' | 'permission_denied' | 'installation_replaced' | 'operation_failed';
            retryable: boolean;
        };
    } | {
        ok: true;
        status: {
            state: 'not_installed';
        };
    };
};
