// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.

import type { JsonValue } from '../../identity.js';

export type PromptLibraryActionInputById = {
    readonly "prompt_doc.get": {
        artifactId: string;
    };
    readonly "prompt_doc.update": {
        [x: string]: unknown;
        artifactId: string;
        title: string;
        markdown: string;
        folderId?: string | null | undefined;
        tags?: string[] | undefined;
    };
    readonly "prompt_bundle.update": {
        [x: string]: unknown;
        artifactId: string;
        title: string;
        skillMarkdown: string;
        folderId?: string | null | undefined;
        tags?: string[] | undefined;
    };
    readonly "prompt_asset.export": {
        [x: string]: unknown;
        artifactId: string;
        machineId: string;
        assetTypeId: string;
        scope: 'user' | 'project';
        directory?: string | undefined;
        targetPath?: string | undefined;
        targetName?: string | undefined;
        installMode?: 'copy' | 'symlink' | undefined;
    };
    readonly "prompt_registry.install": {
        [x: string]: unknown;
        machineId: string;
        sourceId: string;
        itemId: string;
        configuredSources?: {
            [x: string]: unknown;
            id: string;
            adapterId: string;
            title: string;
            enabled?: boolean | undefined;
            config?: Record<string, unknown> | undefined;
        }[] | undefined;
        installTarget?: {
            assetTypeId: string;
            scope: 'user' | 'project';
            targetName: string;
            directory?: string | undefined;
            installMode?: 'copy' | 'symlink' | undefined;
        } | undefined;
    };
};
export type PromptLibraryActionResultById = {
    readonly "prompt_doc.get": {
        ok: true;
        artifactId: string;
        title: string;
        markdown: string;
    };
    readonly "prompt_doc.update": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "prompt_bundle.update": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "prompt_asset.export": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "prompt_registry.install": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
};
