// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.


// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
export type ScmDiffSummaryActionInputById = {
    readonly "scm.diffSummary.generate": {
        [x: string]: unknown;
        cwd: string;
        source: {
            [x: string]: unknown;
            kind: 'turnCheckpoint';
        } | {
            [x: string]: unknown;
            kind: 'workingTree';
        };
        backendPreference?: {
            kind: 'prefer';
            backendId: string;
        } | undefined;
        turnId?: string | undefined;
        checkpointReceiptId?: string | undefined;
        turnEvidenceMode?: 'reconciled' | 'agent_reported' | 'checkpoint' | undefined;
        modelSelector?: {
            [x: string]: unknown;
            profileId?: string | undefined;
            modelId?: string | undefined;
            backendTargetKey?: string | undefined;
        } | undefined;
        cachePolicy?: {
            [x: string]: unknown;
            mode: 'read_write' | 'bypass';
        } | undefined;
    };
};
export type ScmDiffSummaryActionResultById = {
    readonly "scm.diffSummary.generate": {
        [x: string]: unknown;
        success: true;
        summaryMarkdown: string;
        sourceKey: string;
        metadata: {
            [x: string]: unknown;
            source: {
                [x: string]: unknown;
                kind: 'turnCheckpoint';
            } | {
                [x: string]: unknown;
                kind: 'workingTree';
            };
            sourceKey: string;
            turnId?: string | undefined;
            checkpointReceiptId?: string | undefined;
            turnEvidenceMode?: 'reconciled' | 'agent_reported' | 'checkpoint' | undefined;
            contentConfidence?: 'exact' | 'unavailable' | undefined;
            attributionScope?: 'unknown' | 'no_happier_checkpoint_overlap_observed' | 'shared_worktree' | undefined;
        };
        checkpointReceiptId?: string | undefined;
        truncation?: {
            [x: string]: unknown;
            reason: 'fileBudget' | 'diffBytes' | 'fileCount';
            droppedFiles?: number | undefined;
        } | undefined;
        generationState?: 'complete' | 'partial' | undefined;
        cost?: {
            [x: string]: unknown;
            inputTokens?: number | undefined;
            outputTokens?: number | undefined;
            estimatedUsd?: number | undefined;
        } | undefined;
        risks?: string[] | undefined;
        testImpact?: string | undefined;
        suggestedPrBody?: string | undefined;
    } | {
        [x: string]: unknown;
        success: false;
        error: string;
        errorCode: 'TURN_CHANGE_SET_REQUIRED' | 'CHECKPOINT_NOT_FOUND' | 'CHECKPOINT_UNAVAILABLE' | 'DIFF_UNAVAILABLE' | 'MODEL_UNAVAILABLE' | 'SUMMARY_FAILED';
        sourceKey?: string | undefined;
        checkpointReceiptId?: string | undefined;
        metadata?: {
            [x: string]: unknown;
            source: {
                [x: string]: unknown;
                kind: 'turnCheckpoint';
            } | {
                [x: string]: unknown;
                kind: 'workingTree';
            };
            sourceKey: string;
            turnId?: string | undefined;
            checkpointReceiptId?: string | undefined;
            turnEvidenceMode?: 'reconciled' | 'agent_reported' | 'checkpoint' | undefined;
            contentConfidence?: 'exact' | 'unavailable' | undefined;
            attributionScope?: 'unknown' | 'no_happier_checkpoint_overlap_observed' | 'shared_worktree' | undefined;
        } | undefined;
        cost?: {
            [x: string]: unknown;
            inputTokens?: number | undefined;
            outputTokens?: number | undefined;
            estimatedUsd?: number | undefined;
        } | undefined;
    };
};
