// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.


// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
export type SessionFollowActionInputById = {
    readonly "session.follow.get": {
        sessionId: string;
    };
    readonly "session.follow.set": {
        sessionId: string;
        notificationLevel: 'none' | 'important' | 'all_messages';
        includeInVoice: boolean;
    };
    readonly "session.follow.remove": {
        sessionId: string;
    };
    readonly "session.follow.preferences.get": Record<string, never>;
    readonly "session.follow.preferences.set": {
        assigned: boolean;
        direct: boolean;
        team: boolean;
        group: boolean;
    };
    readonly "session.follow.sources.list": {
        destinationSessionId: string;
    };
    readonly "session.follow.sources.set": {
        destinationSessionId: string;
        sourceSessionId: string;
        mode?: 'next_turn' | 'wake_on_human_change' | undefined;
    };
    readonly "session.follow.sources.remove": {
        destinationSessionId: string;
        sourceSessionId: string;
    };
};
export type SessionFollowActionResultById = {
    readonly "session.follow.get": {
        follow: {
            sessionId: string;
            following: boolean;
            notificationLevel: 'none' | 'important' | 'all_messages';
            includeInVoice: boolean;
        } | null;
        isSessionOwner: boolean;
        capabilities: {
            manageFollow: boolean;
        };
        voiceInitialSnapshotPending: boolean;
    };
    readonly "session.follow.set": {
        changed: boolean;
        follow: {
            sessionId: string;
            following: boolean;
            notificationLevel: 'none' | 'important' | 'all_messages';
            includeInVoice: boolean;
        };
        voiceInitialSnapshotPending: boolean;
    };
    readonly "session.follow.remove": {
        changed: boolean;
    };
    readonly "session.follow.preferences.get": {
        assigned: boolean;
        direct: boolean;
        team: boolean;
        group: boolean;
    };
    readonly "session.follow.preferences.set": {
        assigned: boolean;
        direct: boolean;
        team: boolean;
        group: boolean;
    };
    readonly "session.follow.sources.list": {
        sources: {
            sourceSessionId: string;
            destinationSessionId: string;
            mode: 'next_turn' | 'wake_on_human_change';
            deliveryState: 'eligible' | 'paused_archived';
            hasPendingUpdates: boolean;
        }[];
    };
    readonly "session.follow.sources.set": {
        changed: boolean;
        source: {
            sourceSessionId: string;
            destinationSessionId: string;
            mode: 'next_turn' | 'wake_on_human_change';
            deliveryState: 'eligible' | 'paused_archived';
            hasPendingUpdates: boolean;
        };
    };
    readonly "session.follow.sources.remove": {
        changed: boolean;
    };
};
