// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.


// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
export type SessionDiscussionActionInputById = {
    readonly "session.discussion.list": {
        sessionId?: string | undefined;
        state?: 'active' | 'archived' | undefined;
        cursor?: string | undefined;
        limit?: number | undefined;
    };
    readonly "session.discussion.get": {
        discussionId: string;
        sessionId?: string | undefined;
    };
    readonly "session.discussion.read": {
        discussionId: string;
        sessionId?: string | undefined;
        beforeSeq?: number | undefined;
        afterSeq?: number | undefined;
        limit?: number | undefined;
    };
    readonly "session.discussion.create": {
        title: string;
        firstMessage: {
            content: {
                v: 1;
                parts: ({
                    t: 'text';
                    text: string;
                } | {
                    t: 'mention';
                    accountId: string;
                })[];
            };
            localId?: string | undefined;
            mentionedAccountIds?: string[] | undefined;
        };
        sessionId?: string | undefined;
        creationLocalId?: string | undefined;
    };
    readonly "session.discussion.post": {
        discussionId: string;
        content: {
            v: 1;
            parts: ({
                t: 'text';
                text: string;
            } | {
                t: 'mention';
                accountId: string;
            })[];
        };
        sessionId?: string | undefined;
        localId?: string | undefined;
        mentionedAccountIds?: string[] | undefined;
    };
    readonly "session.discussion.rename": {
        discussionId: string;
        title: string;
        sessionId?: string | undefined;
    };
    readonly "session.discussion.archive": {
        discussionId: string;
        sessionId?: string | undefined;
    };
    readonly "session.discussion.restore": {
        discussionId: string;
        sessionId?: string | undefined;
    };
    readonly "session.discussion.read_state.set": {
        discussionId: string;
        lastReadSeq: number;
        sessionId?: string | undefined;
    };
};
export type SessionDiscussionActionResultById = {
    readonly "session.discussion.list": {
        discussions: {
            id: string;
            sessionId: string;
            creationLocalId: string | null;
            title: string | null;
            latestMessage: {
                id: string;
                localId: string | null;
                seq: number;
                authorAccountId: string | null;
                accountActor: {
                    v: 1;
                    accountId: string;
                    profile: {
                        firstName: string | null;
                        lastName: string | null;
                        username: string | null;
                        avatarUrl: string | null;
                    } | null;
                } | null;
                producerV1: {
                    v: 1;
                    kind: 'agent';
                    sessionId: string;
                    runId?: string | undefined;
                    toolCallId?: string | undefined;
                } | null;
                createdAt: number;
            };
            messageSeq: number;
            lastReadSeq: number | null;
            unreadCount: number;
            unreadMentionCount: number;
            recentAuthorAccountIds: string[];
            archivedAt: number | null;
            capabilities: {
                postMessages: boolean;
                rename: boolean;
                archive: boolean;
                restore: boolean;
                askAgent: boolean;
                sendToSession: boolean;
            };
        }[];
        nextCursor: string | null;
        incomplete: boolean;
        v: 1;
        serverId: string;
        sessionId: string;
    };
    readonly "session.discussion.get": {
        discussion: {
            id: string;
            sessionId: string;
            creationLocalId: string | null;
            title: string | null;
            latestMessage: {
                id: string;
                localId: string | null;
                seq: number;
                authorAccountId: string | null;
                accountActor: {
                    v: 1;
                    accountId: string;
                    profile: {
                        firstName: string | null;
                        lastName: string | null;
                        username: string | null;
                        avatarUrl: string | null;
                    } | null;
                } | null;
                producerV1: {
                    v: 1;
                    kind: 'agent';
                    sessionId: string;
                    runId?: string | undefined;
                    toolCallId?: string | undefined;
                } | null;
                createdAt: number;
            };
            messageSeq: number;
            lastReadSeq: number | null;
            unreadCount: number;
            unreadMentionCount: number;
            recentAuthorAccountIds: string[];
            archivedAt: number | null;
            capabilities: {
                postMessages: boolean;
                rename: boolean;
                archive: boolean;
                restore: boolean;
                askAgent: boolean;
                sendToSession: boolean;
            };
        };
        v: 1;
        serverId: string;
        sessionId: string;
    };
    readonly "session.discussion.read": {
        discussionId: string;
        messages: {
            id: string;
            discussionId: string;
            localId: string | null;
            seq: number;
            authorAccountId: string | null;
            accountActor: {
                v: 1;
                accountId: string;
                profile: {
                    firstName: string | null;
                    lastName: string | null;
                    username: string | null;
                    avatarUrl: string | null;
                } | null;
            } | null;
            producerV1: {
                v: 1;
                kind: 'agent';
                sessionId: string;
                runId?: string | undefined;
                toolCallId?: string | undefined;
            } | null;
            content: {
                v: 1;
                parts: ({
                    t: 'text';
                    text: string;
                } | {
                    t: 'mention';
                    accountId: string;
                })[];
            } | null;
            mentionedAccountIds: string[];
            createdAt: number;
        }[];
        hasMoreOlder: boolean;
        messageSeq: number;
        incomplete: boolean;
        v: 1;
        serverId: string;
        sessionId: string;
    };
    readonly "session.discussion.create": {
        discussion: {
            id: string;
            sessionId: string;
            creationLocalId: string | null;
            title: string | null;
            latestMessage: {
                id: string;
                localId: string | null;
                seq: number;
                authorAccountId: string | null;
                accountActor: {
                    v: 1;
                    accountId: string;
                    profile: {
                        firstName: string | null;
                        lastName: string | null;
                        username: string | null;
                        avatarUrl: string | null;
                    } | null;
                } | null;
                producerV1: {
                    v: 1;
                    kind: 'agent';
                    sessionId: string;
                    runId?: string | undefined;
                    toolCallId?: string | undefined;
                } | null;
                createdAt: number;
            };
            messageSeq: number;
            lastReadSeq: number | null;
            unreadCount: number;
            unreadMentionCount: number;
            recentAuthorAccountIds: string[];
            archivedAt: number | null;
            capabilities: {
                postMessages: boolean;
                rename: boolean;
                archive: boolean;
                restore: boolean;
                askAgent: boolean;
                sendToSession: boolean;
            };
        };
        firstMessage: {
            id: string;
            discussionId: string;
            localId: string | null;
            seq: number;
            authorAccountId: string | null;
            accountActor: {
                v: 1;
                accountId: string;
                profile: {
                    firstName: string | null;
                    lastName: string | null;
                    username: string | null;
                    avatarUrl: string | null;
                } | null;
            } | null;
            producerV1: {
                v: 1;
                kind: 'agent';
                sessionId: string;
                runId?: string | undefined;
                toolCallId?: string | undefined;
            } | null;
            content: {
                v: 1;
                parts: ({
                    t: 'text';
                    text: string;
                } | {
                    t: 'mention';
                    accountId: string;
                })[];
            } | null;
            mentionedAccountIds: string[];
            createdAt: number;
        };
        v: 1;
        serverId: string;
        sessionId: string;
    };
    readonly "session.discussion.post": {
        message: {
            id: string;
            discussionId: string;
            localId: string | null;
            seq: number;
            authorAccountId: string | null;
            accountActor: {
                v: 1;
                accountId: string;
                profile: {
                    firstName: string | null;
                    lastName: string | null;
                    username: string | null;
                    avatarUrl: string | null;
                } | null;
            } | null;
            producerV1: {
                v: 1;
                kind: 'agent';
                sessionId: string;
                runId?: string | undefined;
                toolCallId?: string | undefined;
            } | null;
            content: {
                v: 1;
                parts: ({
                    t: 'text';
                    text: string;
                } | {
                    t: 'mention';
                    accountId: string;
                })[];
            } | null;
            mentionedAccountIds: string[];
            createdAt: number;
        };
        messageSeq: number;
        v: 1;
        serverId: string;
        sessionId: string;
    };
    readonly "session.discussion.rename": {
        discussion: {
            id: string;
            sessionId: string;
            creationLocalId: string | null;
            title: string | null;
            latestMessage: {
                id: string;
                localId: string | null;
                seq: number;
                authorAccountId: string | null;
                accountActor: {
                    v: 1;
                    accountId: string;
                    profile: {
                        firstName: string | null;
                        lastName: string | null;
                        username: string | null;
                        avatarUrl: string | null;
                    } | null;
                } | null;
                producerV1: {
                    v: 1;
                    kind: 'agent';
                    sessionId: string;
                    runId?: string | undefined;
                    toolCallId?: string | undefined;
                } | null;
                createdAt: number;
            };
            messageSeq: number;
            lastReadSeq: number | null;
            unreadCount: number;
            unreadMentionCount: number;
            recentAuthorAccountIds: string[];
            archivedAt: number | null;
            capabilities: {
                postMessages: boolean;
                rename: boolean;
                archive: boolean;
                restore: boolean;
                askAgent: boolean;
                sendToSession: boolean;
            };
        };
        v: 1;
        serverId: string;
        sessionId: string;
    };
    readonly "session.discussion.archive": {
        discussion: {
            id: string;
            sessionId: string;
            creationLocalId: string | null;
            title: string | null;
            latestMessage: {
                id: string;
                localId: string | null;
                seq: number;
                authorAccountId: string | null;
                accountActor: {
                    v: 1;
                    accountId: string;
                    profile: {
                        firstName: string | null;
                        lastName: string | null;
                        username: string | null;
                        avatarUrl: string | null;
                    } | null;
                } | null;
                producerV1: {
                    v: 1;
                    kind: 'agent';
                    sessionId: string;
                    runId?: string | undefined;
                    toolCallId?: string | undefined;
                } | null;
                createdAt: number;
            };
            messageSeq: number;
            lastReadSeq: number | null;
            unreadCount: number;
            unreadMentionCount: number;
            recentAuthorAccountIds: string[];
            archivedAt: number | null;
            capabilities: {
                postMessages: boolean;
                rename: boolean;
                archive: boolean;
                restore: boolean;
                askAgent: boolean;
                sendToSession: boolean;
            };
        };
        v: 1;
        serverId: string;
        sessionId: string;
    };
    readonly "session.discussion.restore": {
        discussion: {
            id: string;
            sessionId: string;
            creationLocalId: string | null;
            title: string | null;
            latestMessage: {
                id: string;
                localId: string | null;
                seq: number;
                authorAccountId: string | null;
                accountActor: {
                    v: 1;
                    accountId: string;
                    profile: {
                        firstName: string | null;
                        lastName: string | null;
                        username: string | null;
                        avatarUrl: string | null;
                    } | null;
                } | null;
                producerV1: {
                    v: 1;
                    kind: 'agent';
                    sessionId: string;
                    runId?: string | undefined;
                    toolCallId?: string | undefined;
                } | null;
                createdAt: number;
            };
            messageSeq: number;
            lastReadSeq: number | null;
            unreadCount: number;
            unreadMentionCount: number;
            recentAuthorAccountIds: string[];
            archivedAt: number | null;
            capabilities: {
                postMessages: boolean;
                rename: boolean;
                archive: boolean;
                restore: boolean;
                askAgent: boolean;
                sendToSession: boolean;
            };
        };
        v: 1;
        serverId: string;
        sessionId: string;
    };
    readonly "session.discussion.read_state.set": {
        cursor: {
            discussionId: string;
            lastReadSeq: number;
            didChange: boolean;
        };
        v: 1;
        serverId: string;
        sessionId: string;
    };
};
