// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.


// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
export type SettingsDeclarationsActionInputById = {
    readonly "settings.list": {
        pageId?: string | undefined;
    };
    readonly "settings.get": {
        anchor: string;
    };
    readonly "settings.set": {
        anchor: string;
        value: string | number | boolean | null;
    };
};
export type SettingsDeclarationsActionResultById = {
    readonly "settings.list": {
        items: {
            anchor: string;
            pageId: string;
            title: string;
            readable: boolean;
            writable: boolean;
            sensitive: boolean;
            description?: string | undefined;
            storageScope?: 'account' | 'local' | undefined;
            allowedValues?: (string | number | boolean | null)[] | undefined;
            unavailableReason?: 'sensitive' | 'not_bound' | 'read_only' | 'unsupported_host' | 'feature_disabled' | undefined;
        }[];
    };
    readonly "settings.get": {
        anchor: string;
        value: string | number | boolean | null;
    } | {
        anchor: string;
        unset: true;
    };
    readonly "settings.set": {
        anchor: string;
        value: string | number | boolean | null;
    };
};
