// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.

import type { JsonValue } from '../../identity.js';

export type VoiceControlsActionInputById = {
    readonly "ui.voice_global.reset": Record<string, never>;
    readonly "ui.voice_agent.teleport": {
        [x: string]: unknown;
        sessionId?: string | undefined;
    };
};
export type VoiceControlsActionResultById = {
    readonly "ui.voice_global.reset": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "ui.voice_agent.teleport": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
};
