// Generated from apps/ui/sources/theme/tokens/themeColorTokenDefinitions.ts.
// Run node packages/embed/scripts/generateThemeTokenIds.mjs --write after owner changes.
export const EMBED_COLOR_TOKEN_IDS = [
  "background.canvas",
  "border.default",
  "border.focus",
  "border.modal",
  "border.strong",
  "border.surface",
  "chrome.header.background",
  "chrome.header.foreground",
  "composer.chipTint",
  "control.button.primary.background",
  "control.button.primary.disabled",
  "control.button.primary.foreground",
  "control.button.secondary.background",
  "control.button.secondary.foreground",
  "control.fab.background",
  "control.fab.backgroundPressed",
  "control.fab.foreground",
  "control.input.background",
  "control.input.foreground",
  "control.input.placeholder",
  "control.permissionButton.allow.background",
  "control.permissionButton.allow.foreground",
  "control.permissionButton.allowAll.background",
  "control.permissionButton.allowAll.foreground",
  "control.permissionButton.deny.background",
  "control.permissionButton.deny.foreground",
  "control.permissionButton.inactive.background",
  "control.permissionButton.inactive.border",
  "control.permissionButton.inactive.foreground",
  "control.permissionButton.selected.background",
  "control.permissionButton.selected.border",
  "control.permissionButton.selected.foreground",
  "control.radio.active",
  "control.radio.dot",
  "control.radio.inactive",
  "control.segmentedControl.activeBackground",
  "control.segmentedControl.trackBackground",
  "control.switch.thumb.active",
  "control.switch.thumb.inactive",
  "control.switch.track.active",
  "control.switch.track.inactive",
  "diff.added.background",
  "diff.added.foreground",
  "diff.context.foreground",
  "diff.hunk.background",
  "diff.hunk.foreground",
  "diff.inlineAdded.background",
  "diff.inlineAdded.foreground",
  "diff.inlineRemoved.background",
  "diff.inlineRemoved.foreground",
  "diff.removed.background",
  "diff.removed.foreground",
  "effect.surfaceHighlight",
  "message.agent.foreground",
  "message.event.foreground",
  "message.user.background",
  "message.user.foreground",
  "overlay.foreground",
  "overlay.scrim",
  "overlay.scrimSoft",
  "overlay.scrimStrong",
  "overlay.scrimWizard",
  "overlay.secondaryForeground",
  "permission.acceptEdits",
  "permission.bypass",
  "permission.default",
  "permission.plan",
  "permission.readOnly",
  "permission.safeYolo",
  "permission.yolo",
  "state.active.background",
  "state.active.border",
  "state.active.foreground",
  "state.danger.background",
  "state.danger.border",
  "state.danger.foreground",
  "state.info.background",
  "state.info.border",
  "state.info.foreground",
  "state.neutral.background",
  "state.neutral.border",
  "state.neutral.foreground",
  "state.success.background",
  "state.success.border",
  "state.success.foreground",
  "state.warning.background",
  "state.warning.border",
  "state.warning.foreground",
  "surface.base",
  "surface.elevated",
  "surface.inset",
  "surface.pressed",
  "surface.pressedOverlay",
  "surface.ripple",
  "surface.sectionTint",
  "surface.selected",
  "syntax.comment",
  "syntax.default",
  "syntax.function",
  "syntax.keyword",
  "syntax.number",
  "syntax.string",
  "text.destructive",
  "text.disabled",
  "text.link",
  "text.placeholder",
  "text.primary",
  "text.secondary",
  "text.tertiary",
  "versionControl.added.background",
  "versionControl.added.foreground",
  "versionControl.removed.background",
  "versionControl.removed.foreground"
] as const;
export type EmbedColorTokenId = typeof EMBED_COLOR_TOKEN_IDS[number];
export const EMBED_PLACEHOLDER_THEME = {
  "light": {
    "canvas": "#F5F5F5",
    "skeleton": "#F8F8F8"
  },
  "dark": {
    "canvas": "#131111",
    "skeleton": "#171515"
  },
  "radiusScales": {
    "sharp": {
      "sm": 2,
      "md": 4,
      "lg": 5,
      "xl": 6,
      "xxl": 8,
      "modalCard": 8
    },
    "soft": {
      "sm": 4,
      "md": 8,
      "lg": 10,
      "xl": 12,
      "xxl": 16,
      "modalCard": 14
    },
    "round": {
      "sm": 6,
      "md": 12,
      "lg": 14,
      "xl": 18,
      "xxl": 24,
      "modalCard": 20
    }
  },
  "composerRadiusStep": "xxl",
  "horizontalPadding": {
    "breakpoint": 700,
    "wide": 16,
    "narrow": 8
  },
  "bottom": 8,
  "maxWidth": 850,
  "height": 82,
  "fadeMs": 140,
  "easingCss": "cubic-bezier(0.2, 0, 0, 1)"
} as const;
