// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
export type PluginWebhooksActionInputById = {
    readonly "plugin.webhook.endpoint.ensure": {
        webhookContribution: {
            pluginId: string;
            localId: string;
        };
        targetMaterialization: {
            machineId: string;
            materializationId: string;
            pluginId: string;
        };
        sourceInstanceId: string;
        setup: {
            kind: 'accountEndpointV1';
            credential: 'serverGenerated';
        } | {
            kind: 'githubSharedInstallationV1';
            installationId: string;
            installationAuthorizationRef: string;
        };
        idempotencyKey: string;
    };
    readonly "plugin.webhook.endpoint.read": {
        webhookEndpointId: string;
    };
    readonly "plugin.webhook.endpoint.revoke": {
        webhookEndpointId: string;
        expectedRevision: number;
        idempotencyKey: string;
    };
    readonly "plugin.webhook.endpoint.retarget": {
        webhookEndpointId: string;
        expectedRevision: number;
        targetMaterialization: {
            machineId: string;
            materializationId: string;
            pluginId: string;
        };
        idempotencyKey: string;
    };
    readonly "plugin.webhook.endpoint.checkCorrespondence": {
        webhookEndpointId: string;
        webhookContribution: {
            pluginId: string;
            localId: string;
        };
        targetMaterialization: {
            machineId: string;
            materializationId: string;
            pluginId: string;
        };
        sourceInstanceId: string;
        setup: {
            kind: 'accountEndpointV1';
            credential: 'serverGenerated';
        } | {
            kind: 'githubSharedInstallationV1';
            installationId: string;
            installationAuthorizationRef: string;
        };
    };
    readonly "plugin.webhook.endpoint.convergeTarget": {
        webhookEndpointId: string;
        webhookContribution: {
            pluginId: string;
            localId: string;
        };
        sourceInstanceId: string;
        setup: {
            kind: 'accountEndpointV1';
            credential: 'serverGenerated';
        } | {
            kind: 'githubSharedInstallationV1';
            installationId: string;
            installationAuthorizationRef: string;
        };
        desiredTargetMaterialization: {
            machineId: string;
            materializationId: string;
            pluginId: string;
        };
        targetIntentEpoch: number;
    };
    readonly "plugin.webhook.endpoint.credential.configure": {
        webhookEndpointId: string;
        expectedRevision: number;
    };
    readonly "plugin.webhook.endpoint.credential.rotate": {
        webhookEndpointId: string;
        expectedRevision: number;
    };
    readonly "plugin.webhook.endpoint.credential.finishRotation": {
        webhookEndpointId: string;
        expectedRevision: number;
        expectedPreviousCredentialVersionId: string;
    };
};

export type PluginWebhooksActionResultById = {
    readonly "plugin.webhook.endpoint.ensure": {
        webhookEndpointId: string;
        revision: number;
        publicUrl: string;
        readiness: 'ready' | 'providerConfirmationRequired' | 'credentialDisclosureLost' | 'targetUnavailable' | 'routeUnavailable';
        oneTimeGeneratedSecret?: string | undefined;
    };
    readonly "plugin.webhook.endpoint.read": {
        webhookEndpointId: string;
        revision: number;
        contribution: {
            pluginId: string;
            localId: string;
        };
        targetMaterialization: {
            machineId: string;
            materializationId: string;
            pluginId: string;
        };
        sourceInstanceId: string;
        routing: 'accountEndpoint' | 'providerInstallation';
        readiness: 'ready' | 'providerConfirmationRequired' | 'credentialDisclosureLost' | 'targetUnavailable' | 'routeUnavailable';
        publicUrl: string;
        createdAt: number;
        revokedAt?: number | undefined;
    };
    readonly "plugin.webhook.endpoint.revoke": {
        kind: 'revoked' | 'alreadyRevoked';
        webhookEndpointId: string;
        revision: number;
    };
    readonly "plugin.webhook.endpoint.retarget": {
        kind: 'retargeted' | 'alreadyRetargeted';
        webhookEndpointId: string;
        revision: number;
        previousTargetMaterialization: {
            machineId: string;
            materializationId: string;
            pluginId: string;
        };
        targetMaterialization: {
            machineId: string;
            materializationId: string;
            pluginId: string;
        };
    } | {
        kind: 'targetUnavailable' | 'revisionConflict' | 'incompatible';
        currentRevision?: number | undefined;
    };
    readonly "plugin.webhook.endpoint.checkCorrespondence": {
        kind: 'ready';
        webhookEndpointId: string;
        revision: number;
    } | {
        kind: 'unavailable';
        code: string;
    };
    readonly "plugin.webhook.endpoint.convergeTarget": {
        kind: 'converged';
        webhookEndpointId: string;
        revision: number;
        targetMaterialization: {
            machineId: string;
            materializationId: string;
            pluginId: string;
        };
        targetIntentEpoch: number;
    } | {
        kind: 'superseded';
        webhookEndpointId: string;
        currentTargetIntentEpoch: number;
    } | {
        kind: 'unavailable';
        code: string;
    };
    readonly "plugin.webhook.endpoint.credential.configure": {
        kind: 'configured' | 'alreadyConfigured';
        webhookEndpointId: string;
        revision: number;
        credentialVersionId: string;
        oneTimeGeneratedSecret?: string | undefined;
    };
    readonly "plugin.webhook.endpoint.credential.rotate": {
        kind: 'rotated' | 'alreadyRotated';
        webhookEndpointId: string;
        revision: number;
        credentialVersionId: string;
        previousCredentialVersionId: string;
        previousAcceptUntilMs: number;
        oneTimeGeneratedSecret?: string | undefined;
    };
    readonly "plugin.webhook.endpoint.credential.finishRotation": {
        kind: 'retired' | 'alreadyRetired';
        webhookEndpointId: string;
        revision: number;
    } | {
        kind: 'revisionConflict' | 'unavailable' | 'credentialChanged';
        currentRevision?: number | undefined;
    };
};
