// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
import type { JsonValue, PluginInvocableActionId } from './pluginActionDtoSupport.js';
export type ApprovalsActionInputById = {
    readonly "approval.request.list": {
        [x: string]: unknown;
        status?: 'open' | 'approved' | 'executing' | 'rejected' | 'executed' | 'failed' | 'canceled' | undefined;
        limit?: number | undefined;
    };
    readonly "approval.request.get": {
        [x: string]: unknown;
        artifactId: string;
    };
    readonly "approval.request.create": {
        [x: string]: unknown;
        actionArgs: unknown;
        summary: string;
        createdBy: {
            surface: 'voice' | 'agent' | 'session_agent' | 'mcp' | 'cli' | 'system';
            agentId?: string | undefined;
            pluginId?: string | undefined;
            contributionLocalId?: string | undefined;
            sessionId?: string | undefined;
        };
        actionId: PluginInvocableActionId;
        origin?: {
            kind: 'transcript_tool_call';
            sessionId: string;
            messageId?: string | undefined;
            parentMessageId?: string | undefined;
            toolCallId?: string | undefined;
            mcpRequestId?: string | undefined;
            toolName?: string | undefined;
            toolInput?: unknown;
        } | undefined;
        preview?: unknown;
    };
    readonly "approval.request.decide": {
        [x: string]: unknown;
        artifactId: string;
        decision: 'approve' | 'reject';
        originServerId?: string | undefined;
        serverIdentityId?: string | undefined;
    };
};

export type ApprovalsActionResultById = {
    readonly "approval.request.list": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "approval.request.get": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "approval.request.create": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "approval.request.decide": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
};
