// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
import type { JsonValue } from './pluginActionDtoSupport.js';
export type CompanionControlsActionInputById = {
    readonly "ui.pet.choose": Record<string, never>;
};

export type CompanionControlsActionResultById = {
    readonly "ui.pet.choose": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
};
