// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
import type { JsonValue } from './pluginActionDtoSupport.js';
export type InventoryActionInputById = {
    readonly "paths.list_recent": {
        [x: string]: unknown;
        machineId?: string | undefined;
        limit?: number | undefined;
    };
    readonly "projects.list": {
        [x: string]: unknown;
        machineId?: string | undefined;
        limit?: number | undefined;
    };
    readonly "prompts.invocations.list": {
        [x: string]: unknown;
        limit?: number | undefined;
    };
    readonly "prompts.invocation.resolve": {
        [x: string]: unknown;
        invocationId: string;
        argsText?: string | undefined;
    };
    readonly "machines.list": {
        [x: string]: unknown;
        limit?: number | undefined;
    };
    readonly "servers.list": {
        [x: string]: unknown;
        limit?: number | undefined;
    };
    readonly "review.engines.list": {
        [x: string]: unknown;
        sessionId?: string | undefined;
        includeDisabled?: boolean | undefined;
        scope?: 'paths' | undefined;
    };
    readonly "agents.backends.list": {
        [x: string]: unknown;
        includeDisabled?: boolean | undefined;
        limit?: number | undefined;
        machineId?: string | undefined;
    };
    readonly "machines.agents.list": {
        machineId: string;
        serverId?: string | undefined;
        agentId?: string | undefined;
        refresh?: boolean | undefined;
    };
    readonly "agents.models.list": {
        [x: string]: unknown;
        agentId?: string | undefined;
        backendTargetKey?: string | undefined;
        machineId?: string | undefined;
        serverId?: string | undefined;
        limit?: number | undefined;
    };
    readonly "agents.config_options.list": {
        [x: string]: unknown;
        agentId?: string | undefined;
        backendTargetKey?: string | undefined;
        machineId?: string | undefined;
        limit?: number | undefined;
        modelId?: string | undefined;
        serverId?: string | undefined;
    };
    readonly "agents.session_modes.list": {
        [x: string]: unknown;
        agentId?: string | undefined;
        backendTargetKey?: string | undefined;
        machineId?: string | undefined;
        limit?: number | undefined;
        serverId?: string | undefined;
    };
    readonly "sessions.spawn.profiles.list": {
        [x: string]: unknown;
        agentId?: string | undefined;
        backendTargetKey?: string | undefined;
        machineId?: string | undefined;
        limit?: number | undefined;
    };
    readonly "sessions.spawn.connected_services.list": {
        [x: string]: unknown;
        agentId?: string | undefined;
        backendTargetKey?: string | undefined;
        machineId?: string | undefined;
        limit?: number | undefined;
        includeUnavailable?: boolean | undefined;
        serverId?: string | undefined;
    };
    readonly "sessions.spawn.mcp_servers.preview": {
        [x: string]: unknown;
        agentId?: string | undefined;
        backendTargetKey?: string | undefined;
        machineId?: string | undefined;
        directory?: string | undefined;
        path?: string | undefined;
        selection?: unknown;
        limit?: number | undefined;
    };
};

export type InventoryActionResultById = {
    readonly "paths.list_recent": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "projects.list": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "prompts.invocations.list": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "prompts.invocation.resolve": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "machines.list": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "servers.list": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "review.engines.list": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "agents.backends.list": {
        items: {
            targetKey: string;
            label: string;
            enabled: boolean;
            agentId?: string | undefined;
            identity?: {
                pluginId: string;
                localId: string;
            } | undefined;
            backendId?: string | undefined;
            description?: string | undefined;
        }[];
    };
    readonly "machines.agents.list": {
        items: {
            installed: boolean;
            version: string | null;
            latestVersion: string | null;
            update: {
                supported: boolean;
                command: string | null;
            };
            signIn: {
                status: 'unknown' | 'signedIn' | 'signedOut';
                loginSupport: 'login_terminal' | 'status_only' | 'manual_only' | 'unsupported';
                accountLabel?: string | undefined;
            };
            platform: {
                supported: true;
            } | {
                supported: false;
                reason: 'os' | 'arch';
            };
            install: {
                available: boolean;
                mode: 'managed' | 'vendor_recipe' | 'manual' | 'none';
                sizeBytes: number | null;
                guideUrl: string | null;
            };
            dependencies: {
                key: string;
                installed: boolean;
                version: string | null;
            }[];
            agentId: string;
            title: string;
        }[];
    };
    readonly "agents.models.list": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "agents.config_options.list": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "agents.session_modes.list": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "sessions.spawn.profiles.list": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "sessions.spawn.connected_services.list": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "sessions.spawn.mcp_servers.preview": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
};
