// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
export type LaunchProfilesActionInputById = {
    readonly "launch_profiles.publish": {
        profileId: string;
    };
};

export type LaunchProfilesActionResultById = {
    readonly "launch_profiles.publish": {
        artifactId: string;
    };
};
