// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
export type BrowserRecordingActionInputById = {
    readonly "browser.recording.start": {
        browserSessionId: string;
        viewId: string;
        profileId: string;
        targetKind: 'localServicePreview' | 'hostedPluginWeb' | 'externalUrl' | 'streamedBrowser' | 'simulatorPreview';
        adapterKind: 'externalUrl' | 'simulatorPreview' | 'localPreview' | 'hostedPlugin' | 'chromiumSidecar' | 'streamedBrowserSurface';
        renderEngineKind: 'webIframe' | 'nativeWebView' | 'desktopWebView' | 'electronWebContentsView' | 'streamedSurface' | 'unavailable';
        captureKind: 'unavailable' | 'cdpScreencast' | 'webContentsCapture' | 'nativeViewCapture' | 'streamFrameCapture' | 'mediaRecorder';
        fidelity: 'unavailable' | 'cdp' | 'previewProxy' | 'injectedPage' | 'nativeCallback' | 'streamFrame';
        navigationGeneration: number;
        mimeType: string;
        retentionClass: 'preSend' | 'attached' | 'clearOnClose' | 'clearOnSend' | 'diagnosticsOnly';
        policyState?: 'allowed' | 'permissionDenied' | 'policyDenied' | 'sensitiveOrigin' | 'sensitiveFieldsPresent' | 'ephemeralOnly' | 'captureUnavailable' | 'retentionLimited' | undefined;
        mediaTarget?: {
            sessionId: string;
            messageLocalId: string;
        } | undefined;
        captureSource?: {
            kind: 'machineLiveStream';
            streamFamily: string;
            sourceId?: string | undefined;
            sourceMachineId?: string | undefined;
            targetMachineId?: string | undefined;
        } | undefined;
        startedAtMs?: number | undefined;
        recordingId?: string | undefined;
    };
    readonly "browser.recording.stop": {
        recordingId: string;
        navigationGenerationEnd: number;
        stoppedAtMs?: number | undefined;
        expiresAtMs?: number | undefined;
    };
    readonly "browser.recording.cancel": {
        recordingId: string;
        reason: 'user_canceled' | 'user_discarded' | 'session_closed' | 'logout';
        atMs?: number | undefined;
    };
    readonly "browser.recording.status": {
        recordingId: string;
    };
    readonly "browser.recording.listForView": {
        viewId: string;
    };
    readonly "browser.recording.discard": {
        recordingId: string;
        reason: 'user_canceled' | 'user_discarded' | 'session_closed' | 'logout';
        atMs?: number | undefined;
    };
    readonly "browser.recording.cleanupExpired": {
        nowMs?: number | undefined;
    };
    readonly "browser.recording.attachToComposer": {
        [x: string]: unknown;
        recordingId: string;
        sessionId?: string | undefined;
    };
};

export type BrowserRecordingActionResultById = {
    readonly "browser.recording.start": {
        status: 'started';
        recording: {
            v: 1;
            recordingId: string;
            browserSessionId: string;
            viewId: string;
            profileId: string;
            targetKind: 'localServicePreview' | 'hostedPluginWeb' | 'externalUrl' | 'streamedBrowser' | 'simulatorPreview';
            adapterKind: 'externalUrl' | 'simulatorPreview' | 'localPreview' | 'hostedPlugin' | 'chromiumSidecar' | 'streamedBrowserSurface';
            renderEngineKind: 'webIframe' | 'nativeWebView' | 'desktopWebView' | 'electronWebContentsView' | 'streamedSurface' | 'unavailable';
            captureKind: 'unavailable' | 'cdpScreencast' | 'webContentsCapture' | 'nativeViewCapture' | 'streamFrameCapture' | 'mediaRecorder';
            fidelity: 'unavailable' | 'cdp' | 'previewProxy' | 'injectedPage' | 'nativeCallback' | 'streamFrame';
            startedAtMs: number;
            status: 'recording' | 'starting' | 'paused' | 'stopping' | 'completed' | 'finalized' | 'failed' | 'canceled' | 'discarded' | 'expired';
            navigationGenerationStart: number;
            durationMs: number;
            byteSize: number;
            frameCount: number;
            fps: number;
            mimeType: string;
            retentionClass: 'preSend' | 'attached' | 'clearOnClose' | 'clearOnSend' | 'diagnosticsOnly';
            redactionLevel: 'none' | 'metadataOnly' | 'redacted' | 'blocked';
            policyState: 'allowed' | 'permissionDenied' | 'policyDenied' | 'sensitiveOrigin' | 'sensitiveFieldsPresent' | 'ephemeralOnly' | 'captureUnavailable' | 'retentionLimited';
            maxDurationMs: number;
            maxBytes: number;
            actionChapters: {
                v: 1;
                chapterId: string;
                startOffsetMs: number;
                endOffsetMs: number;
                actionKind: string;
                status: 'failed' | 'canceled' | 'queued' | 'running' | 'succeeded' | 'interrupted';
                requesterClass: 'human' | 'agent' | 'system';
                diagnosticsRefs: string[];
                actionId?: string | undefined;
                targetSummary?: string | undefined;
                reason?: string | undefined;
            }[];
            relatedReferences: ({
                refKind: 'browserContextScreenshot';
                contextId: string;
                mediaId?: string | undefined;
            } | {
                refKind: 'browserDiagnosticsBundle';
                diagnosticsBundleId: string;
            } | {
                refKind: 'browserActionTimeline';
                timelineId: string;
                actionIds: string[];
            } | {
                refKind: 'sessionMedia';
                mediaId: string;
                mediaKind: 'image' | 'video';
                mimeType: string;
                sizeBytes: number;
            })[];
            stoppedAtMs?: number | undefined;
            outcomeReason?: 'user_canceled' | 'user_discarded' | 'session_closed' | 'logout' | 'expired' | 'user_stopped' | 'duration_cap' | 'size_cap' | 'view_hidden' | 'view_parked' | 'view_suspended' | 'host_lost' | 'view_closed' | 'policy_revoked' | 'permission_denied' | 'adapter_lost' | 'capture_failed' | 'capture_unavailable' | 'unsupported' | 'retention_limit' | undefined;
            navigationGenerationEnd?: number | undefined;
            expiresAtMs?: number | undefined;
            mediaRef?: {
                refKind: 'sessionMedia';
                mediaId: string;
                mediaKind: 'image' | 'video';
                mimeType: string;
                sizeBytes: number;
            } | undefined;
        };
    } | {
        status: 'unavailable';
        reason: {
            code: string;
            message: string;
        };
    };
    readonly "browser.recording.stop": {
        status: 'finalized';
        recording: {
            v: 1;
            recordingId: string;
            browserSessionId: string;
            viewId: string;
            profileId: string;
            targetKind: 'localServicePreview' | 'hostedPluginWeb' | 'externalUrl' | 'streamedBrowser' | 'simulatorPreview';
            adapterKind: 'externalUrl' | 'simulatorPreview' | 'localPreview' | 'hostedPlugin' | 'chromiumSidecar' | 'streamedBrowserSurface';
            renderEngineKind: 'webIframe' | 'nativeWebView' | 'desktopWebView' | 'electronWebContentsView' | 'streamedSurface' | 'unavailable';
            captureKind: 'unavailable' | 'cdpScreencast' | 'webContentsCapture' | 'nativeViewCapture' | 'streamFrameCapture' | 'mediaRecorder';
            fidelity: 'unavailable' | 'cdp' | 'previewProxy' | 'injectedPage' | 'nativeCallback' | 'streamFrame';
            startedAtMs: number;
            status: 'recording' | 'starting' | 'paused' | 'stopping' | 'completed' | 'finalized' | 'failed' | 'canceled' | 'discarded' | 'expired';
            navigationGenerationStart: number;
            durationMs: number;
            byteSize: number;
            frameCount: number;
            fps: number;
            mimeType: string;
            retentionClass: 'preSend' | 'attached' | 'clearOnClose' | 'clearOnSend' | 'diagnosticsOnly';
            redactionLevel: 'none' | 'metadataOnly' | 'redacted' | 'blocked';
            policyState: 'allowed' | 'permissionDenied' | 'policyDenied' | 'sensitiveOrigin' | 'sensitiveFieldsPresent' | 'ephemeralOnly' | 'captureUnavailable' | 'retentionLimited';
            maxDurationMs: number;
            maxBytes: number;
            actionChapters: {
                v: 1;
                chapterId: string;
                startOffsetMs: number;
                endOffsetMs: number;
                actionKind: string;
                status: 'failed' | 'canceled' | 'queued' | 'running' | 'succeeded' | 'interrupted';
                requesterClass: 'human' | 'agent' | 'system';
                diagnosticsRefs: string[];
                actionId?: string | undefined;
                targetSummary?: string | undefined;
                reason?: string | undefined;
            }[];
            relatedReferences: ({
                refKind: 'browserContextScreenshot';
                contextId: string;
                mediaId?: string | undefined;
            } | {
                refKind: 'browserDiagnosticsBundle';
                diagnosticsBundleId: string;
            } | {
                refKind: 'browserActionTimeline';
                timelineId: string;
                actionIds: string[];
            } | {
                refKind: 'sessionMedia';
                mediaId: string;
                mediaKind: 'image' | 'video';
                mimeType: string;
                sizeBytes: number;
            })[];
            stoppedAtMs?: number | undefined;
            outcomeReason?: 'user_canceled' | 'user_discarded' | 'session_closed' | 'logout' | 'expired' | 'user_stopped' | 'duration_cap' | 'size_cap' | 'view_hidden' | 'view_parked' | 'view_suspended' | 'host_lost' | 'view_closed' | 'policy_revoked' | 'permission_denied' | 'adapter_lost' | 'capture_failed' | 'capture_unavailable' | 'unsupported' | 'retention_limit' | undefined;
            navigationGenerationEnd?: number | undefined;
            expiresAtMs?: number | undefined;
            mediaRef?: {
                refKind: 'sessionMedia';
                mediaId: string;
                mediaKind: 'image' | 'video';
                mimeType: string;
                sizeBytes: number;
            } | undefined;
        };
    } | {
        status: 'failed';
        recording: {
            v: 1;
            recordingId: string;
            browserSessionId: string;
            viewId: string;
            profileId: string;
            targetKind: 'localServicePreview' | 'hostedPluginWeb' | 'externalUrl' | 'streamedBrowser' | 'simulatorPreview';
            adapterKind: 'externalUrl' | 'simulatorPreview' | 'localPreview' | 'hostedPlugin' | 'chromiumSidecar' | 'streamedBrowserSurface';
            renderEngineKind: 'webIframe' | 'nativeWebView' | 'desktopWebView' | 'electronWebContentsView' | 'streamedSurface' | 'unavailable';
            captureKind: 'unavailable' | 'cdpScreencast' | 'webContentsCapture' | 'nativeViewCapture' | 'streamFrameCapture' | 'mediaRecorder';
            fidelity: 'unavailable' | 'cdp' | 'previewProxy' | 'injectedPage' | 'nativeCallback' | 'streamFrame';
            startedAtMs: number;
            status: 'recording' | 'starting' | 'paused' | 'stopping' | 'completed' | 'finalized' | 'failed' | 'canceled' | 'discarded' | 'expired';
            navigationGenerationStart: number;
            durationMs: number;
            byteSize: number;
            frameCount: number;
            fps: number;
            mimeType: string;
            retentionClass: 'preSend' | 'attached' | 'clearOnClose' | 'clearOnSend' | 'diagnosticsOnly';
            redactionLevel: 'none' | 'metadataOnly' | 'redacted' | 'blocked';
            policyState: 'allowed' | 'permissionDenied' | 'policyDenied' | 'sensitiveOrigin' | 'sensitiveFieldsPresent' | 'ephemeralOnly' | 'captureUnavailable' | 'retentionLimited';
            maxDurationMs: number;
            maxBytes: number;
            actionChapters: {
                v: 1;
                chapterId: string;
                startOffsetMs: number;
                endOffsetMs: number;
                actionKind: string;
                status: 'failed' | 'canceled' | 'queued' | 'running' | 'succeeded' | 'interrupted';
                requesterClass: 'human' | 'agent' | 'system';
                diagnosticsRefs: string[];
                actionId?: string | undefined;
                targetSummary?: string | undefined;
                reason?: string | undefined;
            }[];
            relatedReferences: ({
                refKind: 'browserContextScreenshot';
                contextId: string;
                mediaId?: string | undefined;
            } | {
                refKind: 'browserDiagnosticsBundle';
                diagnosticsBundleId: string;
            } | {
                refKind: 'browserActionTimeline';
                timelineId: string;
                actionIds: string[];
            } | {
                refKind: 'sessionMedia';
                mediaId: string;
                mediaKind: 'image' | 'video';
                mimeType: string;
                sizeBytes: number;
            })[];
            stoppedAtMs?: number | undefined;
            outcomeReason?: 'user_canceled' | 'user_discarded' | 'session_closed' | 'logout' | 'expired' | 'user_stopped' | 'duration_cap' | 'size_cap' | 'view_hidden' | 'view_parked' | 'view_suspended' | 'host_lost' | 'view_closed' | 'policy_revoked' | 'permission_denied' | 'adapter_lost' | 'capture_failed' | 'capture_unavailable' | 'unsupported' | 'retention_limit' | undefined;
            navigationGenerationEnd?: number | undefined;
            expiresAtMs?: number | undefined;
            mediaRef?: {
                refKind: 'sessionMedia';
                mediaId: string;
                mediaKind: 'image' | 'video';
                mimeType: string;
                sizeBytes: number;
            } | undefined;
        };
        reason: 'user_canceled' | 'user_discarded' | 'session_closed' | 'logout' | 'expired' | 'user_stopped' | 'duration_cap' | 'size_cap' | 'view_hidden' | 'view_parked' | 'view_suspended' | 'host_lost' | 'view_closed' | 'policy_revoked' | 'permission_denied' | 'adapter_lost' | 'capture_failed' | 'capture_unavailable' | 'unsupported' | 'retention_limit';
    } | {
        status: 'unavailable';
        reason: {
            code: string;
            message: string;
        };
    };
    readonly "browser.recording.cancel": {
        status: 'paused' | 'failed' | 'canceled' | 'discarded';
        recording: {
            v: 1;
            recordingId: string;
            browserSessionId: string;
            viewId: string;
            profileId: string;
            targetKind: 'localServicePreview' | 'hostedPluginWeb' | 'externalUrl' | 'streamedBrowser' | 'simulatorPreview';
            adapterKind: 'externalUrl' | 'simulatorPreview' | 'localPreview' | 'hostedPlugin' | 'chromiumSidecar' | 'streamedBrowserSurface';
            renderEngineKind: 'webIframe' | 'nativeWebView' | 'desktopWebView' | 'electronWebContentsView' | 'streamedSurface' | 'unavailable';
            captureKind: 'unavailable' | 'cdpScreencast' | 'webContentsCapture' | 'nativeViewCapture' | 'streamFrameCapture' | 'mediaRecorder';
            fidelity: 'unavailable' | 'cdp' | 'previewProxy' | 'injectedPage' | 'nativeCallback' | 'streamFrame';
            startedAtMs: number;
            status: 'recording' | 'starting' | 'paused' | 'stopping' | 'completed' | 'finalized' | 'failed' | 'canceled' | 'discarded' | 'expired';
            navigationGenerationStart: number;
            durationMs: number;
            byteSize: number;
            frameCount: number;
            fps: number;
            mimeType: string;
            retentionClass: 'preSend' | 'attached' | 'clearOnClose' | 'clearOnSend' | 'diagnosticsOnly';
            redactionLevel: 'none' | 'metadataOnly' | 'redacted' | 'blocked';
            policyState: 'allowed' | 'permissionDenied' | 'policyDenied' | 'sensitiveOrigin' | 'sensitiveFieldsPresent' | 'ephemeralOnly' | 'captureUnavailable' | 'retentionLimited';
            maxDurationMs: number;
            maxBytes: number;
            actionChapters: {
                v: 1;
                chapterId: string;
                startOffsetMs: number;
                endOffsetMs: number;
                actionKind: string;
                status: 'failed' | 'canceled' | 'queued' | 'running' | 'succeeded' | 'interrupted';
                requesterClass: 'human' | 'agent' | 'system';
                diagnosticsRefs: string[];
                actionId?: string | undefined;
                targetSummary?: string | undefined;
                reason?: string | undefined;
            }[];
            relatedReferences: ({
                refKind: 'browserContextScreenshot';
                contextId: string;
                mediaId?: string | undefined;
            } | {
                refKind: 'browserDiagnosticsBundle';
                diagnosticsBundleId: string;
            } | {
                refKind: 'browserActionTimeline';
                timelineId: string;
                actionIds: string[];
            } | {
                refKind: 'sessionMedia';
                mediaId: string;
                mediaKind: 'image' | 'video';
                mimeType: string;
                sizeBytes: number;
            })[];
            stoppedAtMs?: number | undefined;
            outcomeReason?: 'user_canceled' | 'user_discarded' | 'session_closed' | 'logout' | 'expired' | 'user_stopped' | 'duration_cap' | 'size_cap' | 'view_hidden' | 'view_parked' | 'view_suspended' | 'host_lost' | 'view_closed' | 'policy_revoked' | 'permission_denied' | 'adapter_lost' | 'capture_failed' | 'capture_unavailable' | 'unsupported' | 'retention_limit' | undefined;
            navigationGenerationEnd?: number | undefined;
            expiresAtMs?: number | undefined;
            mediaRef?: {
                refKind: 'sessionMedia';
                mediaId: string;
                mediaKind: 'image' | 'video';
                mimeType: string;
                sizeBytes: number;
            } | undefined;
        };
    } | {
        status: 'unavailable';
        reason: {
            code: string;
            message: string;
        };
    };
    readonly "browser.recording.status": {
        v: 1;
        recordingId: string;
        browserSessionId: string;
        viewId: string;
        profileId: string;
        targetKind: 'localServicePreview' | 'hostedPluginWeb' | 'externalUrl' | 'streamedBrowser' | 'simulatorPreview';
        adapterKind: 'externalUrl' | 'simulatorPreview' | 'localPreview' | 'hostedPlugin' | 'chromiumSidecar' | 'streamedBrowserSurface';
        renderEngineKind: 'webIframe' | 'nativeWebView' | 'desktopWebView' | 'electronWebContentsView' | 'streamedSurface' | 'unavailable';
        captureKind: 'unavailable' | 'cdpScreencast' | 'webContentsCapture' | 'nativeViewCapture' | 'streamFrameCapture' | 'mediaRecorder';
        fidelity: 'unavailable' | 'cdp' | 'previewProxy' | 'injectedPage' | 'nativeCallback' | 'streamFrame';
        startedAtMs: number;
        status: 'recording' | 'starting' | 'paused' | 'stopping' | 'completed' | 'finalized' | 'failed' | 'canceled' | 'discarded' | 'expired';
        navigationGenerationStart: number;
        durationMs: number;
        byteSize: number;
        frameCount: number;
        fps: number;
        mimeType: string;
        retentionClass: 'preSend' | 'attached' | 'clearOnClose' | 'clearOnSend' | 'diagnosticsOnly';
        redactionLevel: 'none' | 'metadataOnly' | 'redacted' | 'blocked';
        policyState: 'allowed' | 'permissionDenied' | 'policyDenied' | 'sensitiveOrigin' | 'sensitiveFieldsPresent' | 'ephemeralOnly' | 'captureUnavailable' | 'retentionLimited';
        maxDurationMs: number;
        maxBytes: number;
        actionChapters: {
            v: 1;
            chapterId: string;
            startOffsetMs: number;
            endOffsetMs: number;
            actionKind: string;
            status: 'failed' | 'canceled' | 'queued' | 'running' | 'succeeded' | 'interrupted';
            requesterClass: 'human' | 'agent' | 'system';
            diagnosticsRefs: string[];
            actionId?: string | undefined;
            targetSummary?: string | undefined;
            reason?: string | undefined;
        }[];
        relatedReferences: ({
            refKind: 'browserContextScreenshot';
            contextId: string;
            mediaId?: string | undefined;
        } | {
            refKind: 'browserDiagnosticsBundle';
            diagnosticsBundleId: string;
        } | {
            refKind: 'browserActionTimeline';
            timelineId: string;
            actionIds: string[];
        } | {
            refKind: 'sessionMedia';
            mediaId: string;
            mediaKind: 'image' | 'video';
            mimeType: string;
            sizeBytes: number;
        })[];
        stoppedAtMs?: number | undefined;
        outcomeReason?: 'user_canceled' | 'user_discarded' | 'session_closed' | 'logout' | 'expired' | 'user_stopped' | 'duration_cap' | 'size_cap' | 'view_hidden' | 'view_parked' | 'view_suspended' | 'host_lost' | 'view_closed' | 'policy_revoked' | 'permission_denied' | 'adapter_lost' | 'capture_failed' | 'capture_unavailable' | 'unsupported' | 'retention_limit' | undefined;
        navigationGenerationEnd?: number | undefined;
        expiresAtMs?: number | undefined;
        mediaRef?: {
            refKind: 'sessionMedia';
            mediaId: string;
            mediaKind: 'image' | 'video';
            mimeType: string;
            sizeBytes: number;
        } | undefined;
    } | null;
    readonly "browser.recording.listForView": {
        v: 1;
        recordingId: string;
        browserSessionId: string;
        viewId: string;
        profileId: string;
        targetKind: 'localServicePreview' | 'hostedPluginWeb' | 'externalUrl' | 'streamedBrowser' | 'simulatorPreview';
        adapterKind: 'externalUrl' | 'simulatorPreview' | 'localPreview' | 'hostedPlugin' | 'chromiumSidecar' | 'streamedBrowserSurface';
        renderEngineKind: 'webIframe' | 'nativeWebView' | 'desktopWebView' | 'electronWebContentsView' | 'streamedSurface' | 'unavailable';
        captureKind: 'unavailable' | 'cdpScreencast' | 'webContentsCapture' | 'nativeViewCapture' | 'streamFrameCapture' | 'mediaRecorder';
        fidelity: 'unavailable' | 'cdp' | 'previewProxy' | 'injectedPage' | 'nativeCallback' | 'streamFrame';
        startedAtMs: number;
        status: 'recording' | 'starting' | 'paused' | 'stopping' | 'completed' | 'finalized' | 'failed' | 'canceled' | 'discarded' | 'expired';
        navigationGenerationStart: number;
        durationMs: number;
        byteSize: number;
        frameCount: number;
        fps: number;
        mimeType: string;
        retentionClass: 'preSend' | 'attached' | 'clearOnClose' | 'clearOnSend' | 'diagnosticsOnly';
        redactionLevel: 'none' | 'metadataOnly' | 'redacted' | 'blocked';
        policyState: 'allowed' | 'permissionDenied' | 'policyDenied' | 'sensitiveOrigin' | 'sensitiveFieldsPresent' | 'ephemeralOnly' | 'captureUnavailable' | 'retentionLimited';
        maxDurationMs: number;
        maxBytes: number;
        actionChapters: {
            v: 1;
            chapterId: string;
            startOffsetMs: number;
            endOffsetMs: number;
            actionKind: string;
            status: 'failed' | 'canceled' | 'queued' | 'running' | 'succeeded' | 'interrupted';
            requesterClass: 'human' | 'agent' | 'system';
            diagnosticsRefs: string[];
            actionId?: string | undefined;
            targetSummary?: string | undefined;
            reason?: string | undefined;
        }[];
        relatedReferences: ({
            refKind: 'browserContextScreenshot';
            contextId: string;
            mediaId?: string | undefined;
        } | {
            refKind: 'browserDiagnosticsBundle';
            diagnosticsBundleId: string;
        } | {
            refKind: 'browserActionTimeline';
            timelineId: string;
            actionIds: string[];
        } | {
            refKind: 'sessionMedia';
            mediaId: string;
            mediaKind: 'image' | 'video';
            mimeType: string;
            sizeBytes: number;
        })[];
        stoppedAtMs?: number | undefined;
        outcomeReason?: 'user_canceled' | 'user_discarded' | 'session_closed' | 'logout' | 'expired' | 'user_stopped' | 'duration_cap' | 'size_cap' | 'view_hidden' | 'view_parked' | 'view_suspended' | 'host_lost' | 'view_closed' | 'policy_revoked' | 'permission_denied' | 'adapter_lost' | 'capture_failed' | 'capture_unavailable' | 'unsupported' | 'retention_limit' | undefined;
        navigationGenerationEnd?: number | undefined;
        expiresAtMs?: number | undefined;
        mediaRef?: {
            refKind: 'sessionMedia';
            mediaId: string;
            mediaKind: 'image' | 'video';
            mimeType: string;
            sizeBytes: number;
        } | undefined;
    }[];
    readonly "browser.recording.discard": {
        status: 'paused' | 'failed' | 'canceled' | 'discarded';
        recording: {
            v: 1;
            recordingId: string;
            browserSessionId: string;
            viewId: string;
            profileId: string;
            targetKind: 'localServicePreview' | 'hostedPluginWeb' | 'externalUrl' | 'streamedBrowser' | 'simulatorPreview';
            adapterKind: 'externalUrl' | 'simulatorPreview' | 'localPreview' | 'hostedPlugin' | 'chromiumSidecar' | 'streamedBrowserSurface';
            renderEngineKind: 'webIframe' | 'nativeWebView' | 'desktopWebView' | 'electronWebContentsView' | 'streamedSurface' | 'unavailable';
            captureKind: 'unavailable' | 'cdpScreencast' | 'webContentsCapture' | 'nativeViewCapture' | 'streamFrameCapture' | 'mediaRecorder';
            fidelity: 'unavailable' | 'cdp' | 'previewProxy' | 'injectedPage' | 'nativeCallback' | 'streamFrame';
            startedAtMs: number;
            status: 'recording' | 'starting' | 'paused' | 'stopping' | 'completed' | 'finalized' | 'failed' | 'canceled' | 'discarded' | 'expired';
            navigationGenerationStart: number;
            durationMs: number;
            byteSize: number;
            frameCount: number;
            fps: number;
            mimeType: string;
            retentionClass: 'preSend' | 'attached' | 'clearOnClose' | 'clearOnSend' | 'diagnosticsOnly';
            redactionLevel: 'none' | 'metadataOnly' | 'redacted' | 'blocked';
            policyState: 'allowed' | 'permissionDenied' | 'policyDenied' | 'sensitiveOrigin' | 'sensitiveFieldsPresent' | 'ephemeralOnly' | 'captureUnavailable' | 'retentionLimited';
            maxDurationMs: number;
            maxBytes: number;
            actionChapters: {
                v: 1;
                chapterId: string;
                startOffsetMs: number;
                endOffsetMs: number;
                actionKind: string;
                status: 'failed' | 'canceled' | 'queued' | 'running' | 'succeeded' | 'interrupted';
                requesterClass: 'human' | 'agent' | 'system';
                diagnosticsRefs: string[];
                actionId?: string | undefined;
                targetSummary?: string | undefined;
                reason?: string | undefined;
            }[];
            relatedReferences: ({
                refKind: 'browserContextScreenshot';
                contextId: string;
                mediaId?: string | undefined;
            } | {
                refKind: 'browserDiagnosticsBundle';
                diagnosticsBundleId: string;
            } | {
                refKind: 'browserActionTimeline';
                timelineId: string;
                actionIds: string[];
            } | {
                refKind: 'sessionMedia';
                mediaId: string;
                mediaKind: 'image' | 'video';
                mimeType: string;
                sizeBytes: number;
            })[];
            stoppedAtMs?: number | undefined;
            outcomeReason?: 'user_canceled' | 'user_discarded' | 'session_closed' | 'logout' | 'expired' | 'user_stopped' | 'duration_cap' | 'size_cap' | 'view_hidden' | 'view_parked' | 'view_suspended' | 'host_lost' | 'view_closed' | 'policy_revoked' | 'permission_denied' | 'adapter_lost' | 'capture_failed' | 'capture_unavailable' | 'unsupported' | 'retention_limit' | undefined;
            navigationGenerationEnd?: number | undefined;
            expiresAtMs?: number | undefined;
            mediaRef?: {
                refKind: 'sessionMedia';
                mediaId: string;
                mediaKind: 'image' | 'video';
                mimeType: string;
                sizeBytes: number;
            } | undefined;
        };
    } | {
        status: 'unavailable';
        reason: {
            code: string;
            message: string;
        };
    };
    readonly "browser.recording.cleanupExpired": {
        discardedRecordingIds: string[];
        failedRecordingIds: string[];
    };
    readonly "browser.recording.attachToComposer": {
        ok: true;
        attachmentId: string;
    };
};
