import { describe, expect, it, vi } from 'vitest';
import type { SessionDraftDocumentV1, StrictJsonValue } from '@happier-dev/protocol';
import {
    NewSessionDraftDocumentV2Schema,
    SessionDraftStoredContentEnvelopeV1Schema,
    restoreSupportedPredecessorNewSessionDraftPayloadV2,
} from '@happier-dev/protocol';

import { createSessionDraftCipher } from './sessionDraftEncryption';
import { SessionDraftContextUnavailableError } from '@/sync/ops/sessionDrafts/sessionDraftCipherError';

const sessionAddress = { kind: 'session', sessionId: 'session-a' } as const;
const newAddress = { kind: 'newSession', draftId: '00000000-0000-4000-8000-000000000001' } as const;

/** Generated by remote-dev@9b097966's Account-scoped draft writer. */
const remoteDev9B097966NewSessionDraftCiphertext = 'oQoBAgMEBQYHCAkKCwwNDg8QERITFBUWFxiizx8bywx1rLYH8iwQG6VCxyjnUGGtd6tpgR2+XV/3e133gMFtHld18xSsQfkNz/SEk+yrZpTe4KuXQNnMtxoyIxKEZhbgrXiuClPXPVr7hMTCr2QzgGPBW6H8JyNOEqLbAKMzDYTdRozvRKEgbYmjdtX9v6opYrGH0Ob/FvQrNZRbBb6jFNvzplfCRfAd2pTjD3ARZLxK2OgW8ByByAdBy/OGhWrY5VuGPHwwlN6vrkjrx7vL3WOOpR7/mZODvbx03s70P8M8QwR3TimfKh4WwcUmHTqql8M5BhuM6cW2KDYifheC+1gYp2aFDImHzBNcSq1M9ocHSoIPWvDDK39fdbvRXTxS2ZE5TiRniw6MOjEV+89ve1foy6RPclMc+imaBu5xcIGPOveJ8fWKNmmrW51Y/VE0rzw7zDWOC1DzlLFia0sXLPphVu8Bhvv0tub0LSvq1+ZjKazDxdYLZYKKQQP4cQMH5VIuS48zsqYE5RJPZqpazdZ3Hs9+0tHM6rW5OOntaVfdLvWNHj7FIekpvmNM//6Uk+xDFTxq+5i/E8kTvpMw7y1EAWl2P0rM';

function document(kind: 'session' | 'newSession'): SessionDraftDocumentV1 {
    const field = <T extends StrictJsonValue>(mutationId: string, value: T) => ({ mutationId, value });
    return {
        v: 1 as const,
        composer: {
            text: field('00000000-0000-4000-8000-000000000010', 'hello'),
            mentions: field('00000000-0000-4000-8000-000000000011', []),
            attachments: field('00000000-0000-4000-8000-000000000012', []),
        },
        target: kind === 'session'
            ? { kind: 'session' as const, routing: {
                recipient: field('00000000-0000-4000-8000-000000000013', null),
                agentContinuation: field('00000000-0000-4000-8000-000000000014', null),
                executionRunDelivery: field('00000000-0000-4000-8000-000000000015', null),
            } }
            : { kind: 'newSession' as const, authoring: {} },
        extensions: {},
    };
}

describe('sessionDraftEncryption', () => {
    it.each(['plain', 'e2ee'] as const)('seals and restores the lossless supported-predecessor newSession projection (%s)', async (accountMode) => {
        const cipher = createSessionDraftCipher({
            accountMode,
            accountCryptoMaterial: accountMode === 'plain' ? null : { type: 'dataKey', machineKey: new Uint8Array(32).fill(42) },
            getSessionContext: () => null,
            randomBytes: (length) => new Uint8Array(length),
        });
        const successor = NewSessionDraftDocumentV2Schema.parse({
            ...document('newSession'),
            v: 2,
            target: {
                kind: 'newSession',
                authoring: {
                    executionTarget: { mutationId: '00000000-0000-4000-8000-000000000020', value: {
                        kind: 'machine',
                        target: { serverId: 'home-a', machineId: 'machine-a' },
                        selectionOrigin: { kind: 'machine_pool', poolId: '11111111-1111-4111-8111-111111111111' },
                    } },
                    runtimeDescriptorV1: { mutationId: '00000000-0000-4000-8000-000000000021', value: null },
                },
            },
            extensions: {
                example: { retained: { mutationId: '00000000-0000-4000-8000-000000000022', value: { future: true } } },
            },
        });

        const predecessor = await cipher.sealForSupportedPredecessorV1?.(newAddress, successor);
        expect(predecessor).not.toBeNull();
        expect(predecessor).not.toHaveProperty('v', 2);
        const readableContent = predecessor!.t === 'plain'
            ? { t: 'plain' as const, v: restoreSupportedPredecessorNewSessionDraftPayloadV2(predecessor!.v)! }
            : predecessor!;
        await expect(cipher.open(newAddress, readableContent)).resolves.toEqual(successor);
    });

    it('does not produce predecessor bytes for non-representable newSession content', async () => {
        const cipher = createSessionDraftCipher({
            accountMode: 'plain', accountCryptoMaterial: null, getSessionContext: () => null,
            randomBytes: (length) => new Uint8Array(length),
        });
        const successor = NewSessionDraftDocumentV2Schema.parse({
            ...document('newSession'),
            v: 2,
            target: {
                kind: 'newSession',
                authoring: {
                    temporaryComputerActivationRef: { mutationId: '00000000-0000-4000-8000-000000000021', value: null },
                },
            },
        });
        await expect(cipher.sealForSupportedPredecessorV1?.(newAddress, successor)).resolves.toBeNull();
    });

    it.each(['plain', 'e2ee'] as const)('round-trips Temporary computer and its public reference through the Account cipher (%s)', async (accountMode) => {
        const cipher = createSessionDraftCipher({
            accountMode,
            accountCryptoMaterial: accountMode === 'plain' ? null : { type: 'dataKey', machineKey: new Uint8Array(32).fill(42) },
            getSessionContext: () => { throw new Error('A Temporary computer draft has no Session cipher'); },
            randomBytes: (length) => new Uint8Array(length),
        });
        const successor = NewSessionDraftDocumentV2Schema.parse({
            ...document('newSession'),
            v: 2,
            target: {
                kind: 'newSession',
                authoring: {
                    executionTarget: { mutationId: '00000000-0000-4000-8000-000000000020', value: {
                        kind: 'temporary_computer', serverId: 'home-a', artifactTarget: 'linux-x64', workspace: { kind: 'endpoint_home' },
                    } },
                    temporaryComputerActivationRef: { mutationId: '00000000-0000-4000-8000-000000000021', value: {
                        v: 1, activationId: '00000000-0000-4000-8000-000000000022', createdOnDeviceLabel: 'My laptop',
                    } },
                },
            },
        });
        const sealed = await cipher.seal(newAddress, successor);
        expect(SessionDraftStoredContentEnvelopeV1Schema.safeParse(sealed).success).toBe(false);
        await expect(cipher.open(newAddress, sealed)).resolves.toEqual(successor);
        await expect(cipher.open({ ...newAddress, draftId: '00000000-0000-4000-8000-000000000002' }, sealed)).resolves.toBeNull();
        if (sealed.t === 'encrypted') {
            expect(sealed.v).toBe(2);
            await expect(cipher.open(newAddress, { t: 'encrypted', c: sealed.c })).resolves.toBeNull();
        }
    });

    it('rejects the never-released hybrid execution-target field instead of widening V1', async () => {
        const cipher = createSessionDraftCipher({
            accountMode: 'plain', accountCryptoMaterial: null,
            getSessionContext: () => null, randomBytes: (length) => new Uint8Array(length),
        });
        const legacy = document('newSession');
        if (legacy.target.kind !== 'newSession') throw new Error('Expected newSession fixture');
        legacy.target.authoring.executionTarget = {
            mutationId: '00000000-0000-4000-8000-000000000020', value: { serverId: 'home-a', machineId: 'machine-a' },
        };
        const envelope = { t: 'plain' as const, v: { v: 1 as const, address: newAddress, document: legacy } };
        await expect(cipher.open(newAddress, envelope)).resolves.toBeNull();
    });

    it('uses plain envelopes for plain targets and validates the single private address binding', async () => {
        const cipher = createSessionDraftCipher({
            accountMode: 'plain',
            accountCryptoMaterial: { type: 'dataKey', machineKey: new Uint8Array(32) },
            getSessionContext: () => ({ mode: 'plain' }),
            randomBytes: (length) => new Uint8Array(length),
        });
        const envelope = await cipher.seal(sessionAddress, document('session'));

        await expect(cipher.open(sessionAddress, envelope)).resolves.toEqual(document('session'));
        await expect(cipher.open(newAddress, envelope)).resolves.toBeNull();
    });

    it('does not require Account key material for token-only plain new-session drafts', async () => {
        const cipher = createSessionDraftCipher({
            accountMode: 'plain',
            accountCryptoMaterial: null,
            getSessionContext: () => null,
            randomBytes: (length) => new Uint8Array(length),
        });

        const envelope = await cipher.seal(newAddress, document('newSession'));
        expect(envelope).toMatchObject({ t: 'plain' });
        await expect(cipher.open(newAddress, envelope)).resolves.toEqual(document('newSession'));
    });

    it('opens an encrypted new-session draft written by remote-dev@9b097966', async () => {
        const cipher = createSessionDraftCipher({
            accountMode: 'e2ee',
            accountCryptoMaterial: { type: 'dataKey', machineKey: new Uint8Array(32).fill(42) },
            getSessionContext: () => null,
            randomBytes: (length) => new Uint8Array(length),
        });

        await expect(cipher.open(newAddress, {
            t: 'encrypted',
            c: remoteDev9B097966NewSessionDraftCiphertext,
        })).resolves.toEqual(document('newSession'));
    });

    it('uses the Session cipher for encrypted existing-session drafts and the Account kind for new drafts', async () => {
        const sessionEncryption = {
            encryptRaw: vi.fn(async () => 'session-ciphertext'),
            decryptRaw: vi.fn(async () => ({ v: 1, address: sessionAddress, document: document('session') })),
        };
        const cipher = createSessionDraftCipher({
            accountMode: 'e2ee',
            accountCryptoMaterial: { type: 'dataKey', machineKey: new Uint8Array(32) },
            getSessionContext: () => ({ mode: 'e2ee', encryption: sessionEncryption }),
            randomBytes: (length) => new Uint8Array(length),
        });

        await expect(cipher.seal(sessionAddress, document('session'))).resolves.toEqual({ t: 'encrypted', c: 'session-ciphertext' });
        const accountEnvelope = await cipher.seal(newAddress, document('newSession'));
        expect(accountEnvelope).toMatchObject({ t: 'encrypted' });
        await expect(cipher.open(newAddress, accountEnvelope)).resolves.toEqual(document('newSession'));
        expect(sessionEncryption.encryptRaw).toHaveBeenCalledOnce();
    });

    it('distinguishes unavailable Session context from invalid encrypted content', async () => {
        const unavailable = createSessionDraftCipher({
            accountMode: 'e2ee',
            accountCryptoMaterial: { type: 'dataKey', machineKey: new Uint8Array(32) },
            getSessionContext: () => null,
            randomBytes: (length) => new Uint8Array(length),
        });

        await expect(unavailable.open(sessionAddress, { t: 'encrypted', c: 'opaque' }))
            .rejects.toBeInstanceOf(SessionDraftContextUnavailableError);

        const plainSession = createSessionDraftCipher({
            accountMode: 'plain',
            accountCryptoMaterial: { type: 'dataKey', machineKey: new Uint8Array(32) },
            getSessionContext: () => ({ mode: 'plain' }),
            randomBytes: (length) => new Uint8Array(length),
        });
        await expect(plainSession.open(sessionAddress, { t: 'encrypted', c: 'opaque' })).resolves.toBeNull();
    });
});
