// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
export type SessionReadStateActionInputById = {
    readonly "session.read_state.set": {
        sessionId: string;
        state: 'read' | 'unread';
    };
};

export type SessionReadStateActionResultById = {
    readonly "session.read_state.set": {
        state: 'read' | 'unread' | 'empty';
        lastViewedSessionSeq: number | null;
        didChange: boolean;
        viewer?: {
            readState: {
                state: 'not_started';
            } | {
                state: 'tracking';
                lastViewedSessionSeq: number;
                unreadSince: number | null;
            };
            relevance: {
                relevant: boolean;
                reasons: readonly ('owned_by_me' | 'responsible_for_me' | 'shared_directly_with_me' | 'authored_by_me' | 'mentioned_in_discussion' | 'followed_by_me' | 'pinned_by_me' | 'explicit_attention')[];
            };
            attention: {
                needsAttention: boolean;
                reasons: readonly ('unread' | 'failed' | 'permission_required' | 'user_action_required' | 'pending_blocked' | 'mentioned' | 'unread_discussion' | 'ready_after_read' | 'reminder_due' | 'manual')[];
                primary: 'unread' | 'failed' | 'permission_required' | 'user_action_required' | 'pending_blocked' | 'mentioned' | 'unread_discussion' | 'ready_after_read' | 'reminder_due' | 'manual' | null;
                presentation: 'full' | 'status_only';
            };
            follow: {
                follows: boolean;
                notificationLevel: 'none' | 'important' | 'all_messages' | null;
                includeInVoice?: boolean | undefined;
            };
            notification: {
                level: 'none' | 'important' | 'all_messages';
                source: 'none' | 'preference' | 'owner';
            };
        } | undefined;
    };
};
