// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
export type MemoryActionInputById = {
    readonly "memory.search": {
        [x: string]: unknown;
        machineId: string;
        query: {
            [x: string]: unknown;
            v: 1;
            query: string;
            scope: {
                [x: string]: unknown;
                type: 'global';
            } | {
                [x: string]: unknown;
                type: 'session';
                sessionId: string;
            };
            mode: 'hints' | 'deep' | 'auto';
            eligibleSessionIds?: string[] | undefined;
            maxResults?: number | undefined;
            minScore?: number | undefined;
        };
    };
    readonly "memory.get_window": {
        [x: string]: unknown;
        machineId: string;
        sessionId: string;
        seqFrom: number;
        seqTo: number;
    };
    readonly "memory.ensure_up_to_date": {
        [x: string]: unknown;
        machineId: string;
        sessionId?: string | undefined;
    };
};

export type MemoryActionResultById = {
    readonly "memory.search": {
        [x: string]: unknown;
        v: 1;
        ok: true;
        hits: {
            [x: string]: unknown;
            sessionId: string;
            seqFrom: number;
            seqTo: number;
            createdAtFromMs: number;
            createdAtToMs: number;
            summary: string;
            score: number;
        }[];
    } | {
        [x: string]: unknown;
        v: 1;
        ok: false;
        errorCode: 'memory_disabled' | 'memory_key_unavailable' | 'memory_index_missing' | 'memory_invalid_query' | 'memory_failed';
        error: string;
    };
    readonly "memory.get_window": {
        [x: string]: unknown;
        v: 1;
        snippets: {
            [x: string]: unknown;
            sessionId: string;
            seqFrom: number;
            seqTo: number;
            createdAtFromMs: number;
            createdAtToMs: number;
            text: string;
        }[];
        citations: {
            [x: string]: unknown;
            sessionId: string;
            seqFrom: number;
            seqTo: number;
        }[];
    };
    readonly "memory.ensure_up_to_date": {
        [x: string]: unknown;
        ok: boolean;
    };
};
