export const LEGACY_PAIRING_UPDATE_REQUIRED_RESTORE_ROUTE_PARAM = 'legacyPairingUpdateRequired';

export const LEGACY_PAIRING_UPDATE_REQUIRED_RESTORE_ROUTE_PATH =
    `/restore?${LEGACY_PAIRING_UPDATE_REQUIRED_RESTORE_ROUTE_PARAM}=1`;
