/**
 * The packaged browser Iroh assets (Lane 06 amendment A7.2/A7.5).
 *
 * The wasm-bindgen boundary generated from `happier-iroh-wasm` and the
 * SharedWorker bootstrap that hosts the endpoint owner are static files served
 * from the app's own origin under `vendor/iroh/`. They are produced
 * deterministically by `apps/ui/tools/iroh/buildBrowserIrohAssets.mjs` from the
 * A7.1 build owner, which stages them into the web output that build owns (never
 * a shared source tree the Tauri and native exports also copy); nothing at
 * runtime reads Cargo's ignored `target/` output, fetches from a CDN, shells out
 * to a system tool, or generates them on demand.
 *
 * They are also never referenced at startup. The dormant stream foundation does
 * not change that: the only place these URLs are read is the moment an eligible
 * caller explicitly asks the client to connect.
 */

/** Path segment under the app's web static root, appended to the document base. */
export const BROWSER_IROH_ASSET_DIRECTORY = 'vendor/iroh';

/** The SharedWorker bootstrap that hosts the one endpoint owner. */
export const BROWSER_IROH_WORKER_ASSET = 'happier-iroh-worker.js';

/** The generated wasm-bindgen JS boundary and its module. */
export const BROWSER_IROH_WASM_GLUE_ASSET = 'happier_iroh_wasm.js';
export const BROWSER_IROH_WASM_BINARY_ASSET = 'happier_iroh_wasm_bg.wasm';
export const BROWSER_IROH_WASM_TYPES_ASSET = 'happier_iroh_wasm.d.ts';
export const BROWSER_IROH_WASM_BINARY_TYPES_ASSET = 'happier_iroh_wasm_bg.wasm.d.ts';

/** Records the exact generated bytes the app was packaged with. */
export const BROWSER_IROH_ASSET_MANIFEST = 'manifest.json';

/**
 * Every file the packaging step must place under {@link BROWSER_IROH_ASSET_DIRECTORY}.
 * The packaging tool reads this same list through its own contract test, so a
 * rename cannot land on one side only and 404 at runtime.
 */
export const BROWSER_IROH_PACKAGED_ASSETS = [
    BROWSER_IROH_WORKER_ASSET,
    BROWSER_IROH_WASM_GLUE_ASSET,
    BROWSER_IROH_WASM_BINARY_ASSET,
    BROWSER_IROH_WASM_TYPES_ASSET,
    BROWSER_IROH_WASM_BINARY_TYPES_ASSET,
] as const;

/** The one asset URL rule. `base` is the document origin/base URL. */
export function browserIrohAssetUrl(assetName: string, base: string): string {
    return new URL(`${BROWSER_IROH_ASSET_DIRECTORY}/${assetName}`, base).toString();
}
